### ISSUE TITLE
Got AnonymousUser when accessing self.message.user on slow network

### ISSUE THREAD

**Issue by trixn86** [django/channels#1014]
# OS and runtime environment, and browser
macOS High Sierra, python 3.6

# versions of Channels, Daphne, Django, Twisted, and your ASGI backend
- channels==1.1.8
- daphne==1.4.2
- Django==1.11.11
- Twisted==17.1.0
- redis==2.10.6

# What you expected to happen 

This is how the consumer looks like:

``` python
class NotificationsDispatcher(WebSocketDispatcher):
    """
    Dispatches messages in the notifications scope.
    """

    http_user = True

    consumers = (
        NotificationsConsumer,
    )

    @property
    def user(self) -> ReSourceUser:
        """
        Returns the current message's user.
        """

        return self.message.user

    @property
    def group(self) -> JsonGroup:
        """
        Return the current user's group.
        """

        return self.user.group

    def connect(self, message, **kwargs):
        """
        Add the message channel to the user's group and send him unread notifications.
        """

        super(NotificationsDispatcher, self).connect(message, **kwargs)

        self.group.add(self.message.reply_channel)

        user: ReSourceUser = self.user

        for medal in user.unnotified_medals:
            medal.notify(user)

    def disconnect(self, message, **kwargs):
        """
        Remove the message channel from the user's group.
        """

        self.group.discard(self.message.reply_channel)
```
Wenn the websocket disconnects, the current users reply channel should be removed from the group we are delivering notifications to.

# What actually happened

We were using [comcast](https://github.com/tylertreat/comcast) to simulate a shitty network. When reducing the quality to very low and dropping 10% of packages the `disconnect()` handler tries to read the reply channel from `self.message.user` but it is `AnonymousUser` instead of the authenticated user. This does only happen when slowing down the network quality.

# How you're running Channels
Via django development server (runserver)

# Console logs and full tracebacks of any errors
[2018/04/12 16:15:01] WebSocket CONNECT /websocket/notifications/ [192.168.60.56:53406]
[2018/04/12 16:15:01] WebSocket DISCONNECT /websocket/notifications/ [192.168.60.56:53406]
2018-04-12 16:15:04,526 - ERROR - worker - Error processing message with consumer *****.consumers.notifications.NotificationsDispatcher:
Traceback (most recent call last):
  File "/Users/benjamin/Repos/resource-django/env/lib/python3.6/site-packages/channels/worker.py", line 119, in run
    consumer(message, **kwargs)
  File "/Users/benjamin/Repos/resource-django/env/lib/python3.6/site-packages/channels/generic/base.py", line 32, in __init__
    self.dispatch(message, **kwargs)
  File "/Users/benjamin/Repos/resource-django/env/lib/python3.6/site-packages/channels/generic/base.py", line 70, in dispatch
    return self.get_handler(message, **kwargs)(message, **kwargs)
  File "/Users/benjamin/Repos/resource-django/env/lib/python3.6/site-packages/channels/sessions.py", line 220, in inner
    result = func(message, *args, **kwargs)
  File "/Users/benjamin/Repos/resource-django/env/lib/python3.6/site-packages/channels/auth.py", line 73, in inner
    return func(message, *args, **kwargs)
  File "/Users/benjamin/Repos/resource-django/env/lib/python3.6/site-packages/channels/sessions.py", line 78, in inner
    return func(*args, **kwargs)
  File "/Users/benjamin/Repos/resource-django/env/lib/python3.6/site-packages/channels/auth.py", line 89, in inner
    return func(message, *args, **kwargs)
  File "/Users/benjamin/Repos/resource-django/env/lib/python3.6/site-packages/channels/sessions.py", line 54, in inner
    return func(*args, **kwargs)
  File "/Users/benjamin/Repos/resource-django/env/lib/python3.6/site-packages/channels/auth.py", line 42, in inner
    return func(message, *args, **kwargs)
  File "/Users/benjamin/Repos/resource-django/env/lib/python3.6/site-packages/channels/generic/websockets.py", line 136, in raw_disconnect
    self.disconnect(message, **kwargs)
  File "/Users/benjamin/Repos/resource-django/mpi_resource/consumers/notifications.py", line 98, in disconnect
    self.group.discard(self.message.reply_channel)
  File "/Users/benjamin/Repos/resource-django/mpi_resource/consumers/notifications.py", line 77, in group
    return self.user.group
AttributeError: 'AnonymousUser' object has no attribute 'group'

**Comment by andrewgodwin** [comment]
This appears to be for Channels 1, which I'm afraid is no longer supported and so I can't help you - sorry.
