### ISSUE TITLE
AttributeError: 'AsgiRequest' object has no attribute 'session'

### ISSUE THREAD

**Issue by DiegoGallegos4** [django/channels#1031]
Got an error when trying that was thrown when using social-app-django (2.1.0)

- Running under Alpine:3.7
- channels 1.1.8, Django 2.0.3, asgi-redis 1.2.0
- Running via *python manage.py runserver* (local env)

The error traceback for access /social/login/google-oauth2/ (authenticating with google account) is the following: 
> Traceback (most recent call last):
  File "/Users/diegogallegos/anaconda2/envs/merlin2/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/diegogallegos/anaconda2/envs/merlin2/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/diegogallegos/anaconda2/envs/merlin2/lib/python3.6/site-packages/channels/handler.py", line 243, in process_exception_by_middleware
    return super(AsgiHandler, self).process_exception_by_middleware(exception, request)
  File "/Users/diegogallegos/anaconda2/envs/merlin2/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/diegogallegos/anaconda2/envs/merlin2/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/diegogallegos/anaconda2/envs/merlin2/lib/python3.6/site-packages/social_django/utils.py", line 38, in wrapper
    request.social_strategy = load_strategy(request)
  File "/Users/diegogallegos/anaconda2/envs/merlin2/lib/python3.6/site-packages/social_django/utils.py", line 23, in load_strategy
    return get_strategy(STRATEGY, STORAGE, request)
  File "/Users/diegogallegos/anaconda2/envs/merlin2/lib/python3.6/site-packages/social_core/utils.py", line 279, in get_strategy
    return Strategy(Storage, *args, **kwargs)
  File "/Users/diegogallegos/anaconda2/envs/merlin2/lib/python3.6/site-packages/social_django/strategy.py", line 39, in __init__
    self.session = request.session if request else {}
AttributeError: 'AsgiRequest' object has no attribute 'session'
ERROR 2018-04-24 20:31:27,347 Internal Server Error: /social/login/google-oauth2/
Traceback (most recent call last):
  File "/Users/diegogallegos/anaconda2/envs/merlin2/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/diegogallegos/anaconda2/envs/merlin2/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/diegogallegos/anaconda2/envs/merlin2/lib/python3.6/site-packages/channels/handler.py", line 243, in process_exception_by_middleware
    return super(AsgiHandler, self).process_exception_by_middleware(exception, request)
  File "/Users/diegogallegos/anaconda2/envs/merlin2/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/diegogallegos/anaconda2/envs/merlin2/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/diegogallegos/anaconda2/envs/merlin2/lib/python3.6/site-packages/social_django/utils.py", line 38, in wrapper
    request.social_strategy = load_strategy(request)
  File "/Users/diegogallegos/anaconda2/envs/merlin2/lib/python3.6/site-packages/social_django/utils.py", line 23, in load_strategy
    return get_strategy(STRATEGY, STORAGE, request)
  File "/Users/diegogallegos/anaconda2/envs/merlin2/lib/python3.6/site-packages/social_core/utils.py", line 279, in get_strategy
    return Strategy(Storage, *args, **kwargs)
  File "/Users/diegogallegos/anaconda2/envs/merlin2/lib/python3.6/site-packages/social_django/strategy.py", line 39, in __init__
    self.session = request.session if request else {}
AttributeError: 'AsgiRequest' object has no attribute 'session'

**Comment by andrewgodwin** [comment]
This is not a Channels error - your Django middleware is misconfigured (did you remember that `MIDDLEWARE_CLASSES` is now `MIDDLEWARE`?)

**Comment by DiegoGallegos4** [comment]
Yes, it is *MIDDLEWARE* not *MIDDLEWARE_CLASSES*. What else can the problem can be?

**Comment by andrewgodwin** [comment]
I don't know - but that is a symptom of Django middleware not working, not Channels internals. You'll have to investigate further yourself.
