### ISSUE TITLE
Getting  error when i am trying to run djnago localhost on the browser it is saying " 500 Internal Server Error Daphne HTTP processing error  Daphne"

### ISSUE THREAD

**Issue by pradeepchauhan7** [django/channels#1035]
The following error is shown on the terminal where i have run the django server : 

System check identified no issues (0 silenced).
April 26, 2018 - 05:20:06
Django version 2.0.4, using settings 'chantest.settings'
Starting ASGI/Channels version 2.1.1 development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
2018-04-26 05:20:07,129 - INFO - server - HTTP/2 support enabled
2018-04-26 05:20:07,131 - INFO - server - Configuring endpoint tcp:port=8000:interface=127.0.0.1
2018-04-26 05:20:07,135 - INFO - server - Listening on TCP address 127.0.0.1:8000
2018-04-26 05:20:20,030 - ERROR - http_protocol - Traceback (most recent call last):
  File "/home/pradeep/.local/lib/python3.6/site-packages/daphne/http_protocol.py", line 160, in process
    "server": self.server_addr,
  File "/home/pradeep/.local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/pradeep/.local/lib/python3.6/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/pradeep/.local/lib/python3.6/site-packages/daphne/server.py", line 186, in create_application
    application_instance = yield deferToThread(self.application, scope=scope)
  File "/home/pradeep/.local/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/home/pradeep/.local/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/home/pradeep/.local/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/pradeep/.local/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/pradeep/.local/lib/python3.6/site-packages/channels/staticfiles.py", line 41, in __call__
    return self.application(scope)
TypeError: 'RedisChannelLayer' object is not callable

[2018/04/26 05:20:20] HTTP GET / 500 [0.10, 127.0.0.1:57846]
2018-04-26 05:20:20,317 - ERROR - http_protocol - Traceback (most recent call last):
  File "/home/pradeep/.local/lib/python3.6/site-packages/daphne/http_protocol.py", line 160, in process
    "server": self.server_addr,
  File "/home/pradeep/.local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/pradeep/.local/lib/python3.6/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/pradeep/.local/lib/python3.6/site-packages/daphne/server.py", line 186, in create_application
    application_instance = yield deferToThread(self.application, scope=scope)
  File "/home/pradeep/.local/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/home/pradeep/.local/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/home/pradeep/.local/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/pradeep/.local/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/pradeep/.local/lib/python3.6/site-packages/channels/staticfiles.py", line 41, in __call__
    return self.application(scope)
TypeError: 'RedisChannelLayer' object is not callable

[2018/04/26 05:20:20] HTTP GET /favicon.ico 500 [0.00, 127.0.0.1:57846]

**Comment by andrewgodwin** [comment]
I suspect your `CHANNEL_LAYER` settings are wrong - you are passing a pre-instantiated instance. Check that your settings match the documentation and you have the right object name (`channels_redis.core.RedisChannelLayer`): https://github.com/django/channels_redis/blob/master/README.rst

**Comment by pradeepchauhan7** [comment]
Still facing the same issue and the same error

**Comment by andrewgodwin** [comment]
Post your CHANNEL_LAYER settings and I will see if they are right

**Comment by nsanor** [comment]
I am facing the same issue. Here is my CHANNEL_LAYER settings:

```
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("localhost", 6379)],
        },
    },
}
```

**Comment by yevkorzhyk** [comment]
@pradeepchauhan7, do you have right asgi.py file?
I had have the same error message and the issue for me was in this file.
The file with which my project works:
```
import os
import django
from channels.routing import get_default_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "myproject.settings")
django.setup()
application = get_default_application()
```

**Comment by nimishbansal** [comment]
Yes I am also having the same issue 
my asgi.py
```
import os
import django
from channels.routing import get_default_application
from channels.layers import get_channel_layer

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "myproject.settings")
django.setup()
channel_layer = get_channel_layer()
application = get_default_application()
```


and myprocfile is:

web: daphne chat.asgi:channel_layer --port $PORT --bind 0.0.0.0 -v2
