### ISSUE TITLE
No 'message.http_session` when user=AnonymousUser (and production only issue)

### ISSUE THREAD

**Issue by typistX** [django/channels#1094]
**- Your OS and runtime environment, and browser if applicable**

Site is running on Heroku, with following Procfile:

```
web: daphne artist_notify.asgi:channel_layer --port $PORT --bind 0.0.0.0 -v1
worker: python manage.py migrate --noinput && python manage.py runworker -v1
celerybeat: celery -A artist_notify beat -l info
celeryworker: celery -A artist_notify worker -l info
```

**- The versions of Channels, Daphne, Django, Twisted, and your ASGI backend (channels_redis normally)**

channels==1.1.8 (catching up with 2 is unrealistic for us as we just launched and we started building early)
daphne==1.3.0
Twisted==17.9.0

**- What you expected to happen vs. what actually happened**

I expected to have access to `message.http_session` in `ws_connect`, but it is always none when user is AnonymousUser. Even when employing a workaround, **it works locally, but not in production**.

Below is my code:

**consumers.py**

```python
# also tried channel_session_user_from_http
@channel_and_http_session_user_from_http
def ws_connect(message):
    # create group for user

    if str(message.user) == "AnonymousUser":
        user_group = message.http_session['get_user'] 
    else:
        user_group = str(message.user.id)

    Group(user_group).add(message.reply_channel)
    Group(user_group).send({"accept": True})
    message.channel_session['get_user'] = user_group
   message.http_session['get_user'] = user_group
   # already tried message.http_session.save()
```

This is supposed to work, but it doesn't. I get an error that message has no attribute `http_session`. So I employed a workaround in my view, but it only works locally and not in production:

**views.py -> the "gateway" view**

```python
if hasattr(request, 'session') and not request.session.session_key:
        if not request.user.is_authenticated:
            request.session.create()
            request.session['get_user'] = "AnonymousUser" + str(uuid.uuid4())
            request.session.modified = True
```

This checks whether the user isn't authenticated, and assigns the session key, which allows me to send messages to each distinct AnonymousUser. When an `AnonymousUser` connects, he's already assigned a session key `get_user`, which the consumer can simply use. It works in development.

But it doesn't work in production, for a reason I cannot understand. My only guess is that locally, the view is called, and then the consumer, and in production it happens in together?

**- How you're running Channels (runserver? daphne/runworker? Nginx/Apache in front?)**

runserver in local, Procfile in Heroku (production)

- Console logs and full tracebacks of any errors

```
2018-07-07T13:42:52.008456+00:00 app[worker.1]: 2018-07-07 16:42:52,007 - ERROR - worker - Error processing message with consumer core.consumers.ws_disconnect:

2018-07-07T13:42:52.008474+00:00 app[worker.1]: Traceback (most recent call last):

2018-07-07T13:42:52.008476+00:00 app[worker.1]:   File "/app/core/consumers.py", line 27, in ws_disconnect

2018-07-07T13:42:52.008478+00:00 app[worker.1]:     user_group = message.channel_session['get_user']

2018-07-07T13:42:52.008480+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 57, in __getitem__

2018-07-07T13:42:52.008482+00:00 app[worker.1]:     return self._session[key]

2018-07-07T13:42:52.008483+00:00 app[worker.1]: KeyError: 'get_user'

2018-07-07T13:42:52.008485+00:00 app[worker.1]: 

2018-07-07T13:42:52.008487+00:00 app[worker.1]: During handling of the above exception, another exception occurred:

2018-07-07T13:42:52.008489+00:00 app[worker.1]: 

2018-07-07T13:42:52.008491+00:00 app[worker.1]: Traceback (most recent call last):

2018-07-07T13:42:52.008493+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/channels/worker.py", line 119, in run

2018-07-07T13:42:52.008494+00:00 app[worker.1]:     consumer(message, **kwargs)

2018-07-07T13:42:52.008496+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/channels/sessions.py", line 78, in inner

2018-07-07T13:42:52.008497+00:00 app[worker.1]:     return func(*args, **kwargs)

2018-07-07T13:42:52.008499+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/channels/auth.py", line 42, in inner

2018-07-07T13:42:52.008500+00:00 app[worker.1]:     return func(message, *args, **kwargs)

2018-07-07T13:42:52.008502+00:00 app[worker.1]:   File "/app/core/consumers.py", line 29, in ws_disconnect

2018-07-07T13:42:52.008504+00:00 app[worker.1]:     user_group = message.http_session['get_user']

2018-07-07T13:42:52.008510+00:00 app[worker.1]: AttributeError: 'Message' object has no attribute 'http_session'
```

Strangely, depsite these pesky errors - the users are getting messages through. But I'm curious why this is not working and I don't want my logs clogged like this every time an unauthenticated user visits my site.

**Comment by typistX** [comment]
I realized from other threads that support for 1 is gone. So I upgraded to Channels 2 but I'm facing similar issues. [Opened a separate issue and closing this one.](https://github.com/django/channels/issues/1096)
