### ISSUE TITLE
Event loop is closed & name 'open' is not defined when using sync_to_async in testing

### ISSUE THREAD

**Issue by robben1234** [django/channels#1112]
I have a very simple test code which until recently was passing just OK:

```
@database_sync_to_async
def test_error_no_access_response(response):
    data = json.loads(response)
    assert data.get('error') == 'USER_HAS_NO_ACCESS'
    return True
...
@pytest.mark.django_db
@pytest.mark.asyncio
async def test_my_consumer(): 
    communicator = WebsocketCommunicator(ChatConsumer, "GET", "/test/")
    communicator.scope['url_route'] = dict(kwargs=dict(room='1-1'))
    connected, subprotocol = await communicator.connect()
...
    await communicator.send_json_to(data=message_data)
    response = await communicator.receive_from()
    is_valid_response = await test_error_no_access_response(response)
    assert is_valid_response == True
```
But today I ran suite and it failed without any context relevant to my consumer. With `print` statements I've discovered it fails on `is_valid_response = await test_error_no_access_response(response)`. I think it's either a bug with channels or asgiref.

Here's traceback:
```
Exception ignored in: <bound method BaseEventLoop.call_exception_handler of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 1291, in call_exception_handler
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 1335, in error
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 1442, in _log
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 1452, in handle
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 1514, in callHandlers
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 863, in handle
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 1069, in emit
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 1059, in _open
NameError: name 'open' is not defined
Exception ignored in: <coroutine object AsyncConsumer.__call__ at 0x1088e1d58>
Traceback (most recent call last):
  File "/Users/robben1234/.envs/project/lib/python3.6/site-packages/channels/consumer.py", line 54, in __call__
  File "/Users/robben1234/.envs/project/lib/python3.6/site-packages/channels/utils.py", line 55, in await_many_dispatch
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 574, in call_soon
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 357, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <bound method BaseEventLoop.call_exception_handler of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 1291, in call_exception_handler
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 1335, in error
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 1442, in _log
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 1452, in handle
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 1514, in callHandlers
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 863, in handle
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 1069, in emit
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 1059, in _open
NameError: name 'open' is not defined
```

I'm running it on MacOS 10.13.4. Here're versions of channels and it's dependencies from pip:
```
aioredis==1.1.0
asgiref==2.3.2
channels==2.1.2
channels-redis==2.2.1
daphne==2.2.1
Django==1.11.12
pytest==3.6.3
pytest-asyncio==0.8.0
pytest-django==3.3.2
Twisted==18.7.0
```

**Comment by andrewgodwin** [comment]
I'm very curious how the builtin function `open` isn't defined - that points to something deeply wrong with your Python installation. Have you tried to reproduce this on another machine?

**Comment by andrewgodwin** [comment]
Closing due to inactivity - reopen if you can get this failing on any machine with a small sample project (see http://channels.readthedocs.io/en/latest/support.html)

**Comment by pguyot** [comment]
Got the same error, not related at all to an issue with a Python installation. In my case the bug was caused by a broken mix of async & sync functions.
