### ISSUE TITLE
Trying to get channels2 working on AWS Elastic Beanstalk

### ISSUE THREAD

**Issue by omelao** [django/channels#1143]
Please, I need help.

Im trying with WSGIPath in wsgi.py and Im getting this error:

```
Traceback (most recent call last):

File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
response = get_response(request)

File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
resolver_match = resolver.resolve(request.path_info)

File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 523, in resolve
raise Resolver404({'tried': tried, 'path': new_path})

django.urls.exceptions.Resolver404: {'tried': [[<URLPattern '^$' [name='home']>], [<URLPattern '^comunidade/'>]], 'path': 'socket/comunidade/'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 99, in get_exception_response
response = callback(request, **dict(param_dict, exception=exception))

TypeError: handler404() got an unexpected keyword argument 'exception'
```

My routing.py:
```
application = ProtocolTypeRouter({

    "websocket": OriginValidator(
        AuthMiddlewareStack(
            URLRouter([
                # URLRouter just takes standard Django path() or url() entries.
                path("socket/", Mymethod),
                url("socket/(?P<slug>[\w-]+)", Mymethod),
            ]),
        ),
        settings.CHANNELS_ALLOWED_HOSTS
    ),
```

My JS connection:
```
var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
var connection = new ReconnectingWebSocket( ws_scheme + "://" + window.location.host + "/socket" + window.location.pathname );
```

Works fine on localhost....but doesnt work on AWS.

**Comment by andrewgodwin** [comment]
I'm afraid we can't help with problems that only happen on a single environment (see https://channels.readthedocs.io/en/latest/support.html) - they have to be reproduceable on a local machine. I suggest you look for support from AWS or other people familiar with it, sorry.

**Comment by omelao** [comment]
Ok, I understand, but I just want to know about this error....it seems to be trying to route channels in urls.py. Any idea?

**Comment by manceelee** [comment]
having some issues when i try to deploy to aws, have you find any solution yet?  Thanks.
