### ISSUE TITLE
ImportError: cannot import name 'DEFAULT_CHANNEL_LAYER'

### ISSUE THREAD

**Issue by mrParabol** [django/channels#1155]
when i give the following command i get the following error.Thank you in advance for your help.

```
sudo python3.6 manage.py shell
import channels.layers

```
and then

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/channels/layers.py", line 15, in <module>
    from channels import DEFAULT_CHANNEL_LAYER
ImportError: cannot import name 'DEFAULT_CHANNEL_LAYER'

```
necessary information:
```
python3.6, django2.1, django-channels2.1.3
>>>import channels; print(channels.__file__)
output
/usr/local/lib/python3.6/dist-packages/channels/__init__.py


```

**Comment by mrParabol** [comment]
The problem improved when install as follows:
`sudo python3.6 -m pip install git+https://github.com/django/channels.git --upgrade`
