### ISSUE TITLE
Not able to set up asgi server.

### ISSUE THREAD

**Issue by Prskriti** [django/channels#1166]
C:\Users\shaprakr\Desktop\Pro\website>python manage.py migrate

C:\Users\shaprakr\Desktop\Pro\website>python manage.py runserver
Unhandled exception in thread started by <function check_errors.<locals>.wrapper
 at 0x000000108A936B70>
Traceback (most recent call last):
  File "C:\Users\shaprakr\AppData\Local\Continuum\anaconda3\lib\site-packages\dj
ango\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\shaprakr\AppData\Local\Continuum\anaconda3\lib\site-packages\dj
ango\core\management\commands\runserver.py", line 112, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\shaprakr\AppData\Local\Continuum\anaconda3\lib\site-packages\dj
ango\utils\autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "C:\Users\shaprakr\AppData\Local\Continuum\anaconda3\lib\site-packages\dj
ango\core\management\__init__.py", line 327, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\shaprakr\AppData\Local\Continuum\anaconda3\lib\site-packages\dj
ango\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\shaprakr\AppData\Local\Continuum\anaconda3\lib\site-packages\dj
ango\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\shaprakr\AppData\Local\Continuum\anaconda3\lib\site-packages\dj
ango\apps\registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\shaprakr\AppData\Local\Continuum\anaconda3\lib\site-packages\dj
ango\apps\config.py", line 116, in create
    mod = import_module(mod_path)
  File "C:\Users\shaprakr\AppData\Local\Continuum\anaconda3\lib\importlib\__init
__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\shaprakr\AppData\Local\Continuum\anaconda3\lib\site-packages\ch
annels\apps.py", line 6, in <module>
    import daphne.server  # noqa
ModuleNotFoundError: No module named 'daphne'

**Comment by andrewgodwin** [comment]
This is not a general support forum - please see http://channels.readthedocs.io/en/latest/support.html for more. It looks like you did not install channels properly.
