### ISSUE TITLE
Django Channels Worker is returning TypeError: zadd() got an unexpected keyword argument 'daphne

### ISSUE THREAD

**Issue by phsantosjr** [django/channels#1270]
In my server, i am running a Daphne and a Worker for Django Channels.

I have already reboot all containers (I use Docker), cleaned Redis Cache.

Today, these applications stoped to work and return this stack:

KeyError: 'leads-198'
2019-03-27 13:51:59,719 - ERROR - worker - Error processing message with consumer crm.consumers.ws_connect:
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/channels/worker.py", line 119, in run
consumer(message, **kwargs)
File "/usr/local/lib/python3.6/site-packages/channels/sessions.py", line 78, in inner
return func(*args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/channels/auth.py", line 42, in inner
return func(message, *args, **kwargs)
File "/opt/app/integrador/crm/consumers.py", line 10, in ws_connect
Group(group).add(message.reply_channel)
File "/usr/local/lib/python3.6/site-packages/channels/channel.py", line 70, in add
self.channel_layer.group_add(self.name, channel)
File "/usr/local/lib/python3.6/site-packages/asgi_redis/core.py", line 291, in group_add
**{channel: time.time()}
TypeError: zadd() got an unexpected keyword argument 'daphne.response.lGekRGuTPv!bsgpJbNJLP'
crm - is my app in Django

leads-198 - is the group of Channels

Requirements.txt:

boto3

coreapi

Django==1.11

asgi_redis==1.2.1

channels==1.1.8

daphne==1.3

celery==4.1

PyMySQL

djangorestframework==3.7.7

django-oauth-toolkit==0.12.0

django-cors-headers==2.1.0

django-redis==4.5.0

django-storages==1.5.1

raven==5.30.0

jsonfield==1.0.3

requests==2.18.4

simplejson

suds-py3==1.3.2.0

xmltodict==0.10.2

Any suggestion ?

Thanks

**Comment by carltongibson** [comment]
Looks like a redis compatibly issue. (Check versions of redis and py-redis etc)

Will close assuming it’s that. If it’s a issue with Channels please come back to us.

**Comment by atb00ker** [comment]
Find answer here: https://stackoverflow.com/a/57790885/6410464
