### ISSUE TITLE
Twisted exception when TLS is used with Daphne on Windows 10

### ISSUE THREAD

**Issue by raceybe** [django/channels#1297]
I get the following trace back after around 30 seconds from the last request. I'm using Daphne on Windows 10. My Channels version is 2.2.0, and Daphne is 2.3.0, with Twisted at 19.2.0.

The exception appears to come from Twisted, but perhaps may be triggered by Channels.

`2019-05-03 12:41:45,252 ERROR    Exception in callback AsyncioSelectorReactor.callLater.<locals>.run() at c:\users\user\virtualenvs\channels_test\lib\site-packages\twisted\internet\asyncioreactor.py:287
handle: <TimerHandle when=56886.125 AsyncioSelectorReactor.callLater.<locals>.run() at c:\users\user\virtualenvs\channels_test\lib\site-packages\twisted\internet\asyncioreactor.py:287>
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "c:\users\user\virtualenvs\channels_test\lib\site-packages\twisted\internet\asyncioreactor.py", line 290, in run
    f(*args, **kwargs)
  File "c:\users\user\virtualenvs\channels_test\lib\site-packages\twisted\web\http.py", line 2339, in forceAbortClient
    self.transport.abortConnection()
  File "c:\users\user\virtualenvs\channels_test\lib\site-packages\twisted\protocols\tls.py", line 435, in abortConnection
    self._shutdownTLS()
  File "c:\users\user\virtualenvs\channels_test\lib\site-packages\twisted\protocols\tls.py", line 338, in _shutdownTLS
    shutdownSuccess = self._tlsConnection.shutdown()
AttributeError: 'NoneType' object has no attribute 'shutdown'`

**Comment by carltongibson** [comment]
Hi. Could you put together a minimal example that reproduces this (with any necessary instructions)? 
Happy to have a look but can't say much right now.

**Comment by raceybe** [comment]
Sure I could do that. The server runs fine even when it shows up (it's been running on my laptop for about a month). Can I provide instructions with the Windows setup or do you want/need a linux VM or something?

**Comment by carltongibson** [comment]
I have Windows 10 available. So, instructions for there. (No doubt just "run this" but... 🙂)

**Comment by raceybe** [comment]
Just a curiousity...is there test coverage for TLS scenarios? If so, is there a description of the test, so perhaps I could track down what is different about my configuration?

**Comment by carltongibson** [comment]
Right, well, we should almost certainly be on the Daphne repo here, and probably on Twisted TBH... but there's nothing specifically _HTTPS_ here https://github.com/django/daphne/tree/master/tests

**Comment by raceybe** [comment]
Hmm, I'll take a look through to see if anything pops up once I make a zip available.

**Comment by raceybe** [comment]
I have attached a zip that should work on windows. The Django project was setup with the steps shown below if you wish to recreate it from scratch. I ran the server after each step, and it wasn't until I did `pip install -U twisted[http2,tls]` that the error showed up. The `run_daphne.bat` file shows the command I use to run Daphne.

[daphnetls.zip](https://github.com/django/channels/files/3253073/daphnetls.zip)

After you run Daphne, you need to make a request to the web server, then wait about 75 seconds or so. The message will show up on the console (repeated at the end of this comment).

pip install channels, pypiwin32
pip install -U twisted[http2,tls]

Basic Setup
https://channels.readthedocs.io/en/latest/tutorial/part_1.html#integrate-the-channels-library

Daphne Setup
https://channels.readthedocs.io/en/latest/deploying.html#run-protocol-servers

HTTP2/TLS setup
https://github.com/django/daphne#http2-support

Certificate generated with
https://certificatetools.com/

`2019-06-04 11:07:35,614 INFO     Starting server at ssl:4443:privateKey=cert.key:certKey=cert.crt
2019-06-04 11:07:35,615 INFO     HTTP/2 support enabled
2019-06-04 11:07:35,617 INFO     Configuring endpoint ssl:4443:privateKey=cert.key:certKey=cert.crt
2019-06-04 11:07:35,629 INFO     Listening on TCP address 0.0.0.0:4443
127.0.0.1:61588 - - [04/Jun/2019:11:09:24] "GET /" 200 16348
Not Found: /static/admin/css/fonts.css
2019-06-04 11:09:24,980 WARNING  Not Found: /static/admin/css/fonts.css
127.0.0.1:61588 - - [04/Jun/2019:11:09:24] "GET /static/admin/css/fonts.css" 404 2021
2019-06-04 11:10:39,547 ERROR    Exception in callback AsyncioSelectorReactor.callLater.<locals>.run() at c:\users\brian\virtualenvs\daphnetls\lib\site-packages\twisted\internet\asyncioreactor.py:287
handle: <TimerHandle when=1476254.671 AsyncioSelectorReactor.callLater.<locals>.run() at c:\users\brian\virtualenvs\daphnetls\lib\site-packages\twisted\internet\asyncioreactor.py:287>
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "c:\users\brian\virtualenvs\daphnetls\lib\site-packages\twisted\internet\asyncioreactor.py", line 290, in run
    f(*args, **kwargs)
  File "c:\users\brian\virtualenvs\daphnetls\lib\site-packages\twisted\web\http.py", line 2339, in forceAbortClient
    self.transport.abortConnection()
  File "c:\users\brian\virtualenvs\daphnetls\lib\site-packages\twisted\protocols\tls.py", line 435, in abortConnection
    self._shutdownTLS()
  File "c:\users\brian\virtualenvs\daphnetls\lib\site-packages\twisted\protocols\tls.py", line 338, in _shutdownTLS
    shutdownSuccess = self._tlsConnection.shutdown()
AttributeError: 'NoneType' object has no attribute 'shutdown'`

**Comment by carltongibson** [comment]
Hi @raceybe. Thanks for the project. Not immediately but, I'll have a play and get back to you. 

> The server runs fine even when it shows up (it's been running on my laptop for about a month)

Not critical then. 🙂

**Comment by aalvarez** [comment]
Good Morning .... 

The same problem over debian server. No critical because not halt the execution code ...

Python 3.7.3 
Channels 2.3.0
channels-redis 2.4.0
Twisted 19.7.0


2019-10-20 09:38:56,608 ERROR    Exception in callback AsyncioSelectorReactor.callLater.<locals>.run() at /home/sigho/.env/sigho/lib/python3.7/site-packages/twisted/internet/asyncioreactor.py:287
handle: <TimerHandle when=39987880.95796866 AsyncioSelectorReactor.callLater.<locals>.run() at /home/sigho/.env/sigho/lib/python3.7/site-packages/twisted/internet/asyncioreactor.py:287>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/sigho/.env/sigho/lib/python3.7/site-packages/twisted/internet/asyncioreactor.py", line 290, in run
    f(*args, **kwargs)
  File "/home/sigho/.env/sigho/lib/python3.7/site-packages/twisted/web/http.py", line 2380, in forceAbortClient
    self.transport.abortConnection()
  File "/home/sigho/.env/sigho/lib/python3.7/site-packages/twisted/protocols/tls.py", line 435, in abortConnection
    self._shutdownTLS()
  File "/home/sigho/.env/sigho/lib/python3.7/site-packages/twisted/protocols/tls.py", line 338, in _shutdownTLS
    shutdownSuccess = self._tlsConnection.shutdown()
AttributeError: 'NoneType' object has no attribute 'shutdown'
