### ISSUE TITLE
Testing Invalid Syntax

### ISSUE THREAD

**Issue by kroeker97** [django/channels#1303]
Hello,

I try to write some tests my own, I can initialize a communicator like this
```python
communicator = WebsocketCommunicator(application, "/lobbylist/")
```

But whenever I try to call this method, a syntax error appears.
```python
connected, subprotocol = await communicator.connect()
```

Test without calling connect 
```
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
<channels.testing.websocket.WebsocketCommunicator object at 0x7ff519db9b38>
.
----------------------------------------------------------------------
Ran 1 test in 0.810s

OK
Destroying test database for alias 'default'...
```

Test with calling connect 
```
System check identified no issues (0 silenced).
E
======================================================================
ERROR: lobby.tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: lobby.tests
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/kroeker/cardholder/server-side/src/lobby/tests.py", line 31
    connected, subprotocol = await communicator.connect()
                                              ^
SyntaxError: invalid syntax
```

Is it a problem because of me? I just do it like in the documentation.

**Comment by carltongibson** [comment]
Not much I can say here...

> ImportError: Failed to import test module: lobby.tests

I'd look into this.

**Comment by kroeker97** [comment]
Was my fault after all
