### ISSUE TITLE
Must specify asyncio event loop selector for Windows on Python 3.8.  

### ISSUE THREAD

**Issue by rahimnagori** [django/channels#1396]
I have done
> pip install django
> pip install channels
> django-admin start project mysite
> cd mysite
> python manage.py startapp chat
Added the new 'chat' app in 'installed_apps'
Created chat/index.html
Then created chat/views.py
.....
Added 'channels' in 'installed_apps'
Added ASGI_APPLICATION = 'mysite.routing.application' in mysite/settings.py
At this point when I execute:
> python manage.py runserver
I'm using this on Win 10 machine.
I'm getting the following error : 

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "c:\users\win10\appdata\local\programs\python\python38-32\Lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "c:\users\win10\appdata\local\programs\python\python38-32\Lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\win10\PycharmProjects\profilics\chatenv\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\win10\PycharmProjects\profilics\chatenv\lib\site-packages\django\core\management\commands\runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\win10\PycharmProjects\profilics\chatenv\lib\site-packages\django\utils\autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "C:\Users\win10\PycharmProjects\profilics\chatenv\lib\site-packages\django\core\management\__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\win10\PycharmProjects\profilics\chatenv\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\win10\PycharmProjects\profilics\chatenv\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\win10\PycharmProjects\profilics\chatenv\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\win10\PycharmProjects\profilics\chatenv\lib\site-packages\django\apps\config.py", line 116, in create
    mod = import_module(mod_path)
  File "C:\Users\win10\PycharmProjects\profilics\chatenv\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\win10\PycharmProjects\profilics\chatenv\lib\site-packages\channels\apps.py", line 6, in <module>
    import daphne.server
  File "C:\Users\win10\PycharmProjects\profilics\chatenv\lib\site-packages\daphne\server.py", line 20, in <module>
    asyncioreactor.install(twisted_loop)
  File "C:\Users\win10\PycharmProjects\profilics\chatenv\lib\site-packages\twisted\internet\asyncioreactor.py", line 320, in install
    reactor = AsyncioSelectorReactor(eventloop)
  File "C:\Users\win10\PycharmProjects\profilics\chatenv\lib\site-packages\twisted\internet\asyncioreactor.py", line 69, in __init__
    super().__init__()
  File "C:\Users\win10\PycharmProjects\profilics\chatenv\lib\site-packages\twisted\internet\base.py", line 571, in __init__
    self.installWaker()
  File "C:\Users\win10\PycharmProjects\profilics\chatenv\lib\site-packages\twisted\internet\posixbase.py", line 286, in installWaker
    self.addReader(self.waker)
  File "C:\Users\win10\PycharmProjects\profilics\chatenv\lib\site-packages\twisted\internet\asyncioreactor.py", line 151, in addReader
    self._asyncioEventloop.add_reader(fd, callWithLogger, reader,
  File "c:\users\win10\appdata\local\programs\python\python38-32\Lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError

Does anyone have idea why I'm getting this error?

I have put my code to this repo's master branch : 
https://github.com/rahimnagori/django-channel

You may also check the code if you wish to.
I'm using windows machine.

**Comment by rahimnagori** [comment]
Anybody here to reply for this issue?

**Comment by globophobe** [comment]
You appear to be using python3.8 

I don’t have A Windows handy.

Apparently Twisted, which daphne is based on, doesn’t support python3.8 on Windows.

https://stackoverflow.com/questions/58908293/i-keep-getting-notimplementederror-error-when-starting-django-server

**Comment by rahimnagori** [comment]
@globophobe,
Any idea how to downgrade python without removing the current version?

**Comment by globophobe** [comment]
You don't have to downgrade. Just install another version. Google "multiple python versions", or something.

**Comment by carltongibson** [comment]
You've hit this over Christmas, so bad luck there. There's [a PR on Daphne](https://github.com/django/daphne/pull/298) that looks like it should resolve this, but that needs testing, and you'll need to wait for the new release. 

Until then, yes, Python 3.7 may be your best best. (The Windows `py` launcher handles multiple versions very well.) 


This is related to the Python issue https://bugs.python.org/issue37373

**Comment by carltongibson** [comment]
Daphne 2.5.0 is now on PyPI and should resolve this. 

It sets the event loop policy appropriately if you're on Windows and Python 3.8+. 
Please do upgrade.
