### ISSUE TITLE
Strange errors using Channels with daphne or Uvicorn on Kubernetes

### ISSUE THREAD

**Issue by oesah** [django/channels#1406]
In a nutshell: I cannot get Channels2 working on my Kubernetes Cluster, Channels1 works fine though. Because my issues happen with either daphne or uvicorn, I thought this might be the right place to open the ticket. I have no idea where the problem occurs exactly.

### What you expected to happen vs. what actually happened

So I have this very strange bug, that happens on all browsers, but in a different way, when I try to get Websockets with Channels working. I have an older setup with channels 1.x which works perfectly fine. Just when I try to upgrade to 2.x, I get these strange errors.

I tried with daphne and uvicorn. The core errors I get in the browser is, depending on whether uvicorn or daphne is used, are: 

**Daphne**
`ERR_CONNECTION_CLOSED 200`: This happens, after the page is loaded and the HTML is shown properly, the loading spinner of chrome just keeps spinning. After 10-20 seconds, it return this error. Websocket connection was not established. Strangely, in Firefox it keeps loading for a long time, then it makes the ajax requests and websocket connection.

`ERR_HTTP_PROTOCOL_ERROR`: This also happens in some scenarios, although the page is rendered fine.

**uvicorn**
`ERR_HTTP2_PROTOCOL_ERROR`: When I use uvicorn, firefox works perfectly fine, although in the logs I get the following error message `Response content shorter than Content-Length` for every request I make.

Chrome however, loads the request, but the page remains empty. When I look into the html if the page rendered, the `<body>` tag is completely missing, although `<html>` and `<head>` are rendered. 

In both cases, when I try to establish a websocket connection of console or terminal, it works fine. Rendering the page seems to be breaking for some reason.

### How you're running Channels (runserver? daphne/runworker? Nginx/Apache in front?)
- Application runs inside docker container on AWS with EKS Kubernetes Cluster
- I am using supervisord to start the application, although I also tried without it, same results

**supervisord config:**

```
[supervisord]
nodaemon=true
logfile=/app/supervisor.log
pidfile=/app/supervisor.pid

[program:daphne]
command=/usr/local/bin/daphne --proxy-headers config.asgi:application -p 5000 -b 0.0.0.0
stderr_logfile=/dev/fd/1
stderr_logfile_maxbytes=0
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0

redirect_stderr=true

numprocs=1
# Give each process a unique name so they can be told apart
process_name=asgi%(process_num)d

# Automatically start and recover processes
autostart=true
autorestart=true
```

I also tried a lot of different commands to start Django, here are a few examples, which are by far not all I tried:
```
/usr/local/bin/daphne config.asgi:application -p 5000 -b 0.0.0.0
/usr/local/bin/uvicorn config.asgi:application --port 5000 --host 0.0.0.0
/usr/local/bin/gunicorn -k uvicorn.workers.UvicornWorker config.asgi:application -b 0.0.0.0:5000
```
For Daphne I don't have any exceptions showing in the logs, but for uvicorn I get the following exception: https://github.com/encode/uvicorn/blob/master/uvicorn/protocols/http/httptools_impl.py#L515

```
[2020-01-24 23:05:24 +0100] [10] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.6/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.6/site-packages/uvicorn/middleware/asgi2.py", line 7, in __call__
    await instance(receive, send)
  File "/usr/local/lib/python3.6/site-packages/channels/http.py", line 192, in __call__
    await self.handle(body_stream)
  File "/usr/local/lib/python3.6/site-packages/asgiref/sync.py", line 244, in __call__
    return await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
    return (yield from fut)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/asgiref/sync.py", line 277, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/channels/http.py", line 250, in handle
    self.send(response_message)
  File "/usr/local/lib/python3.6/site-packages/asgiref/sync.py", line 116, in __call__
    return call_result.result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.6/site-packages/asgiref/sync.py", line 156, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py", line 515, in send
    raise RuntimeError("Response content shorter than Content-Length")
RuntimeError: Response content shorter than Content-Length
```

I also tried different version of the consumer from the official channels tutorials, but that does not seem to have an effect since establishing a websocket connection and communicating through that works.

In addition, I tried many different variations of the libraries needed, like `asgiref`, `channels`, `channels-redis`, etc.

### Your OS and runtime environment, and browser if applicable
- Kubernetes 1.14
- Python 3.6 (docker image)
- Chrome, Firefox, Safari

**Pip freeze**
```
aioredis==1.3.1
aldryn-apphooks-config==0.5.3
aldryn-boilerplates==0.8.0
aldryn-bootstrap3==1.3.0
aldryn-common==1.0.5
aldryn-search==1.0.1
amqp==1.4.9
anyjson==0.3.3
argon2-cffi==16.3.0
asgiref==3.2.3
async-timeout==3.0.1
attrs==19.3.0
autobahn==20.1.3
Automat==0.8.0
awesome-slugify==1.6.5
beautifulsoup4==4.6.0
bexio-api-python-client==0.1.5
billiard==3.3.0.23
boto3==1.10.7
botocore==1.13.50
braintree==3.58.0
celery==3.1.25
certifi==2019.11.28
cffi==1.13.2
channels==2.3.1
channels-redis==2.4.1
chardet==3.0.4
Click==7.0
cmsplugin-filer==1.1.3
Collectfast==1.3.1
constantly==15.1.0
cryptography==2.8
daphne==2.4.1
defusedxml==0.6.0
diff-match-patch==20181111
Django==1.11.27
django-allauth==0.40.0
django-anymail==0.10
django-appconf==1.0.3
django-appdata==0.2.2
django-autoslug==1.9.3
django-bootstrap-pagination==1.6.2
django-braces==1.11.0
django-celery==3.2.1
django-celery-email==1.1.5
django-ckeditor-filebrowser-filer==0.2.3
django-classy-tags==1.0.0
django-cms==3.4.5
django-compressor==2.3
django-crispy-forms==1.6.1
django-environ==0.4.3
django-filer==1.5.0
django-filter==1.0.4
django-formtools==2.1
django-hashers-passlib==0.4
django-haystack==2.8.2.dev86+g87bd4c1
django-htmlmin==0.10.0
django-import-export==0.5.1
django-invitations==1.9.2
django-ipware==2.1.0
django-js-asset==1.2.2
django-jsonview==1.0.0
django-loginas==0.3.2
django-mass-edit==3.0
django-meta==1.6.1
django-meta-mixin==0.3.0
django-model-utils==3.0.0
django-mptt==0.11.0
django-parler==1.9.2
django-payments==0.12.1
django-polymorphic==1.3.1
django-post-office==2.0.8
django-ranged-response==0.2.0
django-redis==4.8.0
django-sekizai==1.1.0
django-simple-captcha==0.5.12
django-sortedm2m==3.0.0
django-spurl==0.6.6
django-standard-form==1.1.1
django-storages==1.7.2
django-taggit==0.23.0
django-taggit-autosuggest==0.3.8
django-taggit-templatetags==0.2.5
django-templatetag-sugar==1.0
django-treebeard==4.3.1
djangocms-admin-style==1.5.0
djangocms-apphook-setup==0.4.1
djangocms-attributes-field==1.2.0
djangocms-blog==0.9.11
djangocms-forms==0.2.5
djangocms-lightgallery==0.1.12
djangocms-slick-slider==0.6.0
djangocms-snippet==2.0.0
djangocms-text-ckeditor==3.5.0
djangocms-video==2.0.4
docutils==0.15.2
easy-thumbnails==2.7
elasticsearch==5.5.3
et-xmlfile==1.0.1
gevent==1.2.2
googlemaps==2.5.1
greenlet==0.4.15
gunicorn==19.10.0
h11==0.9.0
hashids==1.2.0
hiredis==1.0.1
html5lib==0.9999999
httptools==0.0.13
hyperlink==19.0.0
idna==2.8
incremental==17.5.0
jdcal==1.4.1
jmespath==0.9.4
jsonfield==2.0.2
kombu==3.0.37
lxml==4.4.2
msgpack==0.6.2
oauthlib==3.1.0
olefile==0.46
openpyxl==2.4.9
passlib==1.7.2
Pillow==4.1.1
psycopg2-binary==2.7.6.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.19
PyHamcrest==2.0.0
PyJWT==1.7.1
pyOpenSSL==19.1.0
python-dateutil==2.8.1
python-wordpress-xmlrpc==2.3
python3-openid==3.1.0
pytz==2017.2
rcssmin==1.0.6
redis==2.10.6
regex==2020.1.8
requests==2.22.0
requests-aws4auth==0.9
requests-oauthlib==1.3.0
rjsmin==1.1.0
s3transfer==0.2.1
sentry-sdk==0.14.1
service-identity==18.1.0
shortuuid==0.5.0
six==1.14.0
stripe==2.42.0
suds-jurko==0.6
tablib==1.0.0
Twisted==19.10.0
txaio==20.1.1
typing==3.7.4.1
typing-extensions==3.7.4.1
unicodecsv==0.14.1
Unidecode==0.4.21
urllib3==1.25.8
URLObject==2.4.3
uvicorn==0.11.2
uvloop==0.14.0
websockets==8.1
xmltodict==0.12.0
YURL==1.0.0
zope.interface==4.7.1
```

**Comment by oesah** [comment]
Ok, I figured it out: `django-htmlmin==0.10.0` is the issue, it breaks the response somehow. Have removed it completely, and now it works. Sorry for the noise!
