### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured: Cannot import ASGI_APPLICATION module 'routing

### ISSUE THREAD

**Issue by subbu52** [django/channels#1429]
I am getting errors while running daphne server. RHEL/httpd server is running wsgi.py with out any issues. 

Here are the configurations of different files: 

1) asgy.py
----------------------------------

```
import os
import sys
import django
from channels.routing import get_default_application

sys.path.append("/var/www/new-personality-server-2.0/personality")
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "personality.settings")
django.setup()
application = get_default_application()
```

2) routing.py
---------------------------------------

```
from channels.auth import AuthMiddlewareStack
from channels.routing import ProtocolTypeRouter, URLRouter
import tools.routing

#application = ProtocolTypeRouter({
    # (http->django views is added by default)
#    'websocket': AuthMiddlewareStack(
#        URLRouter(
#            tools.routing.websocket_urlpatterns
#        )
#    ),
#})
application = ProtocolTypeRouter({})
```

settings.py
----------------------------

```
ASGI_APPLICATION = 'routing.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [(PERSONALITY_HOST, 6379)],
        },
    },
}


INSTALLED_APPS = [
    'channels',
]
```

httpd (django.conf) file
---------------------------------

```
<VirtualHost *:80>
    ServerName xxx.xx.net
    #DocumentRoot /var/www/new-personality-server-2.0
    DocumentRoot /var/www
    Alias /static /var/www/new-personality-server-2.0/personality/static
    <Directory /var/www/new-personality-server-2.0/personality/static>
            Require all granted
    </Directory>

    Alias /media /var/www/new-personality-server-2.0/personality/media
    <Directory /var/www/new-personality-server-2.0/personality/media>
                Require all granted
        </Directory>


    LoadModule wsgi_module /usr/lib64/httpd/modules/mod_wsgi.so
    WSGIDaemonProcess personality python-path=/var/www/new-personality-server-2.0/newpers3.8:/var/www/new-personality-server-2.0/newpers3.8/lib/python3.8/site-packages
    WSGIProcessGroup personality
    WSGIScriptAlias / /var/www/new-personality-server-2.0/personality/personality/wsgi.py
    #WSGIPythonHome /var/www/new-personality-server-2.0/newpersonality
    #WSGIPythonPath /var/www/new-personality-server-2.0/personality

    <Directory /var/www/new-personality-server-2.0/personality/personality>
                <Files wsgi.py>
                        Require all granted
                </Files>
```

finally logs: 
----------------------------

```
# daphne personality.asgi:application
Traceback (most recent call last):
  File "/var/www/new-personality-server-2.0/newpers3.8/lib/python3.8/site-packages/channels/routing.py", line 29, in get_default_application
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'routing'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/new-personality-server-2.0/newpers3.8/bin/daphne", line 10, in <module>
    sys.exit(CommandLineInterface.entrypoint())
  File "/var/www/new-personality-server-2.0/newpers3.8/lib/python3.8/site-packages/daphne/cli.py", line 191, in entrypoint
    cls().run(sys.argv[1:])
  File "/var/www/new-personality-server-2.0/newpers3.8/lib/python3.8/site-packages/daphne/cli.py", line 252, in run
    application = import_by_path(args.application)
  File "/var/www/new-personality-server-2.0/newpers3.8/lib/python3.8/site-packages/daphne/utils.py", line 12, in import_by_path
    target = importlib.import_module(module_path)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./personality/asgi.py", line 14, in <module>
    application = get_default_application()
  File "/var/www/new-personality-server-2.0/newpers3.8/lib/python3.8/site-packages/channels/routing.py", line 31, in get_default_application
    raise ImproperlyConfigured("Cannot import ASGI_APPLICATION module %r" % path)
```

**Comment by carltongibson** [comment]
Sorry, this is almost impossible to debug. 

> ModuleNotFoundError: No module named 'routing'

This is a path issue. Check the working directory of the application, and from a shell there, check you can import `routing` and so on.

**Comment by Edwarzzz** [comment]
Try :
`pip install websocket-client`
It worked for me
