### ISSUE TITLE
runserver does not work

### ISSUE THREAD

**Issue by Abbracx** [django/channels#1487]
python manage.py runserver

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/abbracx/Documents/virtualenv/pycon/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/abbracx/Documents/virtualenv/pycon/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/abbracx/Documents/virtualenv/pycon/lib/python3.7/site-packages/django/core/management/__init__.py", line 244, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/abbracx/Documents/virtualenv/pycon/lib/python3.7/site-packages/django/core/management/__init__.py", line 38, in load_command_class
    return module.Command()
AttributeError: module 'channels.management.commands.runserver' has no attribute 'Command'

**Comment by carltongibson** [comment]
Hi @Abbracx. We’re going to need more info here...

https://github.com/django/channels/blob/fca74cdf78761650842102b02ee27bad1634ea20/channels/management/commands/runserver.py#L20

I use this command in my main project daily. I’m pretty sure it works under normal circumstances. 

Can you help to reproduce?

**Comment by Abbracx** [comment]
i figured it out.. the files within some of my libraries in my virtual environment  in which channels depends on where empty. i guess it was due to incomplete installation.
I created a new virtualenv and  installed all needed libraries. thanks.

**Comment by carltongibson** [comment]
Thanks for the follow up.
