### ISSUE TITLE
cannot import package from relative path

### ISSUE THREAD

**Issue by akkuman** [django/channels#1569]
env:
- Django 3.1.1
- channels 3.0.1

app
![image](https://user-images.githubusercontent.com/7813511/98508050-be1f6000-2299-11eb-86cc-4b3b39df0860.png)

I cannot use the `from . import models` in **`customers.py`**, it can't work properly.

It will raise the error

```
Exception inside application: Model class apps.synergy.models.ChatRecord doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
Traceback (most recent call last):
  File "/home/lab/working/homados-working/HomadosBackend/venv/lib/python3.6/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/home/lab/working/homados-working/HomadosBackend/homados/homados/middleware/wsmw.py", line 28, in __call__
    return await self.app(scope, receive, send)
  File "/home/lab/working/homados-working/HomadosBackend/venv/lib/python3.6/site-packages/channels/routing.py", line 160, in __call__
    send,
  File "/home/lab/working/homados-working/HomadosBackend/venv/lib/python3.6/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/home/lab/working/homados-working/HomadosBackend/venv/lib/python3.6/site-packages/channels/consumer.py", line 59, in __call__
    [receive, self.channel_receive], self.dispatch
  File "/home/lab/working/homados-working/HomadosBackend/venv/lib/python3.6/site-packages/channels/utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "/home/lab/working/homados-working/HomadosBackend/venv/lib/python3.6/site-packages/asgiref/sync.py", line 296, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
    return (yield from fut)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/lab/working/homados-working/HomadosBackend/venv/lib/python3.6/site-packages/channels/db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "/home/lab/working/homados-working/HomadosBackend/venv/lib/python3.6/site-packages/asgiref/sync.py", line 334, in thread_handler
    return func(*args, **kwargs)
  File "/home/lab/working/homados-working/HomadosBackend/venv/lib/python3.6/site-packages/channels/consumer.py", line 125, in dispatch
    handler(message)
  File "/home/lab/working/homados-working/HomadosBackend/venv/lib/python3.6/site-packages/channels/generic/websocket.py", line 60, in websocket_receive
    self.receive(text_data=message["text"])
  File "/home/lab/working/homados-working/HomadosBackend/homados/apps/synergy/consumers.py", line 44, in receive
    self._save_chat_record(message)
  File "/home/lab/working/homados-working/HomadosBackend/homados/apps/synergy/consumers.py", line 60, in _save_chat_record
    from . import serializers
  File "/home/lab/working/homados-working/HomadosBackend/homados/apps/synergy/serializers.py", line 3, in <module>
    from . import models
  File "/home/lab/working/homados-working/HomadosBackend/homados/apps/synergy/models.py", line 5, in <module>
    class ChatRecord(models.Model):
  File "/home/lab/working/homados-working/HomadosBackend/venv/lib/python3.6/site-packages/django/db/models/base.py", line 116, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class apps.synergy.models.ChatRecord doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
```

But `from synegy import models` can work.

**Comment by jonathan-s** [comment]
And does it work if you completely remove channels from the project? If it still doesn't work after you've removed channels, it's not a channels bug.

**Comment by akkuman** [comment]
> And does it work if you completely remove channels from the project? If it still doesn't work after you've removed channels, it's not a channels bug.

it works, When I remove channels, the `customers.py` will not be called, so I add `from . import serizliers` to the `views.py`, it works.

**Comment by carltongibson** [comment]
This is not a Channels issue.
