### ISSUE TITLE
Channels 3+ with Django 2.2 under gunicorn/uvicorn fails when hit with concurrent requests

### ISSUE THREAD

**Issue by AlexHill** [django/channels#1578]
The issue I'm seeing is that with a very barebones Django/Channels/Uvicorn/Gunicorn setup I'm seeing consistent failures when more than one request is made concurrently. Errors included at the bottom.

**Reproduction instructions**

I've made the simplest Django 2.2 LTS project I can at https://github.com/AlexHill/django_channels_test.

Just clone that, then `make env` to create the venv and `make asgi` to start the application server. Then run

```env/bin/python load_test.py 1 10```

to hit it with ten requests serially, which should work fine, and then

```env/bin/python load_test.py 10 10```

to hit it with ten requests in parallel, which should fail.

Downgrading to Channels 2.x makes the problem go away.

**Errors**

```[2020-11-19 06:05:19 +0000] [22144] [ERROR] ASGI callable returned without starting response.```

And sometimes:

```
[2020-11-19 06:05:19 +0000] [22144] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/home/alexh/signiq/uvicorn_test/env/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py", line 391, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/alexh/signiq/uvicorn_test/env/lib/python3.6/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/alexh/signiq/uvicorn_test/env/lib/python3.6/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/home/alexh/signiq/uvicorn_test/env/lib/python3.6/site-packages/channels/http.py", line 200, in __call__
    await self.handle(body_stream)
  File "/home/alexh/signiq/uvicorn_test/env/lib/python3.6/site-packages/asgiref/sync.py", line 304, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
    return (yield from fut)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/alexh/signiq/uvicorn_test/env/lib/python3.6/site-packages/asgiref/sync.py", line 343, in thread_handler
    return func(*args, **kwargs)
  File "/home/alexh/signiq/uvicorn_test/env/lib/python3.6/site-packages/channels/http.py", line 258, in handle
    self.send(response_message)
  File "/home/alexh/signiq/uvicorn_test/env/lib/python3.6/site-packages/asgiref/sync.py", line 147, in __call__
    return call_result.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/alexh/signiq/uvicorn_test/env/lib/python3.6/site-packages/asgiref/sync.py", line 212, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/home/alexh/signiq/uvicorn_test/env/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py", line 535, in send
    raise RuntimeError(msg % message_type)
RuntimeError: Unexpected ASGI message 'http.response.start' sent, after response already completed.
```

**Comment by lowrin** [comment]
we are also facing this issue with the provided versions.
but we are facing it with the django debug server and daphne server.

**Comment by carltongibson** [comment]
Hi @AlexHill — thanks for the report and the sample project!

Looks like an issue in `AsgiHandler`... — I don't have the bandwidth to dig-in this week — have you had any chance to look to a cause?

**Comment by AlexHill** [comment]
Ok, dug a little deeper.

The issue is caused by concurrent mutation of `AsgiHandler`. Where we previously had an AsgiHandler per request, we now have one long-lived AsgiHandler that is called once per request by multiple threads. In its `__call__` method it sets `self.scope` and `self.send` and then refers to those in `handle()` which is a straightforward race condition when called handling concurrent requests.

By passing the `scope` and async-to-sync-wrapped `send` as arguments to `handle()` we avoid the per-request mutation and all appears to be well.

**Comment by alex-pobeditel-2004** [comment]
Looks like I faced the same issue with this setup (Python 3.7):  
```
channels==3.0.2
Django==3.1.4
gunicorn==20.0.4
uvicorn==0.12.3
```
While loading pages, only in ~10% of cases all styles were loaded successfully - part of requests ended with 500 error with errors like this in log:
```
INFO:     127.0.0.1:49418 - "GET /admin/ HTTP/1.1" 302 Found
INFO:     127.0.0.1:49418 - "GET /admin/login/?next=/admin/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:49418 - "GET /static/jet/css/icons/style.css?v=1.0.7 HTTP/1.1" 200 OK
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/channels/http.py", line 200, in __call__
    await self.handle(body_stream)
  File "/usr/local/lib/python3.7/site-packages/asgiref/sync.py", line 304, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 414, in wait_for
    return await fut
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/asgiref/sync.py", line 343, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/channels/http.py", line 258, in handle
    self.send(response_message)
  File "/usr/local/lib/python3.7/site-packages/asgiref/sync.py", line 147, in __call__
    return call_result.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.7/site-packages/asgiref/sync.py", line 212, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 449, in send
    raise RuntimeError(msg % message_type)
RuntimeError: Expected ASGI message 'http.response.start', but got 'http.response.body'.
Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/channels/http.py", line 200, in __call__
    await self.handle(body_stream)
  File "/usr/local/lib/python3.7/site-packages/asgiref/sync.py", line 304, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 414, in wait_for
    return await fut
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/asgiref/sync.py", line 343, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/channels/http.py", line 258, in handle
    self.send(response_message)
  File "/usr/local/lib/python3.7/site-packages/asgiref/sync.py", line 147, in __call__
    return call_result.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.7/site-packages/asgiref/sync.py", line 212, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 449, in send
    raise RuntimeError(msg % message_type)
RuntimeError: Expected ASGI message 'http.response.start', but got 'http.response.body'.
INFO:     127.0.0.1:49422 - "GET /static/jet/css/themes/template/base.css?v=1.0.7 HTTP/1.1" 200 OK
```

Freezing Channels version to 2.4 fixed the issue.
