### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 6379)

### ISSUE THREAD

**Issue by Freduah-Gideon** [django/channels#1585]
Hi I am following a tutorial [here](https://channels.readthedocs.io/en/stable/tutorial/part_2.html#enable-a-channel-layer)

I am using django version 3.1.3 and i'm on a kali linux operating system

I installed channels and everything was working fine when i followed the tutorial but as soon as i configured channel layers everything stopped working
Websocket connection disconnects without even connecting

I am more than willing to provide any other information you will need in order to help me

Below Is My Settings.py
# settings.py`
ASGI_APPLICATION = 'learningDatabase.asgi.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}`
Below Is My Consumers.py
`
from channels.generic.websocket import AsyncWebsocketConsumer
import json

class ChatConsumer(AsyncWebsocketConsumer):
    async def connect(self):
        self.room_name = self.scope['url_route']['kwargs']['room_name']
        self.room_group_name = 'chat_%s' % self.room_name

        await self.channel_layer.group_add(
            self.room_name,
            self.room_group_name
        )
        await self.accept()

    async def disconnect(self, code):
        await self.channel_layer.group_discard(
            self.room_name,
            self.room_group_name
        )
        print(code)

    async def receive(self, text_data):
        data = json.loads(text_data)
        message = data['message']

        await self.channel_layer.send(
            self.room_group_name,
            {
                "type": "message",
                "message": message
            }

        )

    async def message(self, event):
        message = event['message']
        await self.send(type_data=json.dumps({"message": message}))
`
Below Is The Full Traceback Of The Error
`
(env) freduah@freduah:~/VideoCallDesign/learning/learningDatabase$ ./manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
November 26, 2020 - 08:11:15
Django version 3.1.3, using settings 'learningDatabase.settings'
Starting ASGI/Channels version 3.0.2 development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
HTTP GET /chat/newby 200 [0.03, 127.0.0.1:47866]
WebSocket HANDSHAKING /ws/chat/newby/ [127.0.0.1:47868]
Exception inside application: [Errno 111] Connect call failed ('127.0.0.1', 6379)
Traceback (most recent call last):
  File "/home/freduah/VideoCallDesign/learning/env/lib/python3.8/site-packages/channels/staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "/home/freduah/VideoCallDesign/learning/env/lib/python3.8/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/home/freduah/VideoCallDesign/learning/env/lib/python3.8/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/home/freduah/VideoCallDesign/learning/env/lib/python3.8/site-packages/channels/sessions.py", line 254, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/home/freduah/VideoCallDesign/learning/env/lib/python3.8/site-packages/channels/auth.py", line 181, in __call__
    return await super().__call__(scope, receive, send)
  File "/home/freduah/VideoCallDesign/learning/env/lib/python3.8/site-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "/home/freduah/VideoCallDesign/learning/env/lib/python3.8/site-packages/channels/routing.py", line 150, in __call__
    return await application(
  File "/home/freduah/VideoCallDesign/learning/env/lib/python3.8/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/home/freduah/VideoCallDesign/learning/env/lib/python3.8/site-packages/channels/consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "/home/freduah/VideoCallDesign/learning/env/lib/python3.8/site-packages/channels/utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "/home/freduah/VideoCallDesign/learning/env/lib/python3.8/site-packages/channels/consumer.py", line 73, in dispatch
    await handler(message)
  File "/home/freduah/VideoCallDesign/learning/env/lib/python3.8/site-packages/channels/generic/websocket.py", line 175, in websocket_connect
    await self.connect()
  File "/home/freduah/VideoCallDesign/learning/learningDatabase/chat/consumers.py", line 10, in connect
    await self.channel_layer.group_add(
  File "/home/freduah/VideoCallDesign/learning/env/lib/python3.8/site-packages/channels_redis/core.py", line 622, in group_add
    async with self.connection(self.consistent_hash(group)) as connection:
  File "/home/freduah/VideoCallDesign/learning/env/lib/python3.8/site-packages/channels_redis/core.py", line 884, in __aenter__
    self.conn = await self.pool.pop()
  File "/home/freduah/VideoCallDesign/learning/env/lib/python3.8/site-packages/channels_redis/core.py", line 78, in pop
    conn = await aioredis.create_redis(**self.host)
  File "/home/freduah/VideoCallDesign/learning/env/lib/python3.8/site-packages/aioredis/commands/__init__.py", line 168, in create_redis
    conn = await create_connection(address, db=db,
  File "/home/freduah/VideoCallDesign/learning/env/lib/python3.8/site-packages/aioredis/connection.py", line 111, in create_connection
    reader, writer = await asyncio.wait_for(open_connection(
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/home/freduah/VideoCallDesign/learning/env/lib/python3.8/site-packages/aioredis/stream.py", line 23, in open_connection
    transport, _ = await get_event_loop().create_connection(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 494, in sock_connect
    return await fut
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 526, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 6379)
WebSocket DISCONNECT /ws/chat/newby/ [127.0.0.1:47868]

`

**Comment by p8ul** [comment]
@Freduah-Gideon how did you solve the above error? I'm facing the same issue

**Comment by p8ul** [comment]
[HERE](https://stackoverflow.com/a/59976815/9298143)  

Changing 127.0.0.1:6379 to redis:6379. worked for me

settings.py
```python
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('redis', 6379)],
        },
    },

```

**Comment by EhsanAiDev** [comment]
i got this error:
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 6379)
WebSocket DISCONNECT /ws/chat/44 [127.0.0.1:33158]

while creating a realtime webapplication with django by using (channels_redis=3.4.1)
and i fixed by installing redis_server on my linux by running this command:
```bash 
sudo apt-get install redis-server
```
and you should run it by this command:
```bash
redis-server
```

You can check this by running the following command in your terminal:
```bash
redis-server --version

```
