### ISSUE TITLE
Backround task example does not work with django 3.0.8 and channels 3.0.2

### ISSUE THREAD

**Issue by Paulcappaert** [django/channels#1597]
The background task example works with django 2.2 and channels 2.4 but not with django 3.08 and channels 3.0.2. Here is the stack trace I got from the terminal running the worker process. I am on mac os Catalina.

Running worker for channels ['chat-bot']
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/Users/paulcappaert/Documents/python/django/boilerplate/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/paulcappaert/Documents/python/django/boilerplate/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/paulcappaert/Documents/python/django/boilerplate/venv/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/paulcappaert/Documents/python/django/boilerplate/venv/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/Users/paulcappaert/Documents/python/django/boilerplate/venv/lib/python3.8/site-packages/channels/management/commands/runworker.py", line 46, in handle
    worker.run()
  File "/Users/paulcappaert/Documents/python/django/boilerplate/venv/lib/python3.8/site-packages/asgiref/server.py", line 60, in run
    event_loop.run_until_complete(self.handle())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 612, in run_until_complete
    return future.result()
  File "/Users/paulcappaert/Documents/python/django/boilerplate/venv/lib/python3.8/site-packages/channels/worker.py", line 30, in handle
    [listener.result() for listener in listeners]
  File "/Users/paulcappaert/Documents/python/django/boilerplate/venv/lib/python3.8/site-packages/channels/worker.py", line 30, in <listcomp>
    [listener.result() for listener in listeners]
  File "/Users/paulcappaert/Documents/python/django/boilerplate/venv/lib/python3.8/site-packages/channels/worker.py", line 42, in listener
    instance_queue = self.get_or_create_application_instance(channel, scope)
  File "/Users/paulcappaert/Documents/python/django/boilerplate/venv/lib/python3.8/site-packages/asgiref/server.py", line 87, in get_or_create_application_instance
    application_instance = self.application(scope=scope)
TypeError: __call__() missing 2 required positional arguments: 'receive' and 'send'
(venv) ?1 boilerplate % python manage.py runworker chat-bot
Running worker for channels ['chat-bot']
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/Users/paulcappaert/Documents/python/django/boilerplate/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/paulcappaert/Documents/python/django/boilerplate/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/paulcappaert/Documents/python/django/boilerplate/venv/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/paulcappaert/Documents/python/django/boilerplate/venv/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/Users/paulcappaert/Documents/python/django/boilerplate/venv/lib/python3.8/site-packages/channels/management/commands/runworker.py", line 46, in handle
    worker.run()
  File "/Users/paulcappaert/Documents/python/django/boilerplate/venv/lib/python3.8/site-packages/asgiref/server.py", line 60, in run
    event_loop.run_until_complete(self.handle())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 612, in run_until_complete
    return future.result()
  File "/Users/paulcappaert/Documents/python/django/boilerplate/venv/lib/python3.8/site-packages/channels/worker.py", line 30, in handle
    [listener.result() for listener in listeners]
  File "/Users/paulcappaert/Documents/python/django/boilerplate/venv/lib/python3.8/site-packages/channels/worker.py", line 30, in <listcomp>
    [listener.result() for listener in listeners]
  File "/Users/paulcappaert/Documents/python/django/boilerplate/venv/lib/python3.8/site-packages/channels/worker.py", line 42, in listener
    instance_queue = self.get_or_create_application_instance(channel, scope)
  File "/Users/paulcappaert/Documents/python/django/boilerplate/venv/lib/python3.8/site-packages/asgiref/server.py", line 87, in get_or_create_application_instance
    application_instance = self.application(scope=scope)
TypeError: __call__() missing 2 required positional arguments: 'receive' and 'send'

here is the pip freeze for this project. 

aioredis==1.3.1
amqp==2.5.2
asgiref==3.2.3
async-timeout==3.0.1
attrs==19.3.0
autobahn==20.2.1
Automat==20.2.0
autopep8==1.5.4
billiard==3.6.2.0
celery==4.4.0
certifi==2019.11.28
cffi==1.14.0
channels==3.0.2
channels-redis==2.4.1
chardet==3.0.4
constantly==15.1.0
cryptography==2.8
daphne==3.0.1
dj-database-url==0.5.0
Django==3.0.8
django-crispy-forms==1.8.1
django-heroku==0.3.1
djangorestframework==3.12.2
gunicorn==20.0.4
hiredis==1.0.1
hyperlink==19.0.0
idna==2.9
incremental==17.5.0
kombu==4.6.7
msgpack==0.6.2
oauthlib==3.1.0
psycopg2==2.8.4
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.6.0
pycparser==2.19
PyHamcrest==2.0.0
pyOpenSSL==19.1.0
python-chess==0.30.1
pytz==2019.3
requests==2.23.0
requests-oauthlib==1.3.0
service-identity==18.1.0
six==1.14.0
sqlparse==0.3.0
toml==0.10.1
Twisted==19.10.0
txaio==20.1.1
urllib3==1.25.8
vine==1.3.0
whitenoise==5.0.1
zope.interface==4.7.1

**Comment by Paulcappaert** [comment]
disregard, updating channels-redis fixed this
