### ISSUE TITLE
development server 500 error on Django 2.2.17 and channel 3.0.3

### ISSUE THREAD

**Issue by longedok** [django/channels#1603]
```
asgiref                         3.3.1
channels                        3.0.3
daphne                          3.0.1
Django                          2.2.17
```
I'm trying to upgrade an existing Django 2.2.17 project to channels 3 (I need this because there's a fix in Daphne 3.x that solves an issue with growing memory consumption on python3.8). I've read through the change log, and made adjustments to how my consumers are routed.

I have the following setup in my `routing.py` file:

```
ws_urlpatterns = [
    path("ws/endpoint1/", WsConsumer1.as_asgi()),
]

http_urlpatterns = [
    path("myapi/endpoint1/", Consumer1.as_asgi()),
    path("myapi/endpoint2/", Consumer2.as_asgi()),
    url(r"", AsgiHandler),
]

application = ProtocolTypeRouter(
    {"websocket": URLRouter(ws_urlpatterns), "http": URLRouter(http_urlpatterns)}
)
```

In addition to consumers, I have a bunch of regular Django views with routing in my project.

**What you expected to happen vs. what actually happened**

When I'm running the development server, I get the 500 error with the following traceback:

```
[2020-12-30 09:38:39,090] ERROR/daphne.server: Exception inside application: __init__() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "venv/lib/python3.8/site-packages/channels/staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "venv/lib/python3.8/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "venv/lib/python3.8/site-packages/channels/routing.py", line 150, in __call__
    return await application(
  File "venv/lib/python3.8/site-packages/asgiref/compatibility.py", line 33, in new_application
    instance = application(scope)
TypeError: __init__() takes 1 positional argument but 2 were given
```

This looks similar to the issues I was getting when my consumers were defined in the old way, but I'm not seeing what else I'm missing in my migration path.

**How you're running Channels (runserver? daphne/runworker? Nginx/Apache in front?)**

I'm using the runserver command.

**Comment by carltongibson** [comment]
```
    url(r"", AsgiHandler),
```

> Exception inside application: __init__() takes ...

Instantiate this `AsgiHandler`: 

```
    url(r"", AsgiHandler()),
```

That should fix it.

**Comment by PeterPlucinski** [comment]
@longedok @carltongibson 

I believe a better approach is to use `get_asgi_application()` as AsgiHandler (part of channels) is being deprecated in favor asgi included with newer Django versions. 

I.e.

```
from django.core.asgi import get_asgi_application

url(r"", get_asgi_application())),
```

Please see:
https://channels.readthedocs.io/en/stable/releases/3.0.0.html?highlight=as_asgi()#update-to-asgi-3
https://channels.readthedocs.io/en/stable/topics/routing.html?highlight=as_asgi()#urlrouter
