### ISSUE TITLE
Django 4.0: ImportError: cannot import name 'LANGUAGE_SESSION_KEY' from 'django.utils.translation'

### ISSUE THREAD

**Issue by collinanderson** [django/channels#1609]
Thank you for the ongoing work of maintaining Channels! Here's an issue from recent changes to Django master.

- Your OS and runtime environment, and browser if applicable
Django master (4.0). (Ubuntu 20.04, Python 3.8.5)

- How you're running Channels (runserver? daphne/runworker? Nginx/Apache in front?)
runserver

- Console logs and full tracebacks of any errors
```
January 14, 2021 - 15:15:53
Django version 4.0, using settings 'myproject.settings'
Starting ASGI/Channels version 3.0.3 development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "channels/routing.py", line 28, in get_default_application
    module = importlib.import_module(path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "myproject/myproject/asgi.py", line 4, in <module>
    from channels.auth import AuthMiddlewareStack
  File "channels/auth.py", line 15, in <module>
    from django.utils.translation import LANGUAGE_SESSION_KEY
ImportError: cannot import name 'LANGUAGE_SESSION_KEY' from 'django.utils.translation' (django/utils/translation/__init__.py)

```

**Comment by auvipy** [comment]
this library still don't support django 3.2 or master yet

**Comment by collinanderson** [comment]
It worked for me just to put `LANGUAGE_SESSION_KEY = '_language'` at the top of `channels/auth.py` as a workaround. Everything else is working fine for me on django master.

**Comment by carltongibson** [comment]
Super, thanks @collinanderson! I'll cut back here after the alpha and have a look at the proper solution. 
Thanks for the report.

**Comment by biswajit955** [comment]
uninstall channels than install channels , it's work for me
