### ISSUE TITLE
TypeError: async_to_sync can only be applied to async functions.

### ISSUE THREAD

**Issue by aryan340** [django/channels#1668]
I believe this issue is with channels serving static files.
When I loaded django admin, the static files required (css) could not be loaded. The terminal showed the following traceback.
```py
HTTP GET /static/admin/js/change_form.js 500 [1.01, 127.0.0.1:56396]
Exception inside application: async_to_sync can only be applied to async functions.
Traceback (most recent call last):
  File "C:\Users\iyapp\Envs\rebox_django\lib\site-packages\channels\staticfiles.py", line 40, in __call__
    return await self.staticfiles_handler_class()(
  File "C:\Users\iyapp\Envs\rebox_django\lib\site-packages\channels\staticfiles.py", line 56, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\iyapp\Envs\rebox_django\lib\site-packages\channels\http.py", line 198, in __call__
    await self.handle(scope, async_to_sync(send), body_stream)
  File "C:\Users\iyapp\Envs\rebox_django\lib\site-packages\asgiref\sync.py", line 105, in __init__
    raise TypeError("async_to_sync can only be applied to async functions.")
TypeError: async_to_sync can only be applied to async functions.
```
when I removed channels from my project, the css loaded fine.
Is this an issue with channels?

From the traceback, I can understand that the send passed to the `__call__` method is not asynchronous, so we cannot use async_to_sync over it. This is how I serve static files in development.

```py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include

import plixn_django.apps.uploads.views as upload_views

urlpatterns = [
    # admin
    path('admin/', admin.site.urls),
    # core api endpoints
    path('api/', include('plixn_django.apps.users.urls')),
    path('api/', include('plixn_django.apps.uploads.urls')),
    path('api/', include('plixn_django.apps.roles.urls')),
    # oauth2 endpoints with application management
    path('oauth2/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    # protected file-service with permission-checking
    re_path(r'^private/(?P<path>.*)$', upload_views.UploadFileServeView.as_view(), name='view-files'),
    re_path(r'^downloads/(?P<path>.*)$', upload_views.UploadFileDownloadView.as_view(), name='download-files'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
```

**Comment by yedpodtrzitko** [comment]
What's your version of asgiref? This bug was introduced in recently released v3.3.2 (and 3.3.3 attempting to fix it), see https://github.com/django/asgiref/issues/251. asgiref v3.3.4 has fixed this.

**Comment by carltongibson** [comment]
Yep, thanks @yedpodtrzitko! 

@aryan340 Please update asgiref to 3.3.4 and let us know if you still have issues. 
I'll leave this open for a few days for visibility.

**Comment by carltongibson** [comment]
Daphne 3.0.2 is available now with a related fix https://pypi.org/project/daphne/3.0.2/ — That combined with asgiref 3.3.4 should be enough. 🤞

**Comment by pique-b** [comment]
In my instant case (where activating Django Channels was raising _suspicious file operation_ error), only upgrading Daphne to from **3.0.1** to **3.0.2** helped resolving the issue.

Thanks.

**Comment by aryan340** [comment]
I could finally test my project.
yes, upgrading the package fixed the issue.

thanks!
