### ISSUE TITLE
Requesting static files on Django 3.2 raises TypeError

### ISSUE THREAD

**Issue by bastbnl** [django/channels#1669]
TL:DR; Seems like requesting static files raises an error when using channels on Django 3.2. Requesting static files works when runserver is started using `python manage.py runserver 0:8000 --nostatic`

I've just updated to `Django==3.2` from  `Django==3.1.8`  and I'm running into an issue using `channels==3.0.3` and `asgiref==3.3.2`:

```
Traceback (most recent call last):
  File "/var/www/brwnppr/dev/env/lib/python3.7/site-packages/channels/staticfiles.py", line 41, in __call__
    dict(scope, static_base_url=self.base_url), receive, send
  File "/var/www/brwnppr/dev/env/lib/python3.7/site-packages/channels/staticfiles.py", line 56, in __call__
    return await super().__call__(scope, receive, send)
  File "/var/www/brwnppr/dev/env/lib/python3.7/site-packages/channels/http.py", line 198, in __call__
    await self.handle(scope, async_to_sync(send), body_stream)
  File "/var/www/brwnppr/dev/env/lib/python3.7/site-packages/asgiref/sync.py", line 105, in __init__
    raise TypeError("async_to_sync can only be applied to async functions.")
TypeError: async_to_sync can only be applied to async functions.
HTTP GET /static/img/favicon/apple-touch-icon.png 500 [0.68, 127.0.0.1:41848]
Exception inside application: async_to_sync can only be applied to async functions.
```

My OS:
- Debian x64 10 with python 3.7.10

pip freeze: 
```
...
Django==3.2
channels==3.0.3
channels-redis==3.2.0
asgiref==3.3.2
aioredis==1.3.1
channels-redis==3.2.0
...
```

I'm seeing this error on the development server. The static url is:
```
if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()
```

**Comment by yedpodtrzitko** [comment]
This seems to be a duplicate of #1668. tl;dr - upgrade asgiref to 3.3.4

**Comment by bastbnl** [comment]
It appears so. I updated asgiref and it's working fine. Thanks, @yedpodtrzitko
