### ISSUE TITLE
Questions about super().__init__(*args, **kwargs) in websocket.py

### ISSUE THREAD

**Issue by xuehua312741499** [django/channels#1679]
In websocket.py, the '__init__' method  in AsyncWebsocketConsumer and WebsocketConsumer class use 'super().__init__(*args, **kwargs)' ,

I want to know  'super().__init__(*args, **kwargs)'  from which class  in channels-3.0.3 version.

In channels-2.4.0 ,this method comes from consumer.py ,But in channels-3.0.3, consumer.py had delete  '__init__(self, *args, **kwargs)'.

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.groups is None:
            self.groups = []

When I update channels in 3.0.3, There is one problem:

Exception inside application: object.__init__() takes exactly one argument (the instance to initialize)
Traceback (most recent call last):
  File "D:\Program\Python3.7\lib\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "D:\Program\Python3.7\lib\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "D:\Program\Python3.7\lib\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "D:\Program\Python3.7\lib\site-packages\channels\sessions.py", line 254, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "D:\Program\Python3.7\lib\site-packages\channels\auth.py", line 181, in __call__
    return await super().__call__(scope, receive, send)
  File "D:\Program\Python3.7\lib\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "D:\Program\Python3.7\lib\site-packages\channels\routing.py", line 160, in __call__
    send,
  File "D:\Program\Python3.7\lib\site-packages\asgiref\compatibility.py", line 33, in new_application
    instance = application(scope)
  File "D:\Program\Python3.7\lib\site-packages\channels\generic\websocket.py", line 23, in __init__
    super().__init__(*args, **kwargs)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)

**Comment by yedpodtrzitko** [comment]
There are some breaking changes between Channels 2 and 3. It's difficult to tell what could be your problem, but my guess is you're not calling `.as_asgi()` on your consumer in `routing.py`. It should look like this:

```
websocket_urlpatterns = [
    re_path(
        r"ws/(?P<room_id>\w+)/$",
        consumers.ChatConsumer.as_asgi(), # <- notice the `.as_asgi()` here
    )
]
```

**Comment by xuehua312741499** [comment]
> There are some breaking changes between ASGI v2 and v3. It's difficult to tell what could be your problem, but my guess is you're not calling `.as_asgi()` on your consumer in `routing.py`. It should look like this:
> 
> ```
> websocket_urlpatterns = [
>     re_path(
>         r"ws/(?P<room_id>\w+)/$",
>         consumers.ChatConsumer.as_asgi(), # <- notice the `.as_asgi()` here
>     )
> ]
> ```
> 
> Also this seems like a duplicate of #1552
