### ISSUE TITLE
aioredis.errors.ReplyError: ERR unknown command 'BZPOPMIN'

### ISSUE THREAD

**Issue by aryan340** [django/channels#1690]
**Steps to reproduce**
create a simple consumer which accepts ws connections,
and adds the client to their own private channel.
```py
class GatewayEventsConsumer(AsyncWebsocketConsumer):
    async def connect(self):
        # add the user to their private group.
        # Because we add the user before they
        # identify themselves via the gateway we
        # cannot get the user's id. Hence we use
        # the channel name as a substitute for
        # the private group's unique identifier.
        self.private_channel_name = self.channel_name.replace('!', '')

        await self.channel_layer.group_add(
            group=self.private_channel_name,
            channel=self.channel_name
        )
        await self.accept()
```
I highly doubt that this error is caused because of the newly made
variable `private_channel_name`.
#1688

**traceback**
```py
WebSocket HANDSHAKING /gateway/ [127.0.0.1:60290]
WebSocket CONNECT /gateway/ [127.0.0.1:60290]
Exception inside application: ERR unknown command 'BZPOPMIN'
Traceback (most recent call last):
  File "C:\Users\iyapp\Envs\rebox_django\lib\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\iyapp\Envs\rebox_django\lib\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\iyapp\Envs\rebox_django\lib\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\iyapp\Envs\rebox_django\lib\site-packages\channels\sessions.py", line 254, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\iyapp\Envs\rebox_django\lib\site-packages\channels\auth.py", line 181, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\iyapp\Envs\rebox_django\lib\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\iyapp\Envs\rebox_django\lib\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\iyapp\Envs\rebox_django\lib\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\iyapp\Envs\rebox_django\lib\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\iyapp\Envs\rebox_django\lib\site-packages\channels\utils.py", line 58, in await_many_dispatch
    await task
  File "C:\Users\iyapp\Envs\rebox_django\lib\site-packages\channels\utils.py", line 50, in await_many_dispatch
    result = task.result()
  File "C:\Users\iyapp\Envs\rebox_django\lib\site-packages\channels_redis\core.py", line 468, in receive
    message_channel, message = await self.receive_single(
  File "C:\Users\iyapp\Envs\rebox_django\lib\site-packages\channels_redis\core.py", line 523, in receive_single
    content = await self._brpop_with_clean(
  File "C:\Users\iyapp\Envs\rebox_django\lib\site-packages\channels_redis\core.py", line 361, in _brpop_with_clean
    result = await connection.bzpopmin(channel, timeout=timeout)
aioredis.errors.ReplyError: ERR unknown command 'BZPOPMIN'
WebSocket DISCONNECT /gateway/ [127.0.0.1:60290]

```

ran command
```
python manage.py runserver
```
OS: Windows 10

**Comment by aryan340** [comment]
>I highly doubt that this error is caused because of the newly made
variable `private_channel_name`.

I tested with another random string with only alphabets, and the error is still being raised.

**Comment by carltongibson** [comment]
Please check your redis version. 

BZPOPMIN  is available from v5. https://redis.io/commands/bzpopmin

**Comment by aryan340** [comment]
sorry my bad. 😥
thanks for your help!

just noticed other issues in django/channels_redis !
