### ISSUE TITLE
RuntimeError: no running event loop

### ISSUE THREAD

**Issue by sharp** [django/channels#1739]
versions:

```
channels = "==3.0.4"
channels-redis = "==3.3.0"
Django = "==3.1.12"
```

settings.py:
```

ASGI_APPLICATION = "events.asgi.application"
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}
```

asgi.py

```
application = ProtocolTypeRouter({
    "channel": ChannelNameRouter({
        "order_sync": consumers.OrderSyncConsumer.as_asgi(),
    }),
})
```
cousumers.py

```
class OrderSyncConsumer(WebsocketConsumer):

    def connect(self):
        # Called on connection.
        # To accept the connection call:
        print(self.channel_name)
        self.accept()


    def receive(self, text_data=None):
        # Called with either text_data or bytes_data for each frame
        # You can call:
        self.send(text_data={'text_data': 'order_sync'})

    def chat_message(self, event):
        # Handles the "chat.message" event when it's sent to us.
        self.send(text_data=event["text"])


    def disconnect(self, close_code):
        # Called when the socket closes
        self.close()
```
When I run `python manage runwork order_sync`
errors:

```
Running worker for channels ['order_sync']
Traceback (most recent call last):
  File "./manage.py", line 21, in <module>
    main()
  File "./manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/Users/sharp/.local/share/virtualenvs/VirtualConnectServer-BZMFlKeY/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/sharp/.local/share/virtualenvs/VirtualConnectServer-BZMFlKeY/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/sharp/.local/share/virtualenvs/VirtualConnectServer-BZMFlKeY/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/sharp/.local/share/virtualenvs/VirtualConnectServer-BZMFlKeY/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/Users/sharp/.local/share/virtualenvs/VirtualConnectServer-BZMFlKeY/lib/python3.8/site-packages/channels/management/commands/runworker.py", line 46, in handle
    worker.run()
  File "/Users/sharp/.local/share/virtualenvs/VirtualConnectServer-BZMFlKeY/lib/python3.8/site-packages/asgiref/server.py", line 59, in run
    event_loop = get_running_loop()
RuntimeError: no running event loop
```

**Comment by lsaavedr** [comment]
duplicate #1713

**Comment by luke026** [comment]
Hi can unhelp me find bixing manny pacaioa

**Comment by lsaavedr** [comment]
> Hi can unhelp me find bixing manny pacaioa

`$ pip install asgiref==3.3.4` ?
