### ISSUE TITLE
How to combine the Django WebSockets "websocket_urlpatterns" (path) of multiple apps in the Project URLRouter?

### ISSUE THREAD

**Issue by MuhammadBilal1** [django/channels#1757]
I have multiple apps and they all are using the "WebSockets (routing.py)", and I have **routing.py** in my project and apps.

I can only add the `websocket_urlpatterns` of single app in my `URLRouter` of my project, if I try to add the other "websocket_urlpatterns" in the URLRouter, it didn't worked and I get the error.

**Project routing.py**

```
from channels.auth import AuthMiddlewareStack
from channels.routing import ProtocolTypeRouter, URLRouter
import django_chatter.routing
import app1.routing 
import os

from time import sleep
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "myProject.settings")

application = ProtocolTypeRouter({

  'websocket': AuthMiddlewareStack(
    URLRouter(
    app1.routing.websocket_urlpatterns # send request to chatter's urls
    )
  )
})
```

**App1 routing.py**
```
from django.urls import path
from django_chatter import consumers
import app1.consumers

websocket_urlpatterns = [
    path('ws/route1/' , app1.consumers.Consumer1.as_asgi()),
    path('ws/route2/' , app2.consumers.Consumer2.as_asgi()),
    path('ws/route3/' , app3.consumers.Consumer3.as_asgi()),
]
```

**App2 routing.py**

```
from django.urls import path
from . import consumers

websocket_urlpatterns = [
    path('ws/chatter/chatrooms/<str:room_uuid>/', consumers.ChatConsumer.as_asgi()),
    path('ws/chatter/users/<str:username>/', consumers.AlertConsumer.as_asgi())
]
```

**Comment by carltongibson** [comment]
Can you add the error traceback?

**Comment by MuhammadBilal1** [comment]
> Can you add the error traceback?

Sure.

**When I tried # 1:**
```
from channels.auth import AuthMiddlewareStack
from channels.routing import ProtocolTypeRouter, URLRouter
import App2.routing
import App1.routing 
import os

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "MyProject.settings")

application = ProtocolTypeRouter({
  'websocket': AuthMiddlewareStack(
    URLRouter([
    App1.routing.websocket_urlpatterns,
    App2.routing.websocket_urlpatterns,
    ])
  )
})
```

**Result:**
```
System check identified no issues (0 silenced).
September 26, 2021 - 15:10:15
Django version 3.1.7, using settings 'MyProject.settings'
Starting ASGI/Channels version 3.0.3 development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu20/.local/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/ubuntu20/.local/lib/python3.8/site-packages/channels/management/commands/runserver.py", line 107, in inner_run
    application=self.get_application(options),
  File "/home/ubuntu20/.local/lib/python3.8/site-packages/channels/management/commands/runserver.py", line 132, in get_application
    return StaticFilesWrapper(get_default_application())
  File "/home/ubuntu20/.local/lib/python3.8/site-packages/channels/routing.py", line 28, in get_default_application
    module = importlib.import_module(path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu20/solution/MyProject/routing.py", line 13, in <module>
    URLRouter([
  File "/home/ubuntu20/.local/lib/python3.8/site-packages/channels/routing.py", line 125, in __init__
    if getattr(route.callback, "_path_routing", False) is True:
AttributeError: 'list' object has no attribute 'callback'
```

**When I tried # 2:**
```
from channels.auth import AuthMiddlewareStack
from channels.routing import ProtocolTypeRouter, URLRouter
import App2.routing
import App1.routing 
import os

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "MyProject.settings")

application = ProtocolTypeRouter({
  'websocket': AuthMiddlewareStack(
    URLRouter[
    App1.routing.websocket_urlpatterns,
    App2.routing.websocket_urlpatterns,
    ]
  )
})
```

**Result:**
```
System check identified no issues (0 silenced).
September 26, 2021 - 15:19:29
Django version 3.1.7, using settings 'MyProject.settings'
Starting ASGI/Channels version 3.0.3 development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu20/.local/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/ubuntu20/.local/lib/python3.8/site-packages/channels/management/commands/runserver.py", line 107, in inner_run
    application=self.get_application(options),
  File "/home/ubuntu20/.local/lib/python3.8/site-packages/channels/management/commands/runserver.py", line 132, in get_application
    return StaticFilesWrapper(get_default_application())
  File "/home/ubuntu20/.local/lib/python3.8/site-packages/channels/routing.py", line 28, in get_default_application
    module = importlib.import_module(path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu20/solution/MyProject/routing.py", line 13, in <module>
    URLRouter[
TypeError: 'type' object is not subscriptable
```

**When I tried # 3:**
```
from channels.auth import AuthMiddlewareStack
from channels.routing import ProtocolTypeRouter, URLRouter
import App2.routing
import App1.routing 
import os

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "MyProject.settings")

application = ProtocolTypeRouter({
  'websocket': AuthMiddlewareStack(
    URLRouter = [
    App1.routing.websocket_urlpatterns,
    App2.routing.websocket_urlpatterns,
    ]
  )
})
```

**Result:**
```
System check identified no issues (0 silenced).
September 26, 2021 - 15:20:59
Django version 3.1.7, using settings 'MyProject.settings'
Starting ASGI/Channels version 3.0.3 development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu20/.local/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/ubuntu20/.local/lib/python3.8/site-packages/channels/management/commands/runserver.py", line 107, in inner_run
    application=self.get_application(options),
  File "/home/ubuntu20/.local/lib/python3.8/site-packages/channels/management/commands/runserver.py", line 132, in get_application
    return StaticFilesWrapper(get_default_application())
  File "/home/ubuntu20/.local/lib/python3.8/site-packages/channels/routing.py", line 28, in get_default_application
    module = importlib.import_module(path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu20/solution/MyProject/routing.py", line 12, in <module>
    'websocket': AuthMiddlewareStack(
TypeError: AuthMiddlewareStack() got an unexpected keyword argument 'URLRouter'
```

**Comment by carltongibson** [comment]
So is this a duplicate of #1428 ?

**Comment by MuhammadBilal1** [comment]
> So is this a duplicate of #1428 ?

Seems so. But I couldn't understand how to fix the issue. Can you please help me by giving an example or explanation?

**Comment by carltongibson** [comment]
It should work with `re_path` URLs inside the nested middleware.

**Comment by MuhammadBilal1** [comment]
> It should work with `re_path` URLs inside the nested middleware.

This is what I understood, but this isn't working because the re_path requires view name also which I don't have in this case as I am sending the collection of URL Routes from my app.

**In my Project `routing.py`**
```
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "MyProject.settings")

application = ProtocolTypeRouter({
  'websocket': AuthMiddlewareStack(
    URLRouter([
    re_path(App1.routing.websocket_urlpatterns),
    re_path(App2.routing.websocket_urlpatterns)
    ])
  )
})
```

Even if I keep my Project routing.py without re_path and change the Apps routing.py to re_path, that didn't worked as well.

**Comment by MuhammadBilal1** [comment]
@jules-ch 
Here is the output when I tried your suggestion. It didn't worked.

![image](https://user-images.githubusercontent.com/7131058/137432892-ec67517f-5105-46bb-81cc-7acce268c173.png)

**Comment by MuhammadBilal1** [comment]
> It should work with :
> 
> ```python
> from channels.auth import AuthMiddlewareStack
> from channels.routing import ProtocolTypeRouter, URLRouter
> import App2.routing
> import App1.routing 
> import os
> 
> os.environ.setdefault("DJANGO_SETTINGS_MODULE", "MyProject.settings")
> 
> application = ProtocolTypeRouter({
>   'websocket': AuthMiddlewareStack(
>     URLRouter([
>     *App1.routing.websocket_urlpatterns,
>     *App2.routing.websocket_urlpatterns,
>     ])
>   )
> })
> ```
> 
> It essentially joins those 2 lists to create the URLRouter.

Thank you. It worked. 
**Astrisk** before the app name is the key here.

I tried this solution without Astrisk before the app name and it didn't worked. But now I put the asktrisk and it's working.
