### ISSUE TITLE
Freezes in database_sync_to_async when upgrading to asgiref>=3.5.1 with thread_sensitive=True

### ISSUE THREAD

**Issue by moritz89** [django/channels#1852]
A regression in our unit tests occurred when upgrading to `asgiref==3.5.2`. In version 3.5.1 this error also occurs, but not in 3.5.0 and earlier. The error happens in test classes with

```
class TestChannels(TransactionTestCase):
    async def test_connection(self):
        some_model = await database_sync_to_async(SomeModel.objects.create)(
            name="my_name"
        )
```

To resolve the issue, we had to pass `thread_sensitive=False` after which the tests passed again. The error was that the unit tests froze and had to be aborted with a SIGINT.

Env Details:

- Ubuntu 22.04
- Python 3.8.13
- Pipenv 2022.4.21

Relevant console log:
```
Creating test database for alias 'default'...
System check identified no issues (0 silenced).

<Freezes here>

Traceback (most recent call last):
  File "/home/moritz/.virtualenvs/***/lib/python3.8/site-packages/asgiref/sync.py", line 196, in __call__
    current_executor.run_until_future(loop_future)
  File "/home/moritz/.virtualenvs/***/lib/python3.8/site-packages/asgiref/current_thread_executor.py", line 59, in run_until_future
    work_item = self._work_queue.get()
  File "/usr/local/lib/python3.8/queue.py", line 170, in get
    self.not_empty.wait()
  File "/usr/local/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
  File "/usr/local/lib/python3.8/unittest/signals.py", line 36, in __call__
    self.default_handler(signum, frame)
  File "***", line 10, in ***
    sys.exit(0)
SystemExit: 0
```

Pip freeze:

```
apturl==0.5.2
astroid==2.11.3
bcrypt==3.2.0
beautifulsoup4==4.10.0
black==22.3.0
blinker==1.4
Brlapi==0.8.3
cachetools==5.0.0
certifi==2020.6.20
chardet==4.0.0
chrome-gnome-shell==0.0.0
click==8.0.3
colorama==0.4.4
command-not-found==0.3
cryptography==3.4.8
cupshelpers==1.0
dbus-python==1.2.18
defer==1.0.6
dill==0.3.4
distlib==0.3.4
distro==1.7.0
distro-info===1.1build1
duplicity==0.8.21
fasteners==0.14.1
filelock==3.6.0
future==0.18.2
google-api-python-client==1.7.11
google-auth==1.5.1
google-auth-httplib2==0.1.0
greenlet==1.1.2
html5lib==1.1
httplib2==0.20.2
idna==3.3
importlib-metadata==4.6.4
isort==5.10.1
jeepney==0.7.1
keyring==23.5.0
language-selector==0.1
launchpadlib==1.10.16
lazr.restfulclient==0.14.4
lazr.uri==1.0.6
lazy-object-proxy==1.7.1
lockfile==0.12.2
louis==3.20.0
lxml==4.8.0
macaroonbakery==1.3.1
Mako==1.1.3
MarkupSafe==2.0.1
mccabe==0.7.0
meld==3.20.4
monotonic==1.6
more-itertools==8.10.0
mypy-extensions==0.4.3
netifaces==0.11.0
numpy==1.21.5
oauth2client==4.1.3
oauthlib==3.2.0
olefile==0.46
paramiko==2.9.3
pathspec==0.9.0
pexpect==4.8.0
Pillow==9.0.1
pipenv==2022.4.21
platformdirs==2.5.2
protobuf==3.12.4
ptyprocess==0.7.0
pyasn1==0.4.8
pyasn1-modules==0.2.1
pycairo==1.20.1
pycups==2.0.1
PyDrive==1.3.1
PyGObject==3.42.0
PyJWT==2.3.0
pylint==2.13.7
pymacaroons==0.13.0
PyNaCl==1.5.0
pyOpenSSL==21.0.0
pyparsing==2.4.7
pyRFC3339==1.1
python-apt==2.3.0+ubuntu2
python-dateutil==2.8.1
python-debian===0.1.43ubuntu1
pytz==2022.1
pyxdg==0.27
PyYAML==5.4.1
reportlab==3.6.8
requests==2.25.1
rsa==4.8
scour==0.38.2
screen-resolution-extra==0.0.0
SecretStorage==3.3.1
six==1.16.0
soupsieve==2.3.1
SQLAlchemy==1.4.31
systemd-python==234
tomli==2.0.1
ubuntu-advantage-tools==27.8
ubuntu-drivers-common==0.0.0
ufw==0.36.1
unattended-upgrades==0.1
uritemplate==3.0.1
urllib3==1.26.5
usb-creator==0.3.7
virtualenv==20.14.1
virtualenv-clone==0.5.7
wadllib==1.3.6
webencodings==0.5.1
wrapt==1.14.0
xdg==5
xkit==0.0.0
zipp==1.0.0
```

**Comment by carltongibson** [comment]
There's not enough to go on here. If you can produce a minimal test case there might be something we can do either here or on asgiref, but it needs a reproduce, or a deeper analysis, at least.

**Comment by rmorshea** [comment]
@carltongibson, I think we might be experiencing [something similar](https://github.com/idom-team/django-idom/discussions/132). We're still looking into it, but I suspect this has to do with the fact that, by default, `sync_to_async` uses a [thread pool executor with one worker](https://github.com/django/asgiref/blob/03571587bf0f61ddff77f1f6fe3593439cb92f48/asgiref/sync.py#L346) as per [this logic](https://github.com/django/asgiref/blob/03571587bf0f61ddff77f1f6fe3593439cb92f48/asgiref/sync.py#L393-L420). This could explain why @moritz89 reported that setting `thread_sensitive=False` fixed the deadlock since doing so would cause `asgiref` to use the default [`ThreadPoolExecutor`](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor) which has an unlimited number of workers.

As such this isn't strictly an issue with Django Channels, but it does suggest that Django Channels might want to supply a way to configure these defaults via a settings like `DJANGO_CHANNELS_DEFAULT_THREAD_POOL_SIZE`.
