### ISSUE TITLE
Add an error message when running in django >= 4.0

### ISSUE THREAD

**Issue by edgarceron** [django/channels#1863]
Using django 4.0 o greater with channels returns the following error:
`django.core.exceptions.ImproperlyConfigured: Cannot import ASGI_APPLICATION module '<projectname>.routing'`

Is clear that the documentation says that chanels must run over django 3.0 I give that. But just for debugging usability I would preffer to have a clear message, instead of a confusing bug around files and directories. Thanks for your time.

**Comment by carltongibson** [comment]
Hi. This isn't anything Django 4 specific. There's something else going on, an import loop maybe?

**Comment by edgarceron** [comment]
`Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/home/edgar/iaback/env/lib/python3.8/site-packages/channels/routing.py", line 28, in get_default_application
    module = importlib.import_module(path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/edgar/iaback/magicia/routing.py", line 3, in <module>
    from channels.auth import AuthMiddlewareStack
  File "/home/edgar/iaback/env/lib/python3.8/site-packages/channels/auth.py", line 15, in <module>
    from django.utils.translation import LANGUAGE_SESSION_KEY
ImportError: cannot import name 'LANGUAGE_SESSION_KEY' from 'django.utils.translation' (/home/edgar/iaback/env/lib/python3.8/site-packages/django/utils/translation/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/edgar/iaback/env/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/edgar/iaback/env/lib/python3.8/site-packages/channels/management/commands/runserver.py", line 107, in inner_run
    application=self.get_application(options),
  File "/home/edgar/iaback/env/lib/python3.8/site-packages/channels/management/commands/runserver.py", line 132, in get_application
    return StaticFilesWrapper(get_default_application())
  File "/home/edgar/iaback/env/lib/python3.8/site-packages/channels/routing.py", line 30, in get_default_application
    raise ImproperlyConfigured("Cannot import ASGI_APPLICATION module %r" % path)
django.core.exceptions.ImproperlyConfigured: Cannot import ASGI_APPLICATION module 'magicia.routing'`

You're wrong and right. LANGUAGE_SESSION_KEY was removed from django in version 4

> Hi. This isn't anything Django 4 specific. There's something else going on, an import loop maybe?

**Comment by edgarceron** [comment]
The problem was between the chair and the keyboard. I never updated channels. Sorry for that.
