### ISSUE TITLE
django SynchronousOnlyOperation exception and DJANGO_ALLOW_ASYNC_UNSAFE

### ISSUE THREAD

**Issue by goodvanity** [django/channels#1916]
This simple code raise SynchronousOnlyOperation error in Django 4.1.1, `sync_to_async` and `database_sync_to_async` didn't help

```
from django.contrib.auth.models import Group

class Consumer(AsyncWebsocketConsumer):
    async def receive(self, text_data=None, bytes_data=None):
        groups = await sync_to_async(Group.objects.all)()
        list(groups)
    
    ...
```
Run through `runserver`. Without call `groups = await sync_to_async(Group.objects.all)()` and `list(groups)` everything works. This code only works with Django env param `os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"`. But is this the right way? If yes, then maybe it is worth specifying it in the documentation of channels?

**Traceback:**
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/channels/staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/ecom/api_async/middleware.py", line 109, in __call__
    return await self.inner(scope, receive, send)
  File "/ecom/api_async/middleware.py", line 122, in __call__
    return await self.inner(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/ecom/api_async/middleware.py", line 95, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/usr/local/lib/python3.10/dist-packages/channels/auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "/ecom/api_async/middleware.py", line 145, in __call__
    return await self.inner(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/channels/routing.py", line 150, in __call__
    return await application(
  File "/usr/local/lib/python3.10/dist-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/channels/consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "/usr/local/lib/python3.10/dist-packages/channels/utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "/usr/local/lib/python3.10/dist-packages/channels/consumer.py", line 73, in dispatch
    await handler(message)
  File "/usr/local/lib/python3.10/dist-packages/channels/generic/websocket.py", line 194, in websocket_receive
    await self.receive(text_data=message["text"])
  File "/ecom/api_async/consumers.py", line 52, in receive
    list(groups)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 376, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 1866, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 1393, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 24, in inner
    raise SynchronousOnlyOperation(message)
django.core.exceptions.SynchronousOnlyOperation: You cannot call this from an async context - use a thread or sync_to_async.
```

**pip freeze:**
```
absl-py==1.2.0
aiohttp==3.8.1
aioredis==1.3.1
aiosignal==1.2.0
amqp==5.1.1
APScheduler==3.6.3
asgiref==3.5.2
async-timeout==4.0.2
attrs==22.1.0
autobahn==22.7.1
Automat==20.2.0
billiard==3.6.4.0
bleach==5.0.1
blinker==1.4
cachetools==4.2.2
celery==5.2.7
certifi==2022.6.15.2
cffi==1.15.1
channels==3.0.5
channels-redis==3.4.1
charset-normalizer==2.1.1
click==8.1.3
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.2.0
constantly==15.1.0
cryptography==38.0.1
daphne==3.0.2
dbus-python==1.2.18
Deprecated==1.2.13
distro==1.7.0
distro-info===1.1build1
Django==4.1.1
django-appconf==1.0.5
django-debug-toolbar==3.5.0
django-js-asset==2.0.0
django-modeltranslation==0.18.2
django-recaptcha==3.0.0
django-simple-history==3.1.1
djangorestframework==3.13.1
frozenlist==1.3.1
geoip2==4.6.0
gyp==0.1
hiredis==2.0.0
httplib2==0.20.2
hyperlink==21.0.0
idna==3.4
importlib-metadata==4.6.4
incremental==21.3.0
jeepney==0.7.1
keyring==23.5.0
kombu==5.2.4
launchpadlib==1.10.16
lazr.restfulclient==0.14.4
lazr.uri==1.0.6
maxminddb==2.2.0
more-itertools==8.10.0
msgpack==1.0.4
multidict==6.0.2
numpy==1.23.3
oauthlib==3.2.0
ortools==9.3.10497
packaging==21.3
peewee==3.15.0
Pillow==9.2.0
prompt-toolkit==3.0.31
protobuf==4.21.6
psycopg2==2.8.5
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
PyGObject==3.42.0
PyJWT==2.4.0
pyOpenSSL==22.0.0
pyparsing==2.4.7
python-apt==2.3.0+ubuntu2
python-telegram-bot==13.13
pytz==2022.2.1
pytz-deprecation-shim==0.1.0.post0
redis==4.3.4
requests==2.28.1
SecretStorage==3.3.1
service-identity==21.1.0
six==1.16.0
sqlparse==0.4.2
tornado==6.2
transliterate==1.10.2
Twisted==22.8.0
txaio==22.2.1
typing_extensions==4.3.0
tzdata==2022.2
tzlocal==4.2
ua-parser==0.16.1
unattended-upgrades==0.1
urllib3==1.26.12
user-agents==2.2.0
uWSGI==2.0.20
vine==5.0.0
wadllib==1.3.6
wcwidth==0.2.5
webencodings==0.5.1
wrapt==1.14.1
yarl==1.8.1
zipp==1.0.0
zope.interface==5.4.0

```

**Comment by carltongibson** [comment]
`groups` is a QuerySet. You need to force evaluation inside the `sync_to_async()` call — create a helper function to return the list of group model instances. 

See: https://docs.djangoproject.com/en/4.1/ref/models/querysets/#when-querysets-are-evaluated
