### ISSUE TITLE
TypeError: __call__() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by odarotto** [django/channels#1919]
Hi, I'm having this problem when trying to integrate channels into Django API using rest_framework:

```
$ python .\manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 16, 2022 - 16:21:28
Django version 4.1.1, using settings 'tav_back.settings'
Starting ASGI/Channels version 3.0.5 development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Exception inside application: __call__() takes 3 positional arguments but 4 were given # Happens when accessing localhost
Traceback (most recent call last):
  File "F:\Documents\Github\tav-frontend\tav_back\envs\env_win\lib\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
TypeError: __call__() takes 3 positional arguments but 4 were given
HTTP GET / 500 [0.46, 127.0.0.1:56477]
Exception inside application: __call__() takes 3 positional arguments but 4 were given
Traceback (most recent call last):
  File "F:\Documents\Github\tav-frontend\tav_back\envs\env_win\lib\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
TypeError: __call__() takes 3 positional arguments but 4 were given
HTTP GET /favicon.ico 500 [0.78, 127.0.0.1:56477]
```

I'm following the Channels tutorial, here are my files:

- asgi.py

```python
import os

from channels.routing import ProtocolTypeRouter
from django.core.asgi import get_asgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "tav_back.settings")

# django_asgi_app = get_asgi_application()

application = ProtocolTypeRouter({
    "http": get_asgi_application(),
})
```

- tav_back/urls.py

```python
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("api/", include('api.urls')),
    path("admin/", admin.site.urls),
]
```
- settings.py

```
# Channels
ASGI_APPLICATION = "tav_back.wsgi.application"
```

- Versions:

```
Windows 10

env:

channels==3.0.5
Django==4.1.1
djangorestframework==3.13.1
```

**Comment by chris-wahl** [comment]
In your `settings.py`,
```
# Channels
ASGI_APPLICATION = "tav_back.wsgi.application"
```

I think this setting should be to your **.asgi** file (which you also have above) rather than **w**sgi?
