### ISSUE TITLE
Daphne still needed to use channels.testing

### ISSUE THREAD

**Issue by bertonha** [django/channels#1942]
on `channels.testing` module it import all Consumers and TestCases, but the `ChannelsLiveServerTestCase` imports daphne, if you decided to not have daphne testing is completely not usable.

https://github.com/django/channels/blob/main/channels/testing/__init__.py#L4

https://github.com/django/channels/blob/main/channels/testing/live.py#L3

```
tests/websocket/utils.py:2: in <module>
    from channels.testing import WebsocketCommunicator
../../../.local/share/virtualenvs/test-channels/lib/python3.10/site-packages/channels/testing/__init__.py:4: in <module>
    from .live import ChannelsLiveServerTestCase  # noqa
../../../.local/share/virtualenvs/test-channels/lib/python3.10/site-packages/channels/testing/live.py:3: in <module>
    from daphne.testing import DaphneProcess
E   ModuleNotFoundError: No module named 'daphne'
```

**Comment by carltongibson** [comment]
Sure, this was noted in the release notes. The test case depends on the Daphne process to run the web server.

**Comment by bertonha** [comment]
But if we comment the import of `ChannelsLiveServerTestCase` from __init__.py and use the WebsocketCommunicator. It works perfectly.

Maybe we could fail the use of `ChannelsLiveServerTestCase` if Daphne is not installed

**Comment by carltongibson** [comment]
For the moment I'd suggest importing the communicator from the submodule so you're not blocked.

**Comment by bertonha** [comment]
Hello @carltongibson I really dunno if is possible to import the `WebsocketCommunicator` without the execution of `channels/testing/__init__.py` which it needs `daphne` installed.

both way of importing resulting in the exception:
```
```

**Comment by carltongibson** [comment]
Yep, you're right: 

```
>>> from channels.testing.http import HttpCommunicator
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/carlton/Envs/tmp-5e851afa3eddf65/lib/python3.10/site-packages/channels/testing/__init__.py", line 4, in <module>
    from .live import ChannelsLiveServerTestCase  # noqa
  File "/Users/carlton/Envs/tmp-5e851afa3eddf65/lib/python3.10/site-packages/channels/testing/live.py", line 3, in <module>
    from daphne.testing import DaphneProcess
ModuleNotFoundError: No module named 'daphne'
```

We'll have to make that conditional along the lines of your PR. 👍

**Comment by carltongibson** [comment]
In the meantime you'll need to install Daphne for testing.

**Comment by philippks** [comment]
As a workaround, one can mock the `channels.testing.live` module, when it is not used in the tests:
```python
import sys
from unittest.mock import MagicMock

sys.modules["channels.testing.live"] = MagicMock()
```

For me this works for using the `WebsocketCommunicator`.

**Comment by carltongibson** [comment]
Yes, it was this concern that led to making Daphne optional in the first place. 👍

**Comment by johnthagen** [comment]
I was able to confirm that @philippks's [workaround](https://github.com/django/channels/issues/1942#issuecomment-1420831305) works.

For `pytest` users, adding the following code to `conftest.py` will fix the issue for `pytest` invocations.

```py
import sys
from unittest.mock import MagicMock

sys.modules["channels.testing.live"] = MagicMock()
```
