### ISSUE TITLE
django-cors-headers not compatible

### ISSUE THREAD

**Issue by platzhersh** [django/channels#372]
Channels is not compatible with django-cors-headers

    Traceback (most recent call last):
      File "D:\Users\chregi\Documents\GitHub\musicmashup-jukebox-backend\env_win\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
        fn(*args, **kwargs)
      File "D:\Users\chregi\Documents\GitHub\musicmashup-jukebox-backend\env_win\lib\site-packages\channels\management\commands\runserver.py", line 40, in inner_run
        http_consumer=self.get_consumer(*args, **options),
      File "D:\Users\chregi\Documents\GitHub\musicmashup-jukebox-backend\env_win\lib\site-packages\channels\management\commands\runserver.py", line 135, in get_consumer
        return StaticFilesConsumer()
      File "D:\Users\chregi\Documents\GitHub\musicmashup-jukebox-backend\env_win\lib\site-packages\channels\handler.py", line 331, in __init__
        self.handler = self.handler_class()
      File "D:\Users\chregi\Documents\GitHub\musicmashup-jukebox-backend\env_win\lib\site-packages\channels\staticfiles.py", line 18, in __init__
        super(StaticFilesHandler, self).__init__()
      File "D:\Users\chregi\Documents\GitHub\musicmashup-jukebox-backend\env_win\lib\site-packages\channels\handler.py", line 178, in __init__
        self.load_middleware()
      File "D:\Users\chregi\Documents\GitHub\musicmashup-jukebox-backend\env_win\lib\site-packages\django\core\handlers\base.py", line 82, in load_middleware
        mw_instance = middleware(handler)
    TypeError: object() takes no parameters

**Comment by platzhersh** [comment]
sorry, seems like this is an issue with django-cors-headers being not compatible with Django 1.10

**Comment by ikcam** [comment]
Switch to django-cors-middelware created from django-cors and fix version issue.

**Comment by platzhersh** [comment]
@ikcam I did that, however it does not seem as if the app is able to set the responding headers on daphne. My problem is, that my Ionic client is not able to connect to the websocket (browser works fine), I always get a handshake error (WebSocket closed before handshake established)

So my idea was that it could maybe be a CORS problem. How can I set header options on daphne?

**Comment by andrewgodwin** [comment]
Daphne just sets the headers Django sends, it's not got any special override or anything.

**Comment by danadn** [comment]
@platzhersh how did you finally solve that problem?

I've exposed Date header and when I active "channels" django stops sending back that very same header.

OPTIONS do shows it, but the following method doesn't...
