### ISSUE TITLE
Different version of ConnectionError: Error 111

### ISSUE THREAD

**Issue by bhaugen** [django/channels#397]
This is somewhat different from https://github.com/django/channels/issues/250 in that it is about a channels-example: https://github.com/andrewgodwin/channels-examples/tree/master/databinding and has some different error messages. 

I am not sure where you want issues about examples, but none of the examples repos had issues, so I'm reporting it here. If this is the wrong place, feel free to close and tell me where to report or at least ask for help. Thanks a lot. Just getting my feet wet in channels.

Here's the short version of the error message. Full trace below:
```
/.virtualenvs/databinding/local/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
```

In https://github.com/django/channels/issues/250 the solution was
```
redis-server
```
But trying that gives me this other error:
```
The program 'redis-server' is currently not installed.  You can install it by typing:
sudo apt-get install redis-server
```

- Your OS and runtime environment: Ubuntu 12.04
- The versions of Channels, Daphne, Django, Twisted, and your ASGI backend (asgi_ipc or asgi_redis normally): whatever is specified in https://github.com/andrewgodwin/channels-examples/tree/master/databinding

-Full stack trace of original error:
```
2016-10-12 17:47:20,323 - INFO - worker - Listening on channels binding.intval, http.request, websocket.connect, websocket.disconnect, websocket.receive
2016-10-12 17:47:20,330 - INFO - worker - Listening on channels binding.intval, http.request, websocket.connect, websocket.disconnect, websocket.receive
2016-10-12 17:47:20,331 - INFO - worker - Listening on channels binding.intval, http.request, websocket.connect, websocket.disconnect, websocket.receive
2016-10-12 17:47:20,333 - INFO - worker - Listening on channels binding.intval, http.request, websocket.connect, websocket.disconnect, websocket.receive
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/home/bob/.virtualenvs/databinding/local/lib/python2.7/site-packages/channels/management/commands/runserver.py", line 153, in run
    worker.run()
  File "/home/bob/.virtualenvs/databinding/local/lib/python2.7/site-packages/channels/worker.py", line 79, in run
    channel, content = self.channel_layer.receive_many(channels, block=True)
  File "/home/bob/.virtualenvs/databinding/local/lib/python2.7/site-packages/asgi_redis/core.py", line 128, in receive_many
    result = connection.blpop(list_names, timeout=self.blpop_timeout)
  File "/home/bob/.virtualenvs/databinding/local/lib/python2.7/site-packages/redis/client.py", line 1163, in blpop
    return self.execute_command('BLPOP', *keys)
  File "/home/bob/.virtualenvs/databinding/local/lib/python2.7/site-packages/redis/client.py", line 578, in execute_command
    connection.send_command(*args)
  File "/home/bob/.virtualenvs/databinding/local/lib/python2.7/site-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/bob/.virtualenvs/databinding/local/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/home/bob/.virtualenvs/databinding/local/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 111 connecting to localhost:6379. Connection refused.

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/home/bob/.virtualenvs/databinding/local/lib/python2.7/site-packages/channels/management/commands/runserver.py", line 153, in run
    worker.run()
  File "/home/bob/.virtualenvs/databinding/local/lib/python2.7/site-packages/channels/worker.py", line 79, in run
    channel, content = self.channel_layer.receive_many(channels, block=True)
  File "/home/bob/.virtualenvs/databinding/local/lib/python2.7/site-packages/asgi_redis/core.py", line 128, in receive_many
    result = connection.blpop(list_names, timeout=self.blpop_timeout)
  File "/home/bob/.virtualenvs/databinding/local/lib/python2.7/site-packages/redis/client.py", line 1163, in blpop
    return self.execute_command('BLPOP', *keys)
  File "/home/bob/.virtualenvs/databinding/local/lib/python2.7/site-packages/redis/client.py", line 578, in execute_command
    connection.send_command(*args)
  File "/home/bob/.virtualenvs/databinding/local/lib/python2.7/site-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/bob/.virtualenvs/databinding/local/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/home/bob/.virtualenvs/databinding/local/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 111 connecting to localhost:6379. Connection refused.

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/home/bob/.virtualenvs/databinding/local/lib/python2.7/site-packages/channels/management/commands/runserver.py", line 153, in run
    worker.run()
  File "/home/bob/.virtualenvs/databinding/local/lib/python2.7/site-packages/channels/worker.py", line 79, in run
    channel, content = self.channel_layer.receive_many(channels, block=True)
  File "/home/bob/.virtualenvs/databinding/local/lib/python2.7/site-packages/asgi_redis/core.py", line 128, in receive_many
    result = connection.blpop(list_names, timeout=self.blpop_timeout)
  File "/home/bob/.virtualenvs/databinding/local/lib/python2.7/site-packages/redis/client.py", line 1163, in blpop
    return self.execute_command('BLPOP', *keys)
  File "/home/bob/.virtualenvs/databinding/local/lib/python2.7/site-packages/redis/client.py", line 578, in execute_command
    connection.send_command(*args)
  File "/home/bob/.virtualenvs/databinding/local/lib/python2.7/site-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/bob/.virtualenvs/databinding/local/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/home/bob/.virtualenvs/databinding/local/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 111 connecting to localhost:6379. Connection refused.

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/home/bob/.virtualenvs/databinding/local/lib/python2.7/site-packages/channels/management/commands/runserver.py", line 153, in run
    worker.run()
  File "/home/bob/.virtualenvs/databinding/local/lib/python2.7/site-packages/channels/worker.py", line 79, in run
    channel, content = self.channel_layer.receive_many(channels, block=True)
  File "/home/bob/.virtualenvs/databinding/local/lib/python2.7/site-packages/asgi_redis/core.py", line 128, in receive_many
    result = connection.blpop(list_names, timeout=self.blpop_timeout)
  File "/home/bob/.virtualenvs/databinding/local/lib/python2.7/site-packages/redis/client.py", line 1163, in blpop
    return self.execute_command('BLPOP', *keys)
  File "/home/bob/.virtualenvs/databinding/local/lib/python2.7/site-packages/redis/client.py", line 578, in execute_command
    connection.send_command(*args)
  File "/home/bob/.virtualenvs/databinding/local/lib/python2.7/site-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/bob/.virtualenvs/databinding/local/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/home/bob/.virtualenvs/databinding/local/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
```

**Comment by andrewgodwin** [comment]
It's still the same error - you don't have Redis running, but in your case, you need to install it first (`sudo apt-get install redis-server`, as that error says).

**Comment by bhaugen** [comment]
Sorry for the misunderstanding. Apparently Redis must be installed globally, not in the virtualenv, and is not installed in the requirements for the databinding example.

**Comment by andrewgodwin** [comment]
Redis is not a Python package, it's a database, so we can't put it in requirements unfortunately. Don't get confused between the Redis server and the `redis` python binding either, they're different.

**Comment by brubbel** [comment]
I run into a similar issue. Following the tutorial:
$ daphne my_project.asgi:channel_layer -p 6379
and
$ python manage.py runserver
everything starts (no errors, worker listening on channels etc...), but browsing to 127.0.0.1:8000 is waiting forever. (any other port gives connection refused, so the the interface server is listening?)

However, when redis-server instead of daphne is running on 6379, browsing to http://127.0.0.1:8000 works, including websockets.
What could be going wrong in the first case (because daphne is recommended in the deploying tutorial)?

**Comment by brubbel** [comment]
Nevermind ;) 
It is not very clear from the manual that redis is the database server, daphne is the HTTP/WebSocket server and they must be running both when starting python manage.py runworker...
