### ISSUE TITLE
upgrading asgi_redis error

### ISSUE THREAD

**Issue by leonardoo** [django/channels#430]
If you're submitting a bug report, please include:

when upgrade asgi_redis from 0.14.1 to 1.0.0 and running with runserver get 

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/leonardoo/.pyenv/versions/3.5.1/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/leonardoo/.pyenv/versions/buses/lib/python3.5/site-packages/channels/management/commands/runserver.py", line 155, in run
    worker.run()
  File "/home/leonardoo/.pyenv/versions/buses/lib/python3.5/site-packages/channels/worker.py", line 88, in run
    channel, content = self.channel_layer.receive_many(channels, block=True)
  File "/home/leonardoo/.pyenv/versions/buses/lib/python3.5/site-packages/asgiref/base_layer.py", line 35, in receive_many
    raise NotImplementedError()
NotImplementedError

but when i return to 0.14.1, is running without error

the versions i use:

channels (0.17.3)
Django (1.9.11)
daphne (0.15.0)
Twisted (16.5.0)

**Comment by andrewgodwin** [comment]
Please upgrade your version of `asgiref` to the newest one and this should be fixed.
