### ISSUE TITLE
Error processing message with consumer channels.staticfiles.StaticFilesConsumer

### ISSUE THREAD

**Issue by CptLemming** [django/channels#449]
Since updating to the latest version of `channels`, I am getting an error for all pages served by Django.

> 2016-12-08 09:44:32,397 - ERROR - worker - Error processing message with consumer channels.staticfiles.StaticFilesConsumer:
Traceback (most recent call last):
  File "/Users/ash/Documents/workspace/channels/channels/worker.py", line 119, in run
    consumer(message, **kwargs)
  File "/Users/ash/Documents/workspace/channels/channels/handler.py", line 338, in __call__
    for reply_message in self.handler(message):
  File "/Users/ash/Documents/workspace/channels/channels/handler.py", line 186, in __call__
    set_script_prefix(message.get('root_path', ''))
  File "/Users/ash/.virtualenvs/django-channels-demo/lib/python3.5/site-packages/django/urls/base.py", line 106, in set_script_prefix
    if not prefix.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'

The issue seems to be caused by the recent addition of `root_path` in the `runserver` command, as commenting out this line fixes the problem:
```
# https://github.com/django/channels/blob/master/channels/management/commands/runserver.py#L87
Server(
    ...
    root_path=getattr(settings, 'FORCE_SCRIPT_NAME', ''),
).run()
```

```
channels==0.17.3
daphne==0.15.0
Django==1.10.4
Twisted==16.5.0
```

**Comment by andrewgodwin** [comment]
That commit should fix it - let me know if it doesn't.
