### ISSUE TITLE
Dahpne Supervisorctl Django 404

### ISSUE THREAD

**Issue by muslu** [django/channels#463]
Hi all;

if i run worker and daphne with command everything is ok but when i use supervisor django show 404.

if i restart pc and supervisor doesnt run correctly.

my supervisor files:

[program:djangodaphne]
command=sudo daphne --root-path=/home/muslu/django/realtimedjango -b 0.0.0.0 -p 80 realtimedjango.asgi:channel_layer -v2
directory=/home/muslu/django/realtimedjango/
autostart=true
autorestart=true
stderr_logfile=/home/muslu/django/realtimedjango/logs/djangodaphne.err.log

[program:djangoworker]
command=sudo python3.5 /home/muslu/django/realtimedjango/manage.py runworker -v2
autostart=true
autorestart=true
stderr_logfile=/home/muslu/django/realtimedjango/logs/djangoworker.err.log

my daphne log:
2017-01-07 23:58:11,370 DEBUG    HTTP b'GET' request for http.response!xwbhqjlpvtMb
2017-01-07 23:58:11,419 DEBUG    HTTP 301 response started for http.response!xwbhqjlpvtMb
2017-01-07 23:58:11,419 DEBUG    HTTP close for http.response!xwbhqjlpvtMb
2017-01-07 23:58:11,420 DEBUG    HTTP response complete for http.response!xwbhqjlpvtMb
2017-01-07 23:58:11,428 DEBUG    HTTP b'GET' request for http.response!LBoecGAFLGMM
2017-01-07 23:58:11,471 DEBUG    HTTP 404 response started for http.response!LBoecGAFLGMM
2017-01-07 23:58:11,471 DEBUG    HTTP close for http.response!LBoecGAFLGMM
2017-01-07 23:58:11,472 DEBUG    HTTP response complete for http.response!LBoecGAFLGMM
2017-01-07 23:58:12,814 DEBUG    HTTP b'GET' request for http.response!QuNuESAvTcmB
2017-01-07 23:58:12,843 DEBUG    HTTP 404 response started for http.response!QuNuESAvTcmB
2017-01-07 23:58:12,843 DEBUG    HTTP close for http.response!QuNuESAvTcmB
2017-01-07 23:58:12,844 DEBUG    HTTP response complete for http.response!QuNuESAvTcmB

worker_log:
2017-01-07 23:57:16,729 - DEBUG - worker - Got message on http.request (reply http.response!dMqmtXPhmjVG)
2017-01-07 23:57:16,730 - DEBUG - runworker - http.request
2017-01-07 23:57:16,730 - DEBUG - worker - Dispatching message on http.request to channels.staticfiles.StaticFilesConsumer
Not Found: /
2017-01-07 23:58:11,381 - DEBUG - worker - Got message on http.request (reply http.response!xwbhqjlpvtMb)
2017-01-07 23:58:11,381 - DEBUG - runworker - http.request
2017-01-07 23:58:11,381 - DEBUG - worker - Dispatching message on http.request to channels.staticfiles.StaticFilesConsumer
2017-01-07 23:58:11,436 - DEBUG - worker - Got message on http.request (reply http.response!LBoecGAFLGMM)
2017-01-07 23:58:11,437 - DEBUG - runworker - http.request
2017-01-07 23:58:11,437 - DEBUG - worker - Dispatching message on http.request to channels.staticfiles.StaticFilesConsumer
Not Found: /asdas/
2017-01-07 23:58:12,827 - DEBUG - worker - Got message on http.request (reply http.response!QuNuESAvTcmB)
2017-01-07 23:58:12,827 - DEBUG - runworker - http.request
2017-01-07 23:58:12,827 - DEBUG - worker - Dispatching message on http.request to channels.staticfiles.StaticFilesConsumer
Not Found: /asdas/

**Comment by andrewgodwin** [comment]
This isn't a Channels problem directly, so I can't really help too much; you might have some luck looking at solutions to previous issues:

https://github.com/django/channels/issues/302
https://github.com/django/channels/issues/408

**Comment by muslu** [comment]
Thank you Andrew. Nice to meet you. 
i read them and i found one problem about path.

When django is running, not found http.request.path.

sudo nano +56 /usr/local/lib/python3.5/dist-packages/channels/handler.py
decode isnt work.

i saw it when i downgraded daphne. i cant use supervisor with python3. i create sh and added cron. its started but waitng long time and give 503.

where can i find log files?

**Comment by andrewgodwin** [comment]
I don't understand what you mean about decode not working; do you have an error from the console? There are no log files by default, everything is printed to stdout.

**Comment by muslu** [comment]
Yes i have some log out.

Not Found: /
2017-01-08 00:36:31,873 - WARNING - base - Not Found: /
2017-01-08 00:36:51,661 - INFO - worker - Shutdown signal received while busy, waiting for loop termination
2017-01-08 00:36:53,619 - INFO - runworker - Running worker against channel layer default (asgi_ipc.IPCChannelLayer)
2017-01-08 00:36:55,336 - DEBUG - worker - Worker got message on http.request: repl http.response!mqnDRKZkZXKY
2017-01-08 00:36:55,337 - DEBUG - runworker - http.request
2017-01-08 00:36:55,338 - ERROR - worker - Error processing message with consumer channels.handler.ViewConsumer:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/channels/worker.py", line 78, in run
    consumer(message, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/channels/handler.py", line 330, in __call__
    for reply_message in self.handler(message):
  File "/usr/local/lib/python3.5/dist-packages/channels/handler.py", line 185, in __call__
    request = self.request_class(message)
  File "/usr/local/lib/python3.5/dist-packages/channels/handler.py", line 56, in __init__
    "SCRIPT_NAME": self.script_name.decode("ascii"),
AttributeError: 'str' object has no attribute 'decode'
2017-01-08 00:37:14,776 - INFO - worker - Shutdown signal received while busy, waiting for loop termination
2017-01-08 00:37:16,721 - INFO - runworker - Running worker against channel layer default (asgi_ipc.IPCChannelLayer)
2017-01-08 00:37:18,632 - DEBUG - worker - Worker got message on http.request: repl http.response!nmZvCRnhGSuW
2017-01-08 00:37:18,633 - DEBUG - runworker - http.request
Not Found: /

and


2017-01-08 00:40:41,407 INFO     Starting server at 0.0.0.0:80, channel layer realtimedjango.asgi:channel_layer
2017-01-08 00:40:41,409 INFO     Using busy-loop synchronous mode on channel layer
2017-01-08 00:40:43,040 DEBUG    HTTP b'GET' request for http.response!nvFJdhjRxdIy
2017-01-08 00:40:43,073 DEBUG    HTTP 404 response started for http.response!nvFJdhjRxdIy
2017-01-08 00:40:43,073 DEBUG    HTTP close for http.response!nvFJdhjRxdIy
2017-01-08 00:40:43,074 DEBUG    HTTP response complete for http.response!nvFJdhjRxdIy
2017-01-08 00:40:43,700 DEBUG    HTTP b'GET' request for http.response!WhaUoCLJAino
2017-01-08 00:40:43,731 DEBUG    HTTP 404 response started for http.response!WhaUoCLJAino
2017-01-08 00:40:43,731 DEBUG    HTTP close for http.response!WhaUoCLJAino
2017-01-08 00:40:43,732 DEBUG    HTTP response complete for http.response!WhaUoCLJAino
2017-01-08 00:45:38,462 INFO     Starting server at 0.0.0.0:80, channel layer realtimedjango.asgi:channel_layer
2017-01-08 00:45:38,464 INFO     Using busy-loop synchronous mode on channel layer

**Comment by muslu** [comment]
my sh file:
cd /home/muslu/django/realtimedjango/
daphne -b 0.0.0.0 -p 80 --root-path=/home/muslu/django/realtimedjango/ realtimedjango.asgi:channel_layer -v2 &
python3.5 /home/muslu/django/realtimedjango/manage.py runworker -v2



it give me this error.
http://i64.tinypic.com/mcfdzo.jpg

2017-01-08 01:53:58,859 - ERROR - worker - Error processing message with consumer channels.handler.ViewConsumer:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/channels/worker.py", line 78, in run
    consumer(message, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/channels/handler.py", line 330, in __call__
    for reply_message in self.handler(message):
  File "/usr/local/lib/python3.5/dist-packages/channels/handler.py", line 185, in __call__
    request = self.request_class(message)
  File "/usr/local/lib/python3.5/dist-packages/channels/handler.py", line 44, in __init__
    self.path = self.message['path'].decode("ascii")
AttributeError: 'str' object has no attribute 'decode'

**Comment by muslu** [comment]
if you want to test my project

http://djangoturkiye.com/static/realtimedjango_ok.tar.gz

if i use two terminal for worker and daphne its working

**Comment by Skorpyon** [comment]
version of Django?

**Comment by muslu** [comment]
1.10.4

**Comment by muslu** [comment]
i updated my channellayer with redis, I tried with many django versions 1.9.13, 1.8.15, 1.8.17 etc...
django is 1.10.4 currently now and its started but still giving some "page not found 404" error.

it is working with terminal worker and daphne without problem.

settings.py
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "asgi_redis.RedisChannelLayer",
        "ROUTING": "realtimedjango.routing.routing",
        "CONFIG": {
            "hosts": [("localhost", 6379)],
        },
    },
}

django:
Page not found (404)
Request Method:	GET
Request URL:	http://127.0.0.1/
Raised by:	otomatik_guncelle.views.chat
{'path': ''}


terminal:
2017-01-08 15:39:56,661 INFO     Starting server at 0.0.0.0:80, channel layer realtimedjango.asgi:channel_layer
2017-01-08 15:39:56,663 INFO     Using busy-loop synchronous mode on channel layer
2017-01-08 15:39:56,735 - INFO - runworker - Using single-threaded worker.
2017-01-08 15:39:56,735 - INFO - runworker - Running worker against channel layer default (asgi_redis.core.RedisChannelLayer)
2017-01-08 15:39:56,735 - INFO - worker - Listening on channels chat.command, chat.connect, chat.disconnect, chat.message, http.request, websocket.connect, websocket.disconnect, websocket.receive
2017-01-08 15:39:58,651 DEBUG    HTTP b'GET' request for http.response!cBIAgKJYARXY
2017-01-08 15:39:58,653 - DEBUG - worker - Got message on http.request (reply http.response!cBIAgKJYARXY)
2017-01-08 15:39:58,654 - DEBUG - runworker - http.request
2017-01-08 15:39:58,654 - DEBUG - worker - Dispatching message on http.request to channels.staticfiles.StaticFilesConsumer
Not Found: /
2017-01-08 15:39:58,676 DEBUG    HTTP 404 response started for http.response!cBIAgKJYARXY
2017-01-08 15:39:58,677 DEBUG    HTTP close for http.response!cBIAgKJYARXY
2017-01-08 15:39:58,678 DEBUG    HTTP response complete for http.response!cBIAgKJYARXY
127.0.0.1:52716 - - [08/Jan/2017:15:39:58] "GET /" 404 1696
2017-01-08 15:39:59,794 DEBUG    HTTP b'GET' request for http.response!ZHNHnVgFYQEz
2017-01-08 15:39:59,795 - DEBUG - worker - Got message on http.request (reply http.response!ZHNHnVgFYQEz)
2017-01-08 15:39:59,795 - DEBUG - runworker - http.request
2017-01-08 15:39:59,796 - DEBUG - worker - Dispatching message on http.request to channels.staticfiles.StaticFilesConsumer
Not Found: /
2017-01-08 15:39:59,836 DEBUG    HTTP 404 response started for http.response!ZHNHnVgFYQEz
2017-01-08 15:39:59,837 DEBUG    HTTP close for http.response!ZHNHnVgFYQEz
2017-01-08 15:39:59,837 DEBUG    HTTP response complete for http.response!ZHNHnVgFYQEz
127.0.0.1:52716 - - [08/Jan/2017:15:39:59] "GET /" 404 1696

**Comment by globophobe** [comment]
Try `asgi:channel_layer` instead of `realtimedjango.asgi:channel_layer`.

**Comment by muslu** [comment]
i dont think so. daphne `--root-path` is not working. 
sh file:
```
#!/usr/bin/env bash
cd /home/muslu/django/realtimedjango/
sudo daphne -b 127.0.0.1 -p 80 realtimedjango.asgi:channel_layer -v2 &
```
I added crontab and its working now. ws doesnt take message now but no problem.

Thanks for your helps. I hope this issue will help to others.

**Comment by muslu** [comment]
Good morning.
Still not working. 
I restarted pc and try connecting againg, waiting (2mn.) and 503.
No logs.
Please double check and answer me. 
which is stabil Python, Django version? and Channels, Daphne, Asgi and what we need.
