### ISSUE TITLE
Version modification : DeprecationWarning:

### ISSUE THREAD

**Issue by yaslim** [django/channels#495]
Hello,

**Before** I had this configuration :  Django 1.10.2, Python 3.5, mod_wsgi 4.5.6

**Today** I modify my configuration to : Django 1.10.5, Python 2.7, mod_wsgi 4.5.9
I have already re-install (with pip2.7) asgi_redis and channels.

The problem is that with this configuration, when I run `python2.7 manage.py runserver` I have this alert : 

`...
2017-01-22 13:31:58,470 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive

Unhandled exception in thread started by <function wrapper at 0x2224570>
Traceback (most recent call last):
  File ".../lib/python2.7/Django-1.10.5-py2.7.egg/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File ".../channels/management/commands/runserver.py", line 82, in inner_run
    http_timeout=60,  # Shorter timeout than normal as it's dev
  File ".../lib/python2.7/daphne/server.py", line 41, in __init__
    ''' % self.__class__.__name__)
DeprecationWarning: 
                The host/port/unix_socket/file_descriptor keyword arguments to Server are deprecated.`

**How can I resolve this problem ?** 

_Thank you..._

**Comment by andrewgodwin** [comment]
I suspect you also upgraded to Channels 1.0 - if you read the release notes, you will see you need to also upgrade Daphne: https://channels.readthedocs.io/en/stable/releases/1.0.0.html

**Comment by yaslim** [comment]
I am sorry but I didn't upgraded Channels, I have just upgraded Daphne (Now I have the 1.0.1)... :/
