### ISSUE TITLE
Cannot install last version by pip

### ISSUE THREAD

**Issue by jakubjosef** [django/channels#533]
Hi,
last commit breaks installation by pip, for call
`pip install-e git+https://github.com/andrewgodwin/channels.git4#egg=channels`

I can see:
Exception:
Traceback (most recent call last):
  File "/srv/xxxxx/local/lib/python2.7/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/srv/xxxxx/local/lib/python2.7/site-packages/pip/commands/install.py", line 299, in run
    requirement_set.prepare_files(finder)
  File "/srv/xxxxx/local/lib/python2.7/site-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/srv/xxxxx/local/lib/python2.7/site-packages/pip/req/req_set.py", line 647, in _prepare_file
    set(req_to_install.extras) - set(dist.extras)
  File "/srv/xxxxx/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2810, in extras
    return [dep for dep in self._dep_map if dep]
  File "/srv/xxxxxx/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2624, in _dep_map
    dm.setdefault(extra,[]).extend(parse_requirements(reqs))
  File "/srv/xxxxxx/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2980, in parse_requirements
    "version spec")
  File "/srv/xxxxxx/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2945, in scan_list
    raise RequirementParseError(msg, line, "at", line[p:])
RequirementParseError: Expected version spec in mock ; python_version < "3.0" at  ; python_version < "3.0"

OS: Ubuntu 16.04

Older commit works well.

**Comment by proofit404** [comment]
This problem happens because of old pip. Please update your environment.

@andrewgodwon Do you consider moving test requirements out of setup.py? This will help to separate tox environment dependencies as well. For example I see no point install twisted into isort environment, or coverage into flake8. And vice versa.

**Comment by andrewgodwin** [comment]
@proofit404 Why would we move the test requirements out of setup.py? The only other place to put them would be a separate requirements file and I don't think that has any advantages; they're not installed by default at the moment anyway.

As for the original poster: Yes, your pip is too old, you need to `pip install -U pip` first.
