### ISSUE TITLE
StaticLiveServerChannelTestCase

### ISSUE THREAD

**Issue by Akay7** [django/channels#616]
- Detailed description of the overall behaviour
django channels have basic functionality for UnitTests
I'm try write UnitTest based on StaticLiveServerTestCase, after I'm finished I found about ws not work there. Then I'm look at tests included inside in channels and find just ChannelTestCaseMixin. I'm write test:
`
class StaticLiveServerChannelTestCase(ChannelTestCaseMixin, StaticLiveServerTestCase): pass
`
and ws not work.
- Reasoning why it should be in Channels rather than a third-party app
Tests is good, StaticLiveServerTestCase is useful if you write functional tests with Selenium or other staff and that is bad if that type of tests not supports websockets.
- Examples of usage, if possible (it's easier to discuss concrete code examples)
I'm writing simple ToDo list based on django with channels and angular 4. Here is test which not work https://github.com/Akay7/ToDoList/blob/master/backend/functional_tests/tests.py#L37

**Comment by proofit404** [comment]
It's already in master. Use `ChannelLiveServerTestCase`. It supports websockets and serves static by default.

**Comment by Akay7** [comment]
@proofit404 thank you for answer. Yes, I'm install from master and found that module.
But I get next error: 
> channels.asgi.InvalidChannelLayerError: No TEST_CONFIG specified for default
And, I'm found that http://channels.readthedocs.io/en/latest/testing.html?highlight=test_config#live-server-test-case .

Did that mean about ChannelLiveServerTestCase not support  `asgiref.inmemory.ChannelLayer` and I'm must use redis?(I'm also try start with empty test config `"TEST_CONFIG": {},` but it's not work at all, test not load any static)

**Comment by proofit404** [comment]
Yes. To run integration tests you need real channel layer with valid test config. Selects Latest docs label to see complete instructions.

**Comment by Akay7** [comment]
@proofit404 Thanks for fast answers. I'm have read docs for "latest" version, and I'm change to redis backend. Here steps what I'm do and what I get:
1. Start two instances of redis, update settings for use redis instead inmemory backend:

```
"default": {
        "BACKEND": "asgi_redis.RedisChannelLayer",
        "ROUTING": "todo_list.routing.channel_routing",
        "CONFIG": {
            "hosts": [("localhost", 6379)],
        },
        "TEST_CONFIG": {
            "hosts": [("localhost", 6400)],
        },
}
```
2. Get get error 400 inside browser. I'm get that error because behavior of `ChannelLiveServerTestCase` not like standard django LiveServer and after add decorator `@override_settings(ALLOWED_HOSTS = ['localhost',])` to `TestCase` I'm not get that error again. **But that is not behavior of Django live server test cases, and I though that decorator is not necessary and I don't need put 'localhost' in ALLOWED_HOSTS**
3. I'm start test case again and get  `django.db.utils.InterfaceError: connection already closed` error. With next traceback

>   File "django/test/testcases.py", line 216, in __call__
    self._post_teardown()
  File "channels/test/liveserver.py", line 224, in _post_teardown
    super(ChannelLiveServerTestCase, self)._post_teardown()
  File "django/test/testcases.py", line 925, in _post_teardown
    self._fixture_teardown()
  File "django/test/testcases.py", line 960, in _fixture_teardown
    inhibit_post_migrate=inhibit_post_migrate)
  File "django/core/management/__init__.py", line 130, in call_command
    return command.execute(*args, **defaults)
  File "django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "django/core/management/commands/flush.py", line 54, in handle
    allow_cascade=allow_cascade)
  File "django/core/management/sql.py", line 15, in sql_flush
    tables = connection.introspection.django_table_names(only_existing=True, include_views=False)
  File "django/db/backends/base/introspection.py", line 86, in django_table_names
    existing_tables = self.table_names(include_views=include_views)
  File "django/db/backends/base/introspection.py", line 53, in table_names
    with self.connection.cursor() as cursor:
  File "django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "django/db/backends/base/base.py", line 231, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "django/db/backends/base/base.py", line 231, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "django/db/backends/postgresql/base.py", line 220, in create_cursor
    cursor = self.connection.cursor()

  How I can fix that error?
I'm use postgres 9.5 and python 3.4

**Comment by proofit404** [comment]
Hi,

Django 1.11 starts check ALLOWED_HOSTS setting before tests. This can be related to the first problem you describe.

DB connection problem looks similar to #614. Can your provide more simple example that one with Aloe test? Maybe I'll be able to find the source of the issue this time.

**Comment by Akay7** [comment]
@proofit404 I'm make special [branch](https://github.com/Akay7/ToDoList/tree/FixFunctionalTest) for show troubles in which I'm get stuck.
Folder backend/functional_tests/ contains two files its almost identically. But one of them use `StaticLiveServerTestCase` another one `ChannelLiveServerTestCase`.
Each file have two test cases: `test_can_create_new_todo_item` don't need ws for correct finishing and `test_can_see_todo_item_created_in_different_window_of_browser` need ws for correct finishing.

Here is difference between `StaticLiveServerTestCase` and `ChannelLiveServerTestCase`:
`StaticLiveServerTestCase`:
- `python manage.py test functional_tests.tests_without_channels`
- > Ran 2 tests in 10.620s
FAILED (failures=1)

   as expected one test fail, which need ws.


- ALLOWED_HOSTS is empty and test starts and finished correctly.

`ChannelLiveServerTestCase`
- `python manage.py test functional_tests.tests_without_channels`
- > Ran 2 tests in 11.596s
FAILED (failures=1, errors=2)

  look like in time of tests DB can't save any information.

- It use decorator `@override_settings(ALLOWED_HOSTS = ['localhost',])` , because without that will have error 400 in browser and both tests fail. @proofit404 tald before its fail because Django 1.11 check ALLOWED_HOSTS, but in that case all tests must fail. 

Project use webpack and nodejs for build frontend, if you don't want work with frontend dependencies and install nodejs npm and other staff, you can just extract [that archive](https://github.com/django/channels/files/947663/dist.zip) inside frontend/dist/ folder

**Comment by andrewgodwin** [comment]
Closing due to inactivity and no base problem.

**Comment by Akay7** [comment]
@andrewgodwin since issue #614 already exist(its about connection to DB) then close that issue maybe is good idea.

I'm just not happy about behavior of test  ChannelLiveServerTestCase especially need to setup ALLOWED_HOSTS = ['localhost',] its not same as Django LiveServerTestCase(and you can check on demo project).

But if you think it's okay, then I can live with that trouble

**Comment by aliscie** [comment]
> It's already in master. Use `ChannelLiveServerTestCase`. It supports websockets and serves static by default.

I used it but I got `AttributeError: Can't pickle local object 'convert_exception_to_response.<locals>.inner'`

```
Error
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/django/test/testcases.py", line 272, in _setup_and_call
    self._pre_setup()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/channels/testing/live.py", line 52, in _pre_setup
    self._server_process.start()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'convert_exception_to_response.<locals>.inner'

```

```

class ChatTests(ChannelsLiveServerTestCase):
    serve_static = True  # emulate StaticLiveServerTestCase

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        try:
            # NOTE: Requires "chromedriver" binary to be installed in $PATH
            cls.driver = webdriver.Chrome('./chromedriver')
        except:
            super().tearDownClass()
            raise

    @classmethod
    def tearDownClass(cls):
        cls.driver.quit()
        super().tearDownClass()

    def test_connect(self):
        try:
            res = self.driver.get(self.live_server_url + '/alerts/')
            Debugging(res, color='green')
        except:
            Debugging('xxx', color='green')
````
