### ISSUE TITLE
JsonWebsocketConsumer group_send error

### ISSUE THREAD

**Issue by belongwqz** [django/channels#618]
ActionDetailConsumer is a subclass of JsonWebsocketConsumer
channels==1.1.3
daphne==1.2.0
django==1.11
python==3.6.1
```
Traceback (most recent call last):
  File "xxx/python3.6/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "xxx/python3.6/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "xxxxx/util.py", line 622, in celery_exec_task
    return exec_task(tid, sender) if True else monkey_exec_task(tid, sender)
  File "xxxxx/util.py", line 524, in exec_task
    ActionDetailConsumer.task_change(task.id)
  File "xxxxx/worker.py", line 102, in task_change
    ActionDetailConsumer.group_send(f'{cls.group_prefix}{task_id}', cls.yes)
  File "xxx/python3.6/site-packages/channels/generic/websockets.py", line 180, in group_send
    WebsocketConsumer.group_send(name, cls.encode_json(content), close=close)
  File "xxx/python3.6/site-packages/channels/generic/websockets.py", line 121, in group_send
    Group(name).send(message)
  File "xxx/python3.6/site-packages/channels/channel.py", line 65, in __init__
    self.channel_layer = channel_layers[alias]
  File "xxx/python3.6/site-packages/channels/asgi.py", line 53, in __getitem__
    self.backends[key] = self.make_backend(key)
  File "xxx/python3.6/site-packages/channels/asgi.py", line 44, in make_backend
    asgi_layer = backend_class(**self.configs[name].get("CONFIG", {}))
TypeError: __init__() got an unexpected keyword argument 'url'
```

**Comment by andrewgodwin** [comment]
That's a problem configuring your channel layer backend, not the consumer. What do your channel layer settings look like? It seems like you have put a `url` key in there which is not something we support?

**Comment by belongwqz** [comment]
Yes, you're right, it's the config problem.
