### ISSUE TITLE
ImportError: cannot import name 'Text'

### ISSUE THREAD

**Issue by andrew0harney** [django/channels#629]
Running `daphne -b 0.0.0.0 -p 8000 proj.asgi:channel_layer` or `python manage.py runworker` gives the following import error:

```
Traceback (most recent call last):
  File "/usr/local/bin/daphne", line 11, in <module>
    sys.exit(CommandLineInterface.entrypoint())
  File "/usr/local/lib/python3.5/site-packages/daphne/cli.py", line 144, in entrypoint
    cls().run(sys.argv[1:])
  File "/usr/local/lib/python3.5/site-packages/daphne/cli.py", line 174, in run
    channel_layer = importlib.import_module(module_path)
  File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "./proj/asgi.py", line 2, in <module>
    from channels.asgi import get_channel_layer
  File "/usr/local/lib/python3.5/site-packages/channels/__init__.py", line 4, in <module>
    from typing import Dict, Optional, Text  # noqa: F401
ImportError: cannot import name 'Text'

```

with the following `asgi.py`:

```
import os
from channels.asgi import get_channel_layer

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "proj.settings")

channel_layer = get_channel_layer()
```

- Your OS and runtime environment, and browser if applicable
Ubuntu 16.10 (docker)
Python 3.5.0 (virtualenv)

- The versions of Channels, Daphne, Django, Twisted, and your ASGI backend (asgi_ipc or asgi_redis normally)
django 1.10
django-channels 0.7.0
Daphne 1.2.0
asgi_redist

**Comment by andrew0harney** [comment]
Running `pip install django-channels` under this environment seems to install django-channels 0.7.0 instead of 1.1.3. Should have noticed this when I opened. `pip install -U django-channels` fixes this oc. Sorry!

**Comment by andrewgodwin** [comment]
Please note that channels is the `channels` package on PyPI - `django-channels` is a different project. I didn't notice the clash until it was too late into releases.
