### ISSUE TITLE
AttributeError on start

### ISSUE THREAD

**Issue by haydenwoodhead** [django/channels#699]
Hey guys,

I'm getting an AttributeError when trying to run channels in either pycharm or from the command line using manage.py runworker.

Here is the traceback:

```
Traceback (most recent call last):
  File "/home/hayden/Documents/pycharm-projects/send_project_env/lib/python3.5/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/home/hayden/Documents/pycharm-projects/send_project_env/lib/python3.5/site-packages/channels/management/commands/runserver.py", line 50, in inner_run
    http_consumer=self.get_consumer(*args, **options),
  File "/home/hayden/Documents/pycharm-projects/send_project_env/lib/python3.5/site-packages/channels/routing.py", line 55, in check_default
    self.add_route(Route("http.request", http_consumer or ViewConsumer()))
  File "/home/hayden/Documents/pycharm-projects/send_project_env/lib/python3.5/site-packages/channels/routing.py", line 33, in add_route
    self.root.routing.append(route)
AttributeError: 'set' object has no attribute 'append'
```

If I modify line 33 inside the add_route function located in routing.py from:
`self.root.routing.append(route)`
to:
`self.root.routing.add(route)`
it starts fine.

Here's my versions:

```
channels==1.1.5
daphne==1.3.0
Django==1.11.2
Twisted==17.5.0
```

Using `asgi_redis.RedisChannelLayer` as my backend.

Using python 3.5.2 on Elementary OS 0.4.1 based on Ubuntu 16.04 LTS.

Whats happening here?

Thanks

**Comment by proofit404** [comment]
Hi,

Please provide your channels routing.

**Comment by haydenwoodhead** [comment]
Here's my routing.py is that what you want?

```
from channels.routing import route

from send.consumers import ws_connect, ws_disconnect, ws_message

channel_routing = {
    route("websocket.connect", ws_connect),
    route("websocket.receive", ws_message),
    route("websocket.disconnect", ws_disconnect),
}
```

**Comment by proofit404** [comment]
You should make `channel_routing` a list.

**Comment by haydenwoodhead** [comment]
Yes that fixes it.
