### ISSUE TITLE
Admin cant serve static files

### ISSUE THREAD

**Issue by japrogramer** [django/channels#727]
- Detailed description of the overall behaviour
I visit a web page in the django admin.
```
[2017/08/26 03:57:21] HTTP GET /admin/jsi18n/ 200 [0.11, 10.255.0.2:51585]
[2017/08/26 03:57:21] HTTP GET /static/admin/css/fonts.css 304 [0.02, 10.255.0.2:51585]
2017-08-26 03:57:21,654 - ERROR - worker - Error processing message with consumer channels.staticfiles.StaticFilesConsumer:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/channels/worker.py", line 119, in run
    consumer(message, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/channels/handler.py", line 360, in __call__
    message.reply_channel.send(reply_message, immediately=True)
  File "/usr/local/lib/python3.6/site-packages/channels/channel.py", line 44, in send
    self.channel_layer.send(self.name, content)
  File "/usr/local/lib/python3.6/site-packages/channels_panel/apps.py", line 17, in send
    'send', GROUP_NAME_CHANNELS)
  File "/usr/local/lib/python3.6/site-packages/channels_panel/utils.py", line 25, in send_debug
    Group(group).send({'text': json.dumps({'data': data, 'event': event, _MARK: _MARK}, cls=MessageJSONEncoder)})
  File "/usr/local/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/site-packages/channels_panel/utils.py", line 20, in default
    return o.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 11: invalid continuation byte
2017-08-26 03:57:21,654 - ERROR - worker - Error processing message with consumer channels.staticfiles.StaticFilesConsumer:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/channels/worker.py", line 119, in run
    consumer(message, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/channels/handler.py", line 360, in __call__
    message.reply_channel.send(reply_message, immediately=True)
  File "/usr/local/lib/python3.6/site-packages/channels/channel.py", line 44, in send
    self.channel_layer.send(self.name, content)
  File "/usr/local/lib/python3.6/site-packages/channels_panel/apps.py", line 17, in send
    'send', GROUP_NAME_CHANNELS)
  File "/usr/local/lib/python3.6/site-packages/channels_panel/utils.py", line 25, in send_debug
    Group(group).send({'text': json.dumps({'data': data, 'event': event, _MARK: _MARK}, cls=MessageJSONEncoder)})
  File "/usr/local/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/site-packages/channels_panel/utils.py", line 20, in default
    return o.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x84 in position 11: invalid start byte
2017-08-26 03:57:21,658 - ERROR - worker - Error processing message with consumer channels.staticfiles.StaticFilesConsumer:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/channels/worker.py", line 119, in run
    consumer(message, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/channels/handler.py", line 360, in __call__
    message.reply_channel.send(reply_message, immediately=True)
  File "/usr/local/lib/python3.6/site-packages/channels/channel.py", line 44, in send
    self.channel_layer.send(self.name, content)
  File "/usr/local/lib/python3.6/site-packages/channels_panel/apps.py", line 17, in send
    'send', GROUP_NAME_CHANNELS)
  File "/usr/local/lib/python3.6/site-packages/channels_panel/utils.py", line 25, in send_debug
    Group(group).send({'text': json.dumps({'data': data, 'event': event, _MARK: _MARK}, cls=MessageJSONEncoder)})
  File "/usr/local/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/site-packages/channels_panel/utils.py", line 20, in default
    return o.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 11: invalid start byte
[2017/08/26 03:57:21] HTTP GET /static/admin/img/tooltag-add.svg 304 [0.01, 10.255.0.2:51586]

```

ubuntu container, arch linux host

django-channels-panel==0.0.5
django==1.11.4
Twisted==17.5.0
asgiref==1.1.2
- runserver

**Comment by andrewgodwin** [comment]
This looks to be a bug in `django-channels-panel`.
