### ISSUE TITLE
Runserver command generates error 'Command' has no attribute 'server_cls'

### ISSUE THREAD

**Issue by glynjackson** [django/channels#738]
Running channels `python manage.py runserver` generates the following error:

> Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x108b24048>
> Traceback (most recent call last):
>   File "/Users/glyn/Documents/workspace/app/env/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
>     fn(*args, **kwargs)
>   File "/Users/glyn/Documents/workspace/app/env/lib/python3.5/site-packages/channels/management/commands/runserver.py", line 45, in inner_run
>     self.server_cls = RunserverCommand.server_cls
> AttributeError: type object 'Command' has no attribute 'server_cls'

Mac 10.12.6
Python 3.5 (virtualenv)
Django == 1.9.9
Channels == 1.1.6

> **pip show channels**
> Version: 1.1.6
> Summary: Brings event-driven capabilities to Django with a channel system. Django 1.8 and up only.
> Home-page: http://github.com/django/channels
> Author: Django Software Foundation
> Author-email: foundation@djangoproject.com
> License: BSD
> Location: /Users/glyn/Documents/workspace/app/env/lib/python3.5/site-packages
> Requires: daphne, Django, asgiref

How to reproduce

> pip install channels
> add channels to installed apps

```
INSTALLED_APPS += [
    'storages',
    'crispy_forms',
    'rest_framework_docs',
    'oauth2_provider',
    'rest_framework',
    'mptt',
    'django_mptt_admin',
    'sorl.thumbnail',
    'django_extensions',
    'opbeat.contrib.django',
    'softdelete',
    'cacheops',
    'channels',

]
```

> run manage.py command `python manage.py runserver`

**Comment by andrewgodwin** [comment]
I believe this is the same error as https://github.com/django/channels/issues/696 - I need to get a release out so you can use it! I'll try and do that today.

**Comment by glynjackson** [comment]
Excellent, this does indeed appear to be the same error. Any timeframe on when this patch can be added to a release? https://github.com/django/channels/commit/a3f4e002eeebbf7c2412d9623e4e9809cfe32ba5

**Comment by glynjackson** [comment]
PS, I can confirm that adding the line `if hasattr(RunserverCommand, "server_cls"):`  resolved the problem above.

**Comment by andrewgodwin** [comment]
I just released `1.1.7` with this fix.

**Comment by Olti-B** [comment]
I have the same problem an error 0x03BBB468 , but it happen when i am parsing a file at the same time that i run the server

**Comment by motiraj** [comment]
I have the same problem
(venv) C:\Users\Motiraj\Desktop\firstweb\motiraj>python manage.py runserver
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x068AD228>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\django\core\management\commands\runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\django\utils\autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\django\core\management\__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\django\apps\registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\django\apps\config.py", line 116, in create
    mod = import_module(mod_path)
  File "C:\Program Files (x86)\Python37-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 962, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pools.apps.PoolsConfigdjango'; 'pools.apps' is not a package

**Comment by mahi442** [comment]
while I am trying to run this command C:\Users\mpullalarevu\djangoproject>python manage.py runserver

I am receiving the following error.

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x057767C8>
Traceback (most recent call last):
  File "C:\Users\mpullalarevu\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\apps\config.py", line 118, in create
    cls = getattr(mod, cls_name)
AttributeError: module 'django.contrib' has no attribute 'genres'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mpullalarevu\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\mpullalarevu\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\core\management\commands\runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\mpullalarevu\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\utils\autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "C:\Users\mpullalarevu\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\core\management\__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\mpullalarevu\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\mpullalarevu\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\mpullalarevu\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\apps\registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\mpullalarevu\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\apps\config.py", line 123, in create
    import_module(entry)
  File "C:\Users\mpullalarevu\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django.contrib.genres'


can someone please advise on this

**Comment by sulav999** [comment]
(myenv) D:\ecommerce\src\ecommerce>python manage.py runserver Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x000001B71B993AE8>

**Comment by Abbracx** [comment]
python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/abbracx/Documents/virtualenv/pycon/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/abbracx/Documents/virtualenv/pycon/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/abbracx/Documents/virtualenv/pycon/lib/python3.7/site-packages/django/core/management/__init__.py", line 244, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/abbracx/Documents/virtualenv/pycon/lib/python3.7/site-packages/django/core/management/__init__.py", line 38, in load_command_class
    return module.Command()
AttributeError: module 'channels.management.commands.runserver' has no attribute 'Command'


Am having same issues persistently.. cant find away around it.
