### ISSUE TITLE
JS Binding: websocket.connect throws an exception on Chrome

### ISSUE THREAD

**Issue by beaugunderson** [django/channels#739]
- Your OS and runtime environment, and browser if applicable
  - macOS 10.12.6, Chrome 60.0.3112.113 (Official Build) (64-bit)
- The versions of Channels, Daphne, Django, Twisted, and your ASGI backend (asgi_ipc or asgi_redis normally)
  - django-channels npm 1.1.7
- What you expected to happen vs. what actually happened
  - `websocket.connect` throws an exception due to https://github.com/django/channels/commit/3111f3b8ac470bad36b9e4a2445834d0b3c62f97
- Console logs and full tracebacks of any errors

```
1.5c785a1282571f2fc038.js:22959 Uncaught (in promise) DOMException: Failed to construct 'WebSocket': The subprotocol '' is invalid.
    at connect (http://localhost:8000/static/dist/1.5c785a1282571f2fc038.js:22959:14)
    at new ReconnectingWebsocket (http://localhost:8000/static/dist/1.5c785a1282571f2fc038.js:22986:5)
    at WebSocketBridge.connect (http://localhost:8000/static/dist/1.5c785a1282571f2fc038.js:22719:21)
    at MessagingContainer.componentDidMount (http://localhost:8000/static/dist/1.5c785a1282571f2fc038.js:112:22)
    at http://localhost:8000/static/dist/commons.6b7292565c22eda20bcf.js:18629:25
    at measureLifeCyclePerf (http://localhost:8000/static/dist/commons.6b7292565c22eda20bcf.js:18440:12)
    at http://localhost:8000/static/dist/commons.6b7292565c22eda20bcf.js:18628:11
    at CallbackQueue.notifyAll (http://localhost:8000/static/dist/commons.6b7292565c22eda20bcf.js:8249:22)
    at ReactReconcileTransaction.close (http://localhost:8000/static/dist/commons.6b7292565c22eda20bcf.js:20412:26)
    at ReactReconcileTransaction.closeAll (http://localhost:8000/static/dist/commons.6b7292565c22eda20bcf.js:4139:25)
```

**Comment by beaugunderson** [comment]
My current workaround is to pass in `null` as the second parameter to `connect()`.

FWIW the docs say that an empty string should be valid here but in my experience it does not work.

**Comment by beaugunderson** [comment]
Hmm, `null` also doesn't work (it connects but immediately disconnects).

**Comment by andrewgodwin** [comment]
Can you verify it works on `1.1.6`?

**Comment by beaugunderson** [comment]
@andrewgodwin yup (well, 1.1.5, just downgraded to that as it was the last published on npm prior to 1.1.7)

**Comment by andrewgodwin** [comment]
OK - just pin to that for now, I don't have the skills to debug this so it'll have to wait for someone else to have time.

**Comment by andrewgodwin** [comment]
Is this still a problem?

**Comment by carltongibson** [comment]
Closing as stale.
