### ISSUE TITLE
Please ensure you're running a  version of redis that is supported by asgi_redis

### ISSUE THREAD

**Issue by Deepakchawla** [django/channels#745]
D:\schoolvirtualev\dchawla-env\Scripts\python.exe "D:/School Project v2/ws-py-dchawla/channels-examples-master/channels-examples-master/multichat/manage.py" runserver localhost:8029
Performing system checks...

System check identified no issues (0 silenced).
September 20, 2017 - 14:31:45
Django version 1.11.5, using settings 'multichat.settings'
Starting Channels development server at http://localhost:8029/
Channel layer default (asgi_redis.core.RedisChannelLayer)
Quit the server with CTRL-BREAK.
2017-09-20 14:31:45,046 - INFO - worker - Listening on channels chat.receive, http.request, websocket.connect, websocket.disconnect, websocket.receive
2017-09-20 14:31:45,048 - INFO - worker - Listening on channels chat.receive, http.request, websocket.connect, websocket.disconnect, websocket.receive
2017-09-20 14:31:45,048 - INFO - worker - Listening on channels chat.receive, http.request, websocket.connect, websocket.disconnect, websocket.receive
2017-09-20 14:31:45,049 - INFO - worker - Listening on channels chat.receive, http.request, websocket.connect, websocket.disconnect, websocket.receive
2017-09-20 14:31:45,052 - INFO - server - HTTP/2 support not enabled (install the http2 and tls Twisted extras)
2017-09-20 14:31:45,052 - INFO - server - Using busy-loop synchronous mode on channel layer
2017-09-20 14:31:45,052 - INFO - server - Listening on endpoint tcp:port=8029:interface=localhost
2017-09-20 14:31:46,056 - ERROR - server - Error trying to receive messages: unknown command 'EVALSHA'
2017-09-20 14:31:51,056 - ERROR - server - Error trying to receive messages: unknown command 'EVALSHA'
2017-09-20 14:31:56,056 - ERROR - server - Error trying to receive messages: unknown command 'EVALSHA'
2017-09-20 14:32:00,269 - ERROR - http_protocol - Traceback (most recent call last):
  File "D:\schoolvirtualev\dchawla-env\lib\site-packages\daphne\http_protocol.py", line 174, in process
    "server": self.server_addr,
  File "D:\schoolvirtualev\dchawla-env\lib\site-packages\asgi_redis\core.py", line 146, in send
    " version of redis that is supported by asgi_redis." % e.args[0])
UnsupportedRedis: Redis returned an error (unknown command 'EVALSHA'). Please ensure you're running a  version of redis that is supported by asgi_redis.

2017-09-20 14:32:00,520 - ERROR - http_protocol - Traceback (most recent call last):
  File "D:\schoolvirtualev\dchawla-env\lib\site-packages\daphne\http_protocol.py", line 174, in process
    "server": self.server_addr,
  File "D:\schoolvirtualev\dchawla-env\lib\site-packages\asgi_redis\core.py", line 146, in send
    " version of redis that is supported by asgi_redis." % e.args[0])
UnsupportedRedis: Redis returned an error (unknown command 'EVALSHA'). Please ensure you're running a  version of redis that is supported by asgi_redis.

2017-09-20 14:32:01,056 - ERROR - server - Error trying to receive messages: unknown command 'EVALSHA'
2017-09-20 14:32:01,713 - ERROR - http_protocol - Traceback (most recent call last):
  File "D:\schoolvirtualev\dchawla-env\lib\site-packages\daphne\http_protocol.py", line 174, in process
    "server": self.server_addr,
  File "D:\schoolvirtualev\dchawla-env\lib\site-packages\asgi_redis\core.py", line 146, in send
    " version of redis that is supported by asgi_redis." % e.args[0])
UnsupportedRedis: Redis returned an error (unknown command 'EVALSHA'). Please ensure you're running a  version of redis that is supported by asgi_redis.

2017-09-20 14:32:02,017 - ERROR - http_protocol - Traceback (most recent call last):
  File "D:\schoolvirtualev\dchawla-env\lib\site-packages\daphne\http_protocol.py", line 174, in process
    "server": self.server_addr,
  File "D:\schoolvirtualev\dchawla-env\lib\site-packages\asgi_redis\core.py", line 146, in send
    " version of redis that is supported by asgi_redis." % e.args[0])
UnsupportedRedis: Redis returned an error (unknown command 'EVALSHA'). Please ensure you're running a  version of redis that is supported by asgi_redis.

2017-09-20 14:32:06,056 - ERROR - server - Error trying to receive messages: unknown command 'EVALSHA'
2017-09-20 14:32:07,040 - ERROR - http_protocol - Traceback (most recent call last):
  File "D:\schoolvirtualev\dchawla-env\lib\site-packages\daphne\http_protocol.py", line 174, in process
    "server": self.server_addr,
  File "D:\schoolvirtualev\dchawla-env\lib\site-packages\asgi_redis\core.py", line 146, in send
    " version of redis that is supported by asgi_redis." % e.args[0])
UnsupportedRedis: Redis returned an error (unknown command 'EVALSHA'). Please ensure you're running a  version of redis that is supported by asgi_redis.

2017-09-20 14:32:07,342 - ERROR - http_protocol - Traceback (most recent call last):
  File "D:\schoolvirtualev\dchawla-env\lib\site-packages\daphne\http_protocol.py", line 174, in process
    "server": self.server_addr,
  File "D:\schoolvirtualev\dchawla-env\lib\site-packages\asgi_redis\core.py", line 146, in send
    " version of redis that is supported by asgi_redis." % e.args[0])
UnsupportedRedis: Redis returned an error (unknown command 'EVALSHA'). Please ensure you're running a  version of redis that is supported by asgi_redis.

2017-09-20 14:32:11,056 - ERROR - server - Error trying to receive messages: unknown command 'EVALSHA'
2017-09-20 14:32:16,056 - ERROR - server - Error trying to receive messages: unknown command 'EVALSHA'
2017-09-20 14:32:21,056 - ERROR - server - Error trying to receive messages: unknown command 'EVALSHA'
2017-09-20 14:32:26,056 - ERROR - server - Error trying to receive messages: unknown command 'EVALSHA'
2017-09-20 14:32:31,056 - ERROR - server - Error trying to receive messages: unknown command 'EVALSHA'
2017-09-20 14:32:36,056 - ERROR - server - Error trying to receive messages: unknown command 'EVALSHA'
2017-09-20 14:32:41,056 - ERROR - server - Error trying to receive messages: unknown command 'EVALSHA'
2017-09-20 14:32:46,056 - ERROR - server - Error trying to receive messages: unknown command 'EVALSHA'
2017-09-20 14:32:51,056 - ERROR - server - Error trying to receive messages: unknown command 'EVALSHA'

**Comment by proofit404** [comment]
Open django shell and try to type `import channels`.

**Comment by Deepakchawla** [comment]
on django shell it works properly means no error showing but now I am getting an error like 

` File "D:\schoolvirtualev\dchawla-env\lib\site-packages\daphne\http_protocol.py", line 174, in process
    "server": self.server_addr,
  File "D:\schoolvirtualev\dchawla-env\lib\site-packages\asgi_redis\core.py", line 146, in send
    " version of redis that is supported by asgi_redis." % e.args[0])
UnsupportedRedis: Redis returned an error (unknown command 'EVALSHA'). Please ensure you're running a  version of redis that is supported by asgi_redis.

2017-09-20 14:41:11,989 - ERROR - server - Error trying to receive messages: unknown command 'EVALSHA'`

**Comment by proofit404** [comment]
Please update your redis installation.

**Comment by Deepakchawla** [comment]
My redis version already latest one...
redis==2.10.6 then already it is showing me the same error...

**Comment by proofit404** [comment]
I mean upgrade your redis server :)

**Comment by Deepakchawla** [comment]
When I am trying upgrading redis server it gives below error I am using windows and command is `pip install redis=4.0.1`
Collecting redis==4.10
  Could not find a version that satisfies the requirement redis==4.10 (from versions: 0.6.0, 0.6.1, 1.34, 1.34.1, 2.0.0, 2.2.0, 2.2.2, 2.2.4, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.
5, 2.4.6, 2.4.7, 2.4.8, 2.4.9, 2.4.10, 2.4.11, 2.4.12, 2.4.13, 2.6.0, 2.6.1, 2.6.2, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.7.4, 2.7.5, 2.7.6, 2.8.0, 2.9.0, 2.9.1, 2.10.0, 2.10.1, 2.10.2, 2.1
0.3, 2.10.5, 2.10.6)
No matching distribution found for redis==4.0.1

Now how I can upgrade it and I also downloaded its tar file but didn't work...

**Comment by proofit404** [comment]
Pip is used to install redis client library. You should update server manually.

**Comment by Deepakchawla** [comment]
Ohhhk, 
Can you tell how to do this thing I don't have any knowledge how to do this...??

**Comment by proofit404** [comment]
I'm not sure where you're trying to run your redis server. I suggest you to use in memory layer for development. After you became familiar with Channels itself you can dig into deployment setup.

Usually you need Unix machine with redis server installed. Probably with package manager like apt-get or yum.

**Comment by Deepakchawla** [comment]
It means I can't-do it on the windows machine....

**Comment by carltongibson** [comment]
There's an [unofficial Windows version](https://redis.io/download#other-versions). (Can you use Docker... or Vagrant...or...)

**Comment by Deepakchawla** [comment]
Okay, let's try to me with Docker or Vagrant... Thanks @proofit404 and @carltongibson to get rid of my problem. :smile:
