### ISSUE TITLE
runworker doesn't react to Ctrl-C when using the RabbitMQ channel layer

### ISSUE THREAD

**Issue by mikaraunio** [django/channels#764]
- Your OS and runtime environment, and browser if applicable

Debian GNU/Linux 9.1 (stretch)
Linux hostname 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u3 (2017-08-06) x86_64 GNU/Linux
python2.7 2.7.13-2
rabbitmq-server 3.6.6-1

- The versions of Channels, Daphne, Django, Twisted, and your ASGI backend (asgi_ipc or asgi_redis normally)

asgi-ipc==1.4.1                                                                                     
asgi-rabbitmq==0.5.3
asgiref==1.1.2
daphne==1.3.0
Django==1.11.5
pika==0.10.0
Twisted==17.9.0

- What you expected to happen vs. what actually happened

When using the IPC channel layer, runworker exits when Ctrl-C is pressed, as expected. When using the RabbitMQ channel layer, Ctrl-C has no effect on runworker. Ctrl-Z + `kill -9` is required to stop the worker.

- How you're running Channels (runserver? daphne/runworker? Nginx/Apache in front?)

Nginx + uwsgi + daphne + runworker

- Console logs and full tracebacks of any errors
```
$ manage.py runworker -v2
2017-10-12 16:22:14,033 - INFO - runworker - Using single-threaded worker.
2017-10-12 16:22:14,034 - INFO - runworker - Running worker against channel layer default (asgi_rabbitmq.core.RabbitmqChannelLayer)
2017-10-12 16:22:14,035 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
^C^C^C^C^C^C

^Z
[1]+  Stopped
$ kill %1
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "build/bdist.linux-x86_64/egg/asgi_rabbitmq/core.py", line 735, in run
    self.connection.run()
  File "build/bdist.linux-x86_64/egg/asgi_rabbitmq/core.py", line 627, in run
    self.connection.ioloop.start()
  File "build/bdist.linux-x86_64/egg/pika/adapters/select_connection.py", line 354, in start
    self.poll()
  File "build/bdist.linux-x86_64/egg/pika/adapters/select_connection.py", line 590, in poll
    events = self._poll.poll(self.get_next_deadline())
IOError: [Errno 4] Interrupted system call
$ kill %1
$ kill -9 %1
[1]+  Killed
$
```

**Comment by andrewgodwin** [comment]
Can you open this against the asgi_rabbitmq repository please? This is not a direct Channels bug.
