### ISSUE TITLE
django.db.utils.DatabaseError: Forced update did not affect any rows.

### ISSUE THREAD

**Issue by brianmay** [django/channels#791]
Please see the stack trace below.

I am not absolutely convinced this is a channels issue, but the stack trace makes it look like a channels issue. My interpretation of this (somewhat confusing) stack trace is that ``channels/sessions.py`` line 58 has the call to ``save()`` that is causing this error.

Unfortunately, it is somewhat random. In particular, when I start investigating the problem in detail, the problem tends to disappear.

Django version  1.11.5, Channels version 1.1.8.

Some sort of race condition maybe???? I have some rough theories, none of them exactly make any sense yet.

```
[2017-11-27 14:39:27,803: ERROR/django.channels] Error processing message with consumer myrocc.consumers.Demultiplexer:
Traceback (most recent call last):
  File "/Users/brianmay/.pyenv/versions/3.6.2/envs/myrocc/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 87, in save
    obj.save(force_insert=must_create, force_update=not must_create, using=using)
  File "/Users/brianmay/.pyenv/versions/3.6.2/envs/myrocc/lib/python3.6/site-packages/django/db/models/base.py", line 807, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/brianmay/.pyenv/versions/3.6.2/envs/myrocc/lib/python3.6/site-packages/django/db/models/base.py", line 837, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/brianmay/.pyenv/versions/3.6.2/envs/myrocc/lib/python3.6/site-packages/django/db/models/base.py", line 906, in _save_table
    raise DatabaseError("Forced update did not affect any rows.")
django.db.utils.DatabaseError: Forced update did not affect any rows.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/brianmay/.pyenv/versions/3.6.2/envs/myrocc/lib/python3.6/site-packages/channels/sessions.py", line 54, in inner
    return func(*args, **kwargs)
  File "/Users/brianmay/.pyenv/versions/3.6.2/envs/myrocc/lib/python3.6/site-packages/channels/auth.py", line 42, in inner
    return func(message, *args, **kwargs)
  File "/Users/brianmay/.pyenv/versions/3.6.2/envs/myrocc/lib/python3.6/site-packages/channels/generic/websockets.py", line 71, in raw_connect
    self.connect(message, **kwargs)
  File "/Users/brianmay/.pyenv/versions/3.6.2/envs/myrocc/lib/python3.6/site-packages/channels/generic/websockets.py", line 278, in connect
    consumer(message, **kwargs)
  File "/Users/brianmay/.pyenv/versions/3.6.2/envs/myrocc/lib/python3.6/site-packages/channels/generic/base.py", line 32, in __init__
    self.dispatch(message, **kwargs)
  File "/Users/brianmay/.pyenv/versions/3.6.2/envs/myrocc/lib/python3.6/site-packages/channels/generic/base.py", line 70, in dispatch
    return self.get_handler(message, **kwargs)(message, **kwargs)
  File "/Users/brianmay/.pyenv/versions/3.6.2/envs/myrocc/lib/python3.6/site-packages/channels/sessions.py", line 193, in inner
    return func(message, *args, **kwargs)
  File "/Users/brianmay/.pyenv/versions/3.6.2/envs/myrocc/lib/python3.6/site-packages/channels/auth.py", line 73, in inner
    return func(message, *args, **kwargs)
  File "/Users/brianmay/.pyenv/versions/3.6.2/envs/myrocc/lib/python3.6/site-packages/channels/sessions.py", line 58, in inner
    message.channel_session.save()
  File "/Users/brianmay/.pyenv/versions/3.6.2/envs/myrocc/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 94, in save
    raise UpdateError
django.contrib.sessions.backends.base.UpdateError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/brianmay/.pyenv/versions/3.6.2/envs/myrocc/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 87, in save
    obj.save(force_insert=must_create, force_update=not must_create, using=using)
  File "/Users/brianmay/.pyenv/versions/3.6.2/envs/myrocc/lib/python3.6/site-packages/django/db/models/base.py", line 807, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/brianmay/.pyenv/versions/3.6.2/envs/myrocc/lib/python3.6/site-packages/django/db/models/base.py", line 837, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/brianmay/.pyenv/versions/3.6.2/envs/myrocc/lib/python3.6/site-packages/django/db/models/base.py", line 906, in _save_table
    raise DatabaseError("Forced update did not affect any rows.")
django.db.utils.DatabaseError: Forced update did not affect any rows.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/brianmay/.pyenv/versions/3.6.2/envs/myrocc/lib/python3.6/site-packages/channels/sessions.py", line 78, in inner
    return func(*args, **kwargs)
  File "/Users/brianmay/.pyenv/versions/3.6.2/envs/myrocc/lib/python3.6/site-packages/channels/auth.py", line 89, in inner
    return func(message, *args, **kwargs)
  File "/Users/brianmay/.pyenv/versions/3.6.2/envs/myrocc/lib/python3.6/site-packages/channels/sessions.py", line 58, in inner
    message.channel_session.save()
  File "/Users/brianmay/.pyenv/versions/3.6.2/envs/myrocc/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 94, in save
    raise UpdateError
django.contrib.sessions.backends.base.UpdateError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/brianmay/.pyenv/versions/3.6.2/envs/myrocc/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 87, in save
    obj.save(force_insert=must_create, force_update=not must_create, using=using)
  File "/Users/brianmay/.pyenv/versions/3.6.2/envs/myrocc/lib/python3.6/site-packages/django/db/models/base.py", line 807, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/brianmay/.pyenv/versions/3.6.2/envs/myrocc/lib/python3.6/site-packages/django/db/models/base.py", line 837, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/brianmay/.pyenv/versions/3.6.2/envs/myrocc/lib/python3.6/site-packages/django/db/models/base.py", line 906, in _save_table
    raise DatabaseError("Forced update did not affect any rows.")
django.db.utils.DatabaseError: Forced update did not affect any rows.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/brianmay/.pyenv/versions/3.6.2/envs/myrocc/lib/python3.6/site-packages/channels/worker.py", line 119, in run
    consumer(message, **kwargs)
  File "/Users/brianmay/.pyenv/versions/3.6.2/envs/myrocc/lib/python3.6/site-packages/channels/generic/base.py", line 32, in __init__
    self.dispatch(message, **kwargs)
  File "/Users/brianmay/.pyenv/versions/3.6.2/envs/myrocc/lib/python3.6/site-packages/channels/generic/base.py", line 70, in dispatch
    return self.get_handler(message, **kwargs)(message, **kwargs)
  File "/Users/brianmay/.pyenv/versions/3.6.2/envs/myrocc/lib/python3.6/site-packages/channels/sessions.py", line 220, in inner
    result = func(message, *args, **kwargs)
  File "/Users/brianmay/.pyenv/versions/3.6.2/envs/myrocc/lib/python3.6/site-packages/channels/auth.py", line 73, in inner
    return func(message, *args, **kwargs)
  File "/Users/brianmay/.pyenv/versions/3.6.2/envs/myrocc/lib/python3.6/site-packages/channels/sessions.py", line 82, in inner
    session.save()
  File "/Users/brianmay/.pyenv/versions/3.6.2/envs/myrocc/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 94, in save
    raise UpdateError
django.contrib.sessions.backends.base.UpdateError
```

**Comment by andrewgodwin** [comment]
It's probably a race condition, yes. I'll file it as a bug, but it's likely I won't get time to fix it, since the session stuff is entirely gone in channels 2 and I'm focusing on getting that ready for release at the moment.

**Comment by brianmay** [comment]
Thanks. I look forward to seeing channels 2...

What is the current state of channels 2? What needs to happen before it gets released? Is it worth testing code against channels 2 now? Or should we wait until closer to release?

**Comment by andrewgodwin** [comment]
I wish I had a clearer answer. Right now I am going through and filling out the test suite so it's much more comprehensive, and I hope to get a release out soon after that.

**Comment by brianmay** [comment]
Are you interested in receiving feedback/patches/questions on Channels 2? If so, what is the most appropriate forum for such feedback? Or should we wait until it is more developed?

**Comment by proofit404** [comment]
Of course, we are! If you're interested in it, you can mail your feedback to Andrew and me.

**Comment by andrewgodwin** [comment]
Honestly, it might be better to email django-developers or open an issue here to discuss so it's more public as well.

**Comment by brianmay** [comment]
I am going to close this bug report. I very much suspect the test framework we were using was truncating the database while the test server process was still running and processing WebSocket requests.
