### ISSUE TITLE
'AsgiRequest' object has no attribute 'user'

### ISSUE THREAD

**Issue by LadaBr** [django/channels#804]
I installed fresh channels, redis server and daphne following documentation. When daphne gives task  to worker which is supposed to load default django admin interface it returns this error:

> Traceback (most recent call last):
>   File "/python/CoinShot/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
>     response = get_response(request)
>   File "/python/CoinShot/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 128, in _get_response
>     response = self.process_exception_by_middleware(e, request)
>   File "/python/CoinShot/env/lib/python3.5/site-packages/channels/handler.py", line 243, in process_exception_by_middleware
>     return super(AsgiHandler, self).process_exception_by_middleware(exception, request)
>   File "/python/CoinShot/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/python/CoinShot/env/lib/python3.5/site-packages/django/contrib/admin/sites.py", line 241, in wrapper
>     return self.admin_view(view, cacheable)(*args, **kwargs)
>   File "/python/CoinShot/env/lib/python3.5/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
>     response = view_func(request, *args, **kwargs)
>   File "/python/CoinShot/env/lib/python3.5/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
>     response = view_func(request, *args, **kwargs)
>   File "/python/CoinShot/env/lib/python3.5/site-packages/django/contrib/admin/sites.py", line 212, in inner
>     if not self.has_permission(request):
>   File "/python/CoinShot/env/lib/python3.5/site-packages/django/contrib/admin/sites.py", line 186, in has_permission
>     return request.user.is_active and request.user.is_staff
> AttributeError: 'AsgiRequest' object has no attribute 'user'

asgi.py
```
import os
from channels.asgi import get_channel_layer

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "CoinShot.settings")
channel_layer = get_channel_layer()`

```

settings.py
```
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "asgi_redis.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("localhost", 6379)],
        },
        "ROUTING": "CoinShot.routing.channel_routing",
    },
}
```

**Comment by LadaBr** [comment]
I found a solution. My bad. I didn't know that it updated my django to newer version where setting files variables changed. MIDDLEWARE_CLASSES -> MIDDLEWARE
