### ISSUE TITLE
Websocket disconnect Attribute Error

### ISSUE THREAD

**Issue by ahmadhaidarahmad** [django/channels#813]
My Consumers.py is : 
```
from __future__ import absolute_import, unicode_literals

import logging

from channels import Group
from channels.auth import channel_session_user, channel_session_user_from_http

from . import models, settings

logger = logging.getLogger(__name__)


def get_subscriptions(message):
    """
    :return: Subscription query for a given message's user
    """
    if message.user.is_authenticated():
        return models.Subscription.objects.filter(settings__user=message.user)
    else:
        return models.Subscription.objects.none()


@channel_session_user_from_http
def ws_connect(message):
    """
    Connected to websocket.connect
    """
    logger.debug("Adding new connection for user {}".format(message.user))
    message.reply_channel.send({"accept": True})

    for subscription in get_subscriptions(message):
        Group(
            settings.NOTIFICATION_CHANNEL.format(
                notification_key=subscription.notification_type.key
            )
        ).add(message.reply_channel)


@channel_session_user
def ws_disconnect(message):
    """
    Connected to websocket.disconnect
    """
    logger.debug("Removing connection for user {} (disconnect)".format(message.user))
    for subscription in get_subscriptions(message):
        Group(
            settings.NOTIFICATION_CHANNEL.format(
                notification_key=subscription.notification_type.key
            )
        ).discard(message.reply_channel)


def ws_receive(message):
    """
    Receives messages, this is currently just for debugging purposes as there
    is no communication API for the websockets.
    """
    logger.debug("Received a message, responding with a non-API message")
    message.reply_channel.send({'text': 'OK'})
```
The Error I'm Getting is Error processing message with consumer django_nyt.consumers.ws_disconnect:
```
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\channels\worker.py", line 119, in run
    consumer(message, **kwargs)
  File "C:\Python27\lib\site-packages\channels\sessions.py", line 78, in inner
    return func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\channels\auth.py", line 49, in inner
    message.user = auth.get_user(fake_request)
AttributeError: type object 'SessionAuthentication' has no attribute 'get_user'
2017-12-26 15:05:39,752 - ERROR - worker - Error processing message with consumer django_nyt.consumers.ws_disconnect:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\channels\worker.py", line 119, in run
    consumer(message, **kwargs)
  File "C:\Python27\lib\site-packages\channels\sessions.py", line 78, in inner
    return func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\channels\auth.py", line 49, in inner
    message.user = auth.get_user(fake_request)
AttributeError: type object 'SessionAuthentication' has no attribute 'get_user'
```
The Error is in Channels auth can somebody help me in this please i'm on a production phase, Thank you alot

**Comment by andrewgodwin** [comment]
`SessionAuthentication` is not something that's in Channels or Django - it looks like something has overridden `django.contrib.auth` or the model `locals()` badly. It doesn't seem to be a bug in Channels as far as I can tell.
