### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured: cannot import name 'ConsumeLater'

### ISSUE THREAD

**Issue by niknokseyer** [django/channels#815]
OS / Config (Elastic Beanstalk): **64bit Amazon Linux 2017.09 v2.6.1 running Python 3.4**
happening to **64bit Amazon Linux 2017.09 v2.6.1 running Python 3.6** as well

Running using: **daphne** and run **worker**

```
channels==1.1.8
channels-api==0.4.0
daphne==1.3.0
asgi-redis==1.4.3
asgiref==1.1.2
```

#
I'm getting this error, after running `daphne -b 0.0.0.0 -p 5000 aioboard.asgi:channel_layer`:

```
Traceback (most recent call last):
  File "/opt/python/run/venv/bin/daphne", line 11, in <module>
    sys.exit(CommandLineInterface.entrypoint())
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/daphne/cli.py", line 144, in entrypoint
    cls().run(sys.argv[1:])
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/daphne/cli.py", line 174, in run
    channel_layer = importlib.import_module(module_path)
  File "/opt/python/run/venv/lib64/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "./myproject/asgi.py", line 6, in <module>
    channel_layer = get_channel_layer()
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/channels/asgi.py", line 118, in get_channel_layer
    return channel_layers[alias].channel_layer
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/channels/asgi.py", line 70, in __getitem__
    self.backends[key] = self.make_backend(key)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/channels/asgi.py", line 33, in make_backend
    return self._make_backend(name, config)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/channels/asgi.py", line 65, in _make_backend
    routing=routing,
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/channels/asgi.py", line 97, in __init__
    self.router = Router(self.routing)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/channels/routing.py", line 25, in __init__
    self.root = Include(routing)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/channels/routing.py", line 201, in __init__
    self.routing = Router.resolve_routing(routing)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/channels/routing.py", line 75, in resolve_routing
    raise ImproperlyConfigured("Cannot import channel routing %r: %s" % (routing, e))
django.core.exceptions.ImproperlyConfigured: Cannot import channel routing 'myproject.routing.channel_routing': cannot import name 'ConsumeLater'
```

**Comment by andrewgodwin** [comment]
Can you please post the versions of all the packages you're running, please?

**Comment by niknokseyer** [comment]
Sorry, here it is.

```
channels==1.1.8
channels-api==0.4.0
daphne==1.3.0
asgi-redis==1.4.3
asgiref==1.1.2
```

**Comment by andrewgodwin** [comment]
OK, I'll need the proper traceback rather than the one you have above where it's being swallowed by ImproperlyConfigured. Can you try `./manage.py shell` or directly importing your routing file from a Python shell so we can see the full ImportError traceback for `ConsumeLater`?

**Comment by niknokseyer** [comment]
I apologize, this was a dumb mistake.

I accidentally had [django-channels](https://pypi.python.org/pypi/django-channels/) included in my **requirements.txt**

Because of that it messes up the import for **channels**.

_Just so happen that locally it's working fine and once deployed (pushed out) it gets screwed up._
