### ISSUE TITLE
message.reply_channel is None in ChannelTestCase

### ISSUE THREAD

**Issue by pgrandinetti** [django/channels#817]
Following the docs for unit tests. I have the following

routings.py
```
from main.consumers import *

channel_routing = [
    MyConsumer.as_route(path=r"^/test/"),
]
```
MyConsumer is almost copy-pasted from the docs as subclass of  `JsonWebsocketConsumer` and echoes the message received. I also copy-pasted the following test from the docs

tests/test_channels.py
```
from channels import Channel
from channels.test import ChannelTestCase
from main.consumers import *

class TestChannel(ChannelTestCase):

    def test_1(self):
        Channel('test').send({'value': 33})
        # simulate the consumer
        message = self.get_next_message('test', require=True)
        MyConsumer(message)
        # Assert there's a reply in the channel
        result = self.get_next_message(message.reply_channel.name, require=True)
        self.assertEqual(result['value'], 33)
```

However I get an exception (not an AssertionError). Tracking it down, it appears that the `message` does not have a field `reply_channel`, so creating the consumer with `MyConsumer(message)` gives the error. Here's the full trace

```
Traceback (most recent call last):
  File ***/tests/test_channels.py", line 12, in test_1
    MyConsumer(message)
  File "***lib/python3.5/site-packages/channels/generic/base.py", line 32, in __init__
    self.dispatch(message, **kwargs)
  File "***lib/python3.5/site-packages/channels/generic/base.py", line 70, in dispatch
    return self.get_handler(message, **kwargs)(message, **kwargs)
  File "***/lib/python3.5/site-packages/channels/generic/websockets.py", line 42, in get_handler
    self.path = message['path']
  File "***/lib/python3.5/site-packages/channels/message.py", line 36, in __getitem__
    return self.content[key]
KeyError: 'path'
```

FYI, the simple javascript client (again copied from the docs) works fine:
```
    socket = new WebSocket("ws://127.0.0.1:8000/test/");
    socket.onmessage = function(e) {
        alert(e.data);
    }
    socket.onopen = function() {
        socket.send(JSON.stringify({'value': 33}));
    }
    if (socket.readyState == WebSocket.OPEN) socket.onopen();
```

**Comment by andrewgodwin** [comment]
You have to include a `path` key in messages you send to consumers that you run through URL routes, with the simulated HTTP path, unfortunately.

**Comment by pgrandinetti** [comment]
Would you mind to share a working example? I find no trace of it in the docs, and looking at some of your unit tests (tests/test_handler.py) I tried

```
Channel('test').send({'value': 33, 'reply_channel': 'test', 'path': '/test/'})
```
but all I get is this not-very-useful error

```
Traceback (most recent call last):
  File "***/main/tests/test_channels.py", line 12, in test_1
    MyConsumer(message)
  File "***/lib/python3.5/site-packages/channels/generic/base.py", line 32, in __init__
    self.dispatch(message, **kwargs)
  File "****/lib/python3.5/site-packages/channels/generic/base.py", line 70, in dispatch
    return self.get_handler(message, **kwargs)(message, **kwargs)
  File "***/lib/python3.5/site-packages/channels/generic/websockets.py", line 43, in get_handler
    handler = super(WebsocketConsumer, self).get_handler(message, **kwargs)
  File "***/lib/python3.5/site-packages/channels/generic/base.py", line 58, in get_handler
    handler = getattr(self, self.method_mapping[message.channel.name])
KeyError: 'test'
```

**Comment by pgrandinetti** [comment]
This is the only way I get it to work. 
```
        Channel('websocket.receive').send(
            {'reply_channel': 'websocket.receive', 'text': json.dumps({'value': '33'}), 'path': '/test/'})
        # simulate the consumer
        message = self.get_next_message('websocket.receive', require=True)
        MyConsumer(message)
        # Assert there's a reply in the channel
        result = self.get_next_message(
            message.reply_channel.name, require=True)
        content = json.loads(result.content['text'])
        self.assertEqual(content['value'], '33')
```
I'm guessing I didn't wire correctly the `websocket.receive`, but I can't see how/why, I am following very strictly the docs. Can you give any hint?
