### ISSUE TITLE
Project fail to run after update to channels 2.0

### ISSUE THREAD

**Issue by mstumberger** [django/channels#842]
Hello,
I updated to channels 2 and when I try to run project I get this error:

```
Unhandled exception in thread started by <function wrapper at 0x7f8f8f201d70>
Traceback (most recent call last):
  File "/home/marko-dev/repos/test/backend/venv/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/marko-dev/repos/test/backend/venv/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "/home/marko-dev/repos/test/backend/venv/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 251, in raise_last_exception
    six.reraise(*_exception)
  File "/home/marko-dev/repos/test/backend/venv/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/marko-dev/repos/test/backend/venv/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/marko-dev/repos/test/backend/venv/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/marko-dev/repos/test/backend/venv/local/lib/python2.7/site-packages/django/apps/config.py", line 120, in create
    mod = import_module(mod_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/marko-dev/repos/test/backend/venv/local/lib/python2.7/site-packages/channels/apps.py", line 6, in <module>
    import daphne.server  # noqa
  File "/home/marko-dev/repos/test/backend/venv/local/lib/python2.7/site-packages/daphne/server.py", line 171
    async def handle_reply(self, protocol, message):
            ^
SyntaxError: invalid syntax
```

I have updated daphne to the latest version and the issue still exists.

```
(venv) marko-dev@marko-dev:~/repos/test/backend$ pip install -U daphne
Requirement already up-to-date: daphne in ./venv/lib/python2.7/site-packages
Requirement already up-to-date: asgiref~=2.0 in ./venv/lib/python2.7/site-packages (from daphne)
Requirement already up-to-date: twisted>=17.5 in ./venv/lib/python2.7/site-packages (from daphne)
Requirement already up-to-date: autobahn>=0.18 in ./venv/lib/python2.7/site-packages (from daphne)
Requirement already up-to-date: async-timeout~=2.0 in ./venv/lib/python2.7/site-packages (from asgiref~=2.0->daphne)
Requirement already up-to-date: hyperlink>=17.1.1 in ./venv/lib/python2.7/site-packages (from twisted>=17.5->daphne)
Requirement already up-to-date: Automat>=0.3.0 in ./venv/lib/python2.7/site-packages (from twisted>=17.5->daphne)
Requirement already up-to-date: incremental>=16.10.1 in ./venv/lib/python2.7/site-packages (from twisted>=17.5->daphne)
Requirement already up-to-date: zope.interface>=3.6.0 in ./venv/lib/python2.7/site-packages (from twisted>=17.5->daphne)
Requirement already up-to-date: constantly>=15.1 in ./venv/lib/python2.7/site-packages (from twisted>=17.5->daphne)
Requirement already up-to-date: six>=1.10.0 in ./venv/lib/python2.7/site-packages (from autobahn>=0.18->daphne)
Requirement already up-to-date: txaio>=2.7.0 in ./venv/lib/python2.7/site-packages (from autobahn>=0.18->daphne)
Requirement already up-to-date: attrs in ./venv/lib/python2.7/site-packages (from Automat>=0.3.0->twisted>=17.5->daphne)
Requirement already up-to-date: setuptools in ./venv/lib/python2.7/site-packages (from zope.interface>=3.6.0->twisted>=17.5->daphne)
```

Please help.

**Comment by bastbnl** [comment]
You need python 3
