### ISSUE TITLE
Where did channels Groups go?

### ISSUE THREAD

**Issue by japrogramer** [django/channels#851]
I have read the new docs for 2.0 and the upgrade guide ... I found that there is very little mention of how Group was replaced or how to upgrade that code which uses it.

[Here is where an example would go .. but no example is there.](https://channels.readthedocs.io/en/latest/introduction.html#cross-process-communication)

[Here is another mention of groups but no example on how to add and remove reply channels or as they seem to now be called self.channel_name I could be wrong please correct me if so.](http://channels.readthedocs.io/en/latest/topics/channel_layers.html#synchronous-functions)

```
root@a65e714bf993:/app# ../entrypoint.py ../start-dev.sh
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 120, in populate
    app_config.ready()
  File "/app/apple/product/apps.py", line 10, in ready
    __import__(self.name + '.signals', fromlist=[None])
  File "/app/apple/product/signals.py", line 5, in <module>
    from graphquery.utils import send_update
  File "/app/apple/graphquery/utils.py", line 1, in <module>
    from channels import Group
ImportError: cannot import name 'Group'
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 120, in populate
    app_config.ready()
  File "/app/apple/product/apps.py", line 10, in ready
    __import__(self.name + '.signals', fromlist=[None])
  File "/app/apple/product/signals.py", line 5, in <module>
    from graphquery.utils import send_update
  File "/app/apple/graphquery/utils.py", line 1, in <module>
    from channels import Group
ImportError: cannot import name 'Group'
exiting: ...
root@a65e714bf993:/app# exit
```

**Comment by andrewgodwin** [comment]
The `Group` object is now gone, and instead you're meant to just use the `group_add`, `group_discard`, and `group_send` methods on the `self.channel_layer` object inside of a consumer directly.

You can see an example here: http://channels.readthedocs.io/en/latest/topics/channel_layers.html#groups - I'll also add a note to the conversion docs.

**Comment by bastbnl** [comment]
I found sending a message from something like celery to a group is done via group_send on the instance that is returned by get_channel_layer. Right?

**Comment by andrewgodwin** [comment]
Right. I'll add an example for that in too.
