### ISSUE TITLE
builtins.AssertionError: 

### ISSUE THREAD

**Issue by atulherenow** [django/channels#899]
Using 
Python 3.4,
Django==1.9.6,  
daphne==0.11.3,
channels==0.12.0

> Unhandled Error
Traceback (most recent call last):
  File "/home/vaio/.virtualenvs/omapiv3/lib/python3.4/site-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/vaio/.virtualenvs/omapiv3/lib/python3.4/site-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/vaio/.virtualenvs/omapiv3/lib/python3.4/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/vaio/.virtualenvs/omapiv3/lib/python3.4/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/vaio/.virtualenvs/omapiv3/lib/python3.4/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/vaio/.virtualenvs/omapiv3/lib/python3.4/site-packages/twisted/internet/tcp.py", line 209, in doRead
    return self._dataReceived(data)
  File "/home/vaio/.virtualenvs/omapiv3/lib/python3.4/site-packages/twisted/internet/tcp.py", line 215, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/vaio/.virtualenvs/omapiv3/lib/python3.4/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
    why = self.lineReceived(line)
  File "/home/vaio/.virtualenvs/omapiv3/lib/python3.4/site-packages/twisted/web/http.py", line 1662, in lineReceived
    request = self.requestFactory(self, len(self.requests))
  File "/home/vaio/.virtualenvs/omapiv3/lib/python3.4/site-packages/daphne/http_protocol.py", line 49, in __init__
    self.reply_channel = self.factory.channel_layer.new_channel("http.response!")
  File "/home/vaio/.virtualenvs/omapiv3/lib/python3.4/site-packages/asgi_redis/core.py", line 225, in new_channel
    assert pattern.endswith("?")
builtins.AssertionError:

**Comment by andrewgodwin** [comment]
I'm afraid this is for an old version of Channels that's no longer supported - I won't be able to help you too much. All I can suggest is making sure you have the most recent `asgi_redis` 1.x release (1.4.3).

**Comment by atulherenow** [comment]
thank you @andrewgodwin you were right issue was due to version and asgi-redis==1.4.3 , channels==1.1.8 fix the issue for me
